### PR TITLE
feat(logging)_: introduce custom zap.Core enabling runtime changes

### LINKED ISSUE #6023: Enable runtime log configuration for zap.Logger
Currently, the geth logger supports [overriding](https://github.com/status-im/status-go/blob/7617bdd2ef3abb8c1fb71534be74aa5b25dbc0e6/logutils/override.go#L46) log level, format, and writer at runtime. zap.Logger does not support it out of the box, to achieve similar functionality with zap.Logger, a custom zap.Core must be introduced.

### PR DESCRIPTION
**Pull request by osmaczko**
Geth logger allows overriding the log level, format and writer at runtime. To make it interchangeable with zap.Logger, a custom zap.Core has been introduced to enable these features as well.

closes: #6023

### CODE REVIEW

**Review by igor-sirotin — APPROVED** [review]
Noice 👍 
Is this not too harmful for performance?

**Comment by osmaczko** [comment]
> Noice 👍 Is this not too harmful for performance?

Thanks! Overriding the log level, format, and writer isn’t a common operation—usually it's done only once per user account lifetime—so I wouldn’t worry about performance here. As for the writes, since I used atomics, performance should be solid (no locks on write from multiple goroutines). I’ll look into creating a benchmark.

**Review by qfrank — APPROVED** [review]
no usage for the custom zap.Core yet?

**Comment by osmaczko** [comment]
> no usage for the custom zap.Core yet?

There is a followup PR I am finalizing: https://github.com/status-im/status-go/pull/6025/

**Comment by osmaczko** [comment]
@igor-sirotin created a benchmark for zap.Core and custom core. Result looks fine, seems there is no performance penalty due to use of atomics.

```
$ go test -bench .
goos: linux
goarch: amd64
pkg: github.com/status-im/status-go/logutils
cpu: AMD Ryzen 7 4800HS with Radeon Graphics         
BenchmarkCustomCore-16           1061532              1118 ns/op
BenchmarkZapCore-16              1000000              1057 ns/op
```

**Pull request merged**
