### PR TITLE
added function which creates an account from the provided mnemonic

### PR DESCRIPTION
**Pull request by saledjenic**
Added function creates an account from the provided mnemonic

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]
I think it's okay but would like for @cammellos to give his blessings to this PR :)

**Comment by 0x-r4bbit** [comment]
Can we have a test for this?

**Review by Samyoul — APPROVED** [review]
This PR is fine, as long as all you want to do is get only the master key generated from the mnemonic without doing anything else with the key.

Basically `ImportMnemonic` but no storing in memory

**Comment by saledjenic** [comment]
> Can we have a test for this?

@PascalPrecht test is added.

**Review by 0x-r4bbit — APPROVED** [review]

**Pull request merged**
