### PR TITLE
fix: remove mailserver topic when deactivating a chat

### PR DESCRIPTION
**Pull request by richard-ramos**
This fixes an issue where re-joining a chat does not load the messages again from the mailserver

### CODE REVIEW

**Comment by richard-ramos** [comment]
Might be a good idea to test this with status-react!

**Review by 0x-r4bbit — APPROVED** [review]
Changes LGTM but it seems like this is failing some tests

**Comment by 0x-r4bbit** [comment]
Seems to be still failing..

**Comment by 0x-r4bbit** [comment]
Once squashed, this seems to be gtg

**Review by 0x-r4bbit — APPROVED** [review]

**Review by cammellos — APPROVED** [review]
Version change is missing, otherwise look good, would you mind testing it works as expected before merging?

**Comment by richard-ramos** [comment]
I did test on deskop. But I do not know how to test this status-go version in status-react

**Comment by cammellos** [comment]
@richard-ramos desktop is fine, if it works there it should work in status-react (in most cases), so no need to test there.
Thanks!

**Pull request merged**
