### PR TITLE
Hash password before passing it as a pragma

### PR DESCRIPTION
**Pull request by dshulyak**
issue in react: https://github.com/status-im/status-react/issues/8702

### CODE REVIEW

**Comment by cammellos** [comment]
@dshulyak looks good to me, one thing, how does this fit with  https://github.com/status-im/status-go/issues/1562 ? if we will share the database we then won't need to do this here I take (or at leas we should be using the same hashing :) )

**Comment by dshulyak** [comment]
> if we will share the database we then won't need to do this here I take 

@cammellos we will have to do it somewhere. why not here? 
as i understand we will need to open database and then pass it to appdatabase module and protocol database module where migrations will be applied. if you want to use another sqlite module (from protocol lib) i definitely have nothing against it, but technically i don't see any difference

**Comment by cammellos** [comment]
@dshulyak sure by all means, I meant that probably we might want to handle the two issues together, but it's all fine by me. Seems like though this might not be strictly necessary, as status-react will pass the hashed password, https://github.com/status-im/status-react/issues/8702#event-2553731323 , what do you think? I guess we could still keep it, no harm in it

**Comment by dshulyak** [comment]
that makes sense. one thing is that ethereum accounts manager, that we are using in account module, was using password for kdf. but if we are ignoring backward compatibility it can just start using hash i guess

**Comment by dshulyak** [comment]
@cammellos as i understand this is an optional change, please let me know if i misunderstood smth

**Pull request closed without merging**
