### PR TITLE
using zap.NewNop() ignores configured log level

### PR DESCRIPTION
**Pull request by jakubgs**
Our hosts are flooded with `DEBUG` level logs about each and every message multiplied by N number of log messages.

### CODE REVIEW

**Comment by jakubgs** [comment]
I still think there is an issue in `protocol/encryption/publisher/publisher.go` which causes logs like this to appear:
```
2021-02-04T18:18:35.250Z#011DEBUG#011publisher/publisher.go:85#011not enough time passed#011{"Publisher": {"site": "tickerLoop"}}
2021-02-04T18:20:35.250Z#011DEBUG#011publisher/publisher.go:85#011not enough time passed#011{"Publisher": {"site": "tickerLoop"}}
2021-02-04T18:22:35.250Z#011DEBUG#011publisher/publisher.go:85#011not enough time passed#011{"Publisher": {"site": "tickerLoop"}}
```
Despite log level `INFO` being configured on the host:
```
admin@mail-01.do-ams3.eth.test:~ % grep LogLevel /docker/statusd-mail/node/conf/config.json 
  "LogLevel": "INFO",
```
So something is still fishy.

**Comment by jakubgs** [comment]
I can't use `logutils` inside of `protocol/encryption/publisher/publisher.go` because of a dependency loop:
```
package github.com/status-im/status-go/cmd/statusd
	imports github.com/status-im/status-go/api
	imports github.com/status-im/status-go/account
	imports github.com/status-im/status-go/eth-node/bridge/geth
	imports github.com/status-im/status-go/waku
	imports github.com/status-im/status-go/logutils
	imports github.com/status-im/status-go/params
	imports github.com/status-im/status-go/protocol/pushnotificationserver
	imports github.com/status-im/status-go/protocol/common
	imports github.com/status-im/status-go/protocol/encryption
	imports github.com/status-im/status-go/protocol/encryption/publisher
	imports github.com/status-im/status-go/logutils: import cycle not allowed
make: *** [Makefile:79: statusgo] Error 1
```

**Comment by jakubgs** [comment]
The issue is specifically with this debug log level line:
https://github.com/status-im/status-go/blob/f6dc6f752ac87ff3f05e235aec18ad2bc36da791/protocol/encryption/publisher/publisher.go#L85
Because the logger doesn't inherit the node log level this debug message spams logs even if log level is info.

**Comment by jakubgs** [comment]
Thanks @Samyoul for removing the dependency of `logutils` on `params`. That fixes the dependency loop.

**Review by cammellos — APPROVED** [review]

**Review by Samyoul — APPROVED** [review]
Not sure how much my approval is worth on this PR, but *Approved*

**Comment by williamdes** [comment]
Hi @Samyoul 
I am very sorry as this is not the best place to contact you, but I am trying to contact you by email&GitHub.
(trying a last chance ping as you still seem active)

**Pull request merged**
