### PR TITLE
feat: introduce `AddBookmark`, `RemoveBookmark` and `UpdateBookmark` APIs to messenger

### LINKED ISSUE #2706: Introduce messenger RPC APIs for storing and deleting bookmarks
Further discussions around implementing #2704 and #2705 have resulted in the decision that we need dedicated RPC APIs in the messenger to take care of syncing bookmarks when clients attempt to store or remove them.

Essentially what this would look like otherwise right now, is that clients use `StoreBookmark` and `RemoveBookmark` APIs provided by the bookmark service, which operates right on the database. This means clients will have to manually perform the syncing as this functionality isn't available inside services.

Therefore it's better to have dedicated `StoreBookmark` and `RemoveBookmark` APIs on the messenger level where we **do** have the sync capabilities, allowing us to do that work implicitly without clients having to worry about it.

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
These APIs are being introduced to address https://github.com/status-im/status-go/issues/2706 and https://github.com/status-im/status-go/issues/2704, provided
that clients will move to using these APIs instead of the currently
provided equivalent APIs in the browser service.

The `bookmarks` table is being extended with a `deleted_at` field which
can later be used for garbage collection, as "removing" a bookmark is
merely soft deletion and doesn't actually remove the data from the
database.

In addition to those APIs adding and soft deleting bookmark entries,
they also automatically perform a sync operation to ensure that
bookmarks are synced in real-time (https://github.com/status-im/status-go/issues/2704).

Closes https://github.com/status-im/status-go/issues/2706, https://github.com/status-im/status-go/issues/2704

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status_go.html))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Comment by 0x-r4bbit** [comment]
@Samyoul @cammellos as always, only the first commit is relevant, second commit are build artifacts, will squash them once reviewed.

**Comment by 0x-r4bbit** [comment]
As for status mobile, once these APIs land and they make use of them, they no longer need to manually trigger the syncing of bookmarks (as currently happening here: https://github.com/status-im/status-react/blob/54c3030971c005c774883b721c422fc534b06456/src/status_im/browser/core.cljs#L103-L140)

**Review by cammellos — APPROVED** [review]

**Comment by 0x-r4bbit** [comment]
@churik @qoqobolo This one is ready for testing!

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-desktop/pull/6107 - to test on desktop

**Review by anastasiyaig — APPROVED** [review]

**Review by Samyoul — APPROVED** [review]

**Pull request merged**
