### PR TITLE
chore_: partially revert ContentTopicOverride

### PR DESCRIPTION
**Pull request by osmaczko**
Revert `ContentTopicOverride` and use `ContentTopic` only at `RawMessage` level.

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
This looks definitely cleaner.
I am wondering if these changes will work with phase-2 changes https://github.com/status-im/status-go/pull/5993.

Also with this change we are removing per chatID encryption that is being done for public chats at filters layer and using single sym encryption key which is derived from UniversalChatID. Is that fine?

**Review by chaitanyaprem — APPROVED** [review]
LGTM

tested with release version and chats work fine.

Thanks a lot @osmaczko for making this clean!

**Comment by osmaczko** [comment]
> This looks definitely cleaner. I am wondering if these changes will work with phase-2 changes #5993.
> 
> Also with this change we are removing per chatID encryption that is being done for public chats at filters layer and using single sym encryption key which is derived from UniversalChatID. Is that fine?

I believe single key is fine, all keys for public chats are not secret anyway (as they are simply derived from chat name).

**Comment by osmaczko** [comment]
> LGTM
> 
> tested with release version and chats work fine.
> 
> Thanks a lot @osmaczko for making this clean!

No problem. Sorry it took that long :pray:

**Pull request merged**
