### PR TITLE
Update dependency: google.golang.org/protobuf

### PR DESCRIPTION
**Pull request by Parveshdhull**
Update `google.golang.org/protobuf` to `v1.26.0`

https://github.com/status-im/status-go/pull/2366#issuecomment-921280829

### CODE REVIEW

**Review by Samyoul — CHANGES_REQUESTED** [review]
There are some strange things in this PR.

Did you update the generated files (`bindata.go`) using `make generate`? The changes look manual.

**Comment by Parveshdhull** [comment]
> There are some strange things in this PR.
> 
> Did you update the generated files (`bindata.go`) using `make generate`? The changes look manual.

Hi @Samyoul,
Yes, I generated using `make generate`.
(I recently updated go-bindata to version 3.1.2, maybe it is creating strange behavior?) 
I also tried running it again in a fresh branch and it is generating the same results.

**Comment by Samyoul** [comment]
Ah, I think you may need to run `make setup` in your `status-go` dir. We use a forked version of bin-data

**Comment by Parveshdhull** [comment]
> Ah, I think you may need to run `make setup` in your `status-go` dir. We use a forked version of bin-data

Yes, that was the problem. Thanks

**Comment by Parveshdhull** [comment]
I think it is no longer updating `google.golang.org/protobuf` should I close this PR?

**Comment by Parveshdhull** [comment]
Sorry, I closed this PR when I thought google.golang.org/protobuf is not updating when I tried `make generate` after `make setup`. But I had just forgotten to run `make vendor`

**Comment by Parveshdhull** [comment]
Changes already merged 👍

**Pull request closed without merging**
