### PR TITLE
Make it possible to mark individual notifications as read

### PR DESCRIPTION
**Pull request by jrainville**
Adds the `MarkActivityCenterNotificationsRead` function to mark one or more activity center notifications as read instead of only having mark all as read.

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Comment by jrainville** [comment]
Is there a reason why Jenkins is failing? I tried to understand where it failed and couldn't. Are my new tests failing?

**Comment by Samyoul** [comment]
Hey, I've just spotted this message. The full fail log is here https://ci.status.im/blue/rest/organizations/jenkins/pipelines/status-go/pipelines/prs/pipelines/tests/branches/PR-2256/runs/1/nodes/74/steps/77/log/?start=0

It seems that the failed test is this:

```
[2021-06-08T15:43:45.555Z] --- FAIL: TestActivityCenterPersistence (0.55s)
[2021-06-08T15:43:45.555Z]     persistence_test.go:1204: 
[2021-06-08T15:43:45.555Z]         	Error Trace:	persistence_test.go:1204
[2021-06-08T15:43:45.555Z]         	Error:      	Should be true
[2021-06-08T15:43:45.555Z]         	Test:       	TestActivityCenterPersistence
[2021-06-08T15:43:45.555Z] FAIL
[2021-06-08T15:43:45.555Z] FAIL	github.com/status-im/status-go/protocol	99.364s
[2021-06-08T15:43:45.555Z] ?   	github.com/status-im/status-go/protocol/audio	[no test files]
```

**Comment by Samyoul** [comment]
@jrainville I've also made a couple of quick videos that show how you can find the logs and how to find the fails in the logs.

<a href="https://www.loom.com/share/2dcf044452ba4ee09d74dc27539cec68" target="_blank"> <p>How to find the full test logs of a failed test</p>  </a>

<a href="https://www.loom.com/share/0a64b7c7cd674536a9c9f3b1c1c7ae7d" target="_blank">
    <p>How to find the failed test in the full test logs</p>
    
  </a>

**Review by Samyoul — APPROVED** [review]

**Comment by jrainville** [comment]
@Samyoul thanks a lot for the guide. I had no idea there was a complete log.

I'll fix the test right away!

**Pull request merged**
