### PR TITLE
feat: add function to obtain the current bloomfilter

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Looks good, but I see no explanation in your commit as to WHY you need this change. What is it for? It's kinda in a vacuum. At least link a relevant desktop/mobile issue so it's clear what this is necessary for.

**Comment by richard-ramos** [comment]
> Looks good, but I see no explanation in your commit as to WHY you need this change. What is it for? It's kinda in a vacuum. At least link a relevant desktop/mobile issue so it's clear what this is necessary for.

I exposed the bloom filter so we're able to display the % of use on desktop in the node management tab like this:
image

Relevant PR:
https://github.com/status-im/status-desktop/pull/3286

**Comment by jakubgs** [comment]
@richard-ramos that's neat. But please include that information in the commit and PR description as well.

**Comment by iurimatias** [comment]
tested in https://github.com/status-im/status-desktop/pull/3286

**Comment by jakubgs** [comment]
@iurimatias you merged it before @richard-ramos updated the commit to include the purpose.

**Pull request merged**
