### PR TITLE
0.9.25 hotfix 2 for ETHIndia

### PR DESCRIPTION
**Pull request by mandrigin**
based on the previous hotfix `release/0.9.24`

### CODE REVIEW

**Review by adambabik — APPROVED** [review]
LGTM

This can be problematic if we run e2e tests on Rinkeby but it's disabled for now because Rinkeby does not sync anymore. Will it be cherry-picked to develop?

**Comment by mandrigin** [comment]
@adambabik it probably should be, and probably should be cherry-picked to 0.10.0 too...

**Comment by adambabik** [comment]
Ok. I will create 0.10.1 when it's done.

**Comment by divan** [comment]
@mandrigin could you please provide more information about this PR? I loosely remember the issue from chat conversations, but definitely not enough to assess this fix.
Or it's not a subject for merging at all?

**Comment by mandrigin** [comment]
@divan it will be. the gist is that rinkeby users should be able to chat with other networks.
we used to have it completely separate and never used it. but now, with ETHIndia we have to use Rinkeby users, so we want the same interoperability between Rinkeby/Mainnet users as with Ropsten/Mainnet.

**Comment by divan** [comment]
@mandrigin thanks, and why it's being pushed into the `release/0.9.24` branch?

**Comment by mandrigin** [comment]
@divan just to make the diff contain only the changes that I added. When this PR was created, I believe, the fixup for the shh endpoints wasn't in develop yet.
Anyway, I will later re-open it as a separate PR to `develop`.

**Comment by mandrigin** [comment]
replaced by https://github.com/status-im/status-go/pull/1147

**Pull request closed without merging**
