### PR TITLE
Add config required to debug statusd on VS Code

### PR DESCRIPTION
**Pull request by pedropombeiro**

### CODE REVIEW

**Comment by adambabik** [comment]
Isn't it a custom setting? `.vscode` should be ignored just like `/.idea/` and other editor specific directories.

**Comment by pedropombeiro** [comment]
@adambabik `/cmd/*/.debug` refers to the executable that gets generated in the current folder when you press F5 to start debugging (configured [here](https://github.com/status-im/status-go/pull/875/files#diff-3090e25fed17a6bd57433c6bbadc451aR19)). We could make it build the app in `build/bin/status` but maybe it is better not to interfere with that one.

**Comment by dshulyak** [comment]
it looks like that @adambabik referred to this file `.vscode/launch.json` , it is not gitignored by intention?

**Comment by pedropombeiro** [comment]
@adambabik @dshulyak I think there is value in having `.vscode/launch.json` in the repo since it gives you an initial working configuration, but we can definitely .gitignore the rest of the folder.

**Comment by divan** [comment]
As `launch.json` has nothing to do with `status-go`, but does with the tool (VSCode/delve), I'd rather add the `launch.json` and short instructions on how to debug with VSCode into project's wiki (or even README, if it's short).

**Comment by pedropombeiro** [comment]
@divan Sure, we can also do that. I like the idea of adding a short instruction to the README.md, so that new contributors are aware that VS Code can easily be set up to debug the project. I personally don't see an issue with havings the file from the hidden folder already present when you clone the project, so I'll defer to a vote. @adambabik @dshulyak, what are your thoughts on that, any preference?

**Comment by adambabik** [comment]
Rule of thumb is not to include editor config files because each person can have it different and this addition would make it hard for those people. We can rename it to `.vscode/launch.example.json` to avoid name clashing.

**Comment by pedropombeiro** [comment]
OK, implemented that as well as a short description in `README.md`

**Review by adambabik — APPROVED** [review]

**Review by divan — APPROVED** [review]
LGTM

**Pull request merged**
