### PR TITLE
Fix/endless logout

### PR DESCRIPTION
**Pull request by qfrank**
comparison after optimization:

before optimization

after optimization

this PR also added some debug logs.

relate mobile [issue](https://github.com/status-im/status-mobile/issues/18063)

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Review by siddarthkay — APPROVED** [review]
changes in `multiaccounts/settings/mocks/database_data_retriever_mock.go` and
`multiaccounts/settings/mocks/database_info_retriever_mock.go` could be reverted in this PR since they are just whitespace changes.

also do you still want those debug messages logged? 

rest looks good @qfrank ! nice work.

**Comment by qfrank** [comment]
> changes in multiaccounts/settings/mocks/database_data_retriever_mock.go and
multiaccounts/settings/mocks/database_info_retriever_mock.go could be reverted in this PR since they are just whitespace changes.

it's the result of `make lint-fix` and i don't want to see the changes in my git change list next time 🙂

> also do you still want those debug messages logged?

yes, i think it make sense sometimes e.g. help check where time consumed. WDYT? @siddarthkay

**Comment by siddarthkay** [comment]
Sounds good to keep them then 👍

**Review by vitvly — APPROVED** [review]
Beautiful. Thanks for adding helpful code comments too.

**Comment by jakubgs** [comment]
Your branch is WAY out of date dude:
```
There are no nodes with the label ‘macos && aarch64 && xcode-14.3 && nix-2.14’
```
https://ci.status.im/job/status-go/job/prs/job/ios/job/PR-4563/1/console

Look at the Xcode label.

**Pull request merged**
