### PR TITLE
Fix/tokens block range nil access

### PR DESCRIPTION
**Pull request by IvanBelyakoff**
On empty acc access to a nil pointer is fixed
Fixed a crash on a nil block number in local notification service on HistoryReady event

### CODE REVIEW

**Review by Cuteivist — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Comment by siddarthkay** [comment]
@IvanBelyakoff : do you mind if we verify this fix with a PR in mobile repo?
I can create that PR.

cc @cammellos @churik

**Comment by IvanBelyakoff** [comment]
> @IvanBelyakoff : do you mind if we verify this fix with a PR in mobile repo? I can create that PR.
> 
> cc @cammellos @churik

sure go ahead

**Comment by siddarthkay** [comment]
@IvanBelyakoff : Thanks a lot for the swift fix :) we'll run E2E suite here https://github.com/status-im/status-mobile/pull/18110

**Comment by IvanBelyakoff** [comment]
@cammellos I treated `NoRows` as no error when getting wallet preferences. Is it ok with you? Could you please have a look

**Comment by churik** [comment]
@IvanBelyakoff can you please take a look to not successful checks before we take PR to test again?
Thanks!

**Comment by IvanBelyakoff** [comment]
> @IvanBelyakoff can you please take a look to not successful checks before we take PR to test again? Thanks!

I believe the tests failure is not related to my PR, the tests pass successfully locally on my PC. I will restart them several times until they pass, but if you wan tto test it, I don't think you need to wait for them to pass

**Comment by churik** [comment]
@siddarthkay can you please update status-go in our status-mobile Pr?

**Comment by siddarthkay** [comment]
> @siddarthkay can you please update status-go in our status-mobile Pr?

updated a while ago, confirmed that current status-go commit hash match our status-go-version.json

**Review by siddarthkay — APPROVED** [review]
Lets go! 🚀

**Comment by pavloburykh** [comment]
@IvanBelyakoff thank you for the fix. [Tested](https://github.com/status-im/status-mobile/pull/18110#issuecomment-1845539122) manually and no crash is detected. Failed e2e either known or related to global data delivery issues. Ready for merge.

**Pull request merged**
