### PR TITLE
feat(accounts)_: cherry-pick Persist acceptance of Terms of Use & Privacy policy (#5766)

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/16566

There was a migration applied to the 0.182.x (2.30) branch that was never ported to the develop branch, so any account that tried to upgrade from 2.30 to 2.31 just didn't work.

It will be fixed with this.

### CODE REVIEW

**Review by dlipicar — APPROVED** [review]

**Comment by ilmotta** [comment]
@jrainville shouldn't we bring into `develop` the entire work of https://github.com/status-im/status-go/pull/5766/files, not just the migration file? I was going to create this cherry-pick PR from 2.30 release branch today.

Since you already opened this PR and https://github.com/status-im/status-go/pull/5977, if you want, I can update both of them to bring the full implementation along with the migration file. I'm offering to help because I intentionally kept postponing cherry-picking because I had agreed with @igor-sirotin that we would do a better implementation for release 2.31, but other priorities really got on my way since then (see https://github.com/status-im/status-go/pull/5766#discussion_r1730875111)

**Comment by ilmotta** [comment]
@jrainville, I'm marking this PR as a draft because it should wait until the status-go PR https://github.com/status-im/status-go/pull/5977 is merged into `develop`. I already opened the mobile PR for the `develop` branch https://github.com/status-im/status-mobile/pull/21487. Once the mobile PR is approved by QAs we can proceed to merge and update the release branches.

I believe the PRs will be QAed relatively quickly because they were already tested for 2.30. I'm playing safe because the original PRs in 2.30 are somewhat old already.

**Comment by jrainville** [comment]
> @jrainville, I'm marking this PR as a draft because it should wait until the status-go PR #5977 is merged into `develop`. I already opened the mobile PR for the `develop` branch [status-im/status-mobile#21487](https://github.com/status-im/status-mobile/pull/21487). Once the mobile PR is approved by QAs we can proceed to merge and update the release branches.
> 
> I believe the PRs will be QAed relatively quickly because they were already tested for 2.30. I'm playing safe because the original PRs in 2.30 are somewhat old already.

@ilmotta my bad, I saw this comment after I saw the changes you did to the develop PR, so I already merged the develop PR.

I'll obviously still wait for the QA tests to merge the release PR. 

Sorry for skipping a step. I also thought that since it was a cherry-pick, it couldn't hurt, especially in the develop branch after the cut was done.

**Comment by jrainville** [comment]
:heavy_check_mark:  Desktop approved by @glitchminer https://github.com/status-im/status-desktop/pull/16572#issuecomment-2432462649

**Review by glitchminer — APPROVED** [review]

**Pull request merged**
