### PR TITLE
fix_: native token not found error when generating a new route issue fixed

### LINKED ISSUE #21252: "Native token not found" error message randomly occurs on the routes generation page
Follow up for https://github.com/status-im/status-mobile/pull/21235

Unfortunately, this issue doesn't occur consistently, and there are no exact steps to reproduce it. However, it seems to happen after attempting to find routes upon entering valid data into the input field. Hopefully, the logs will help.

### Steps:
1. Enter valid data into the routes generation page to build the routes

### Actual result:
"Native token not found" error message is shown
image

### Expected result:
No errors are shown, routes are build

### Devices:
- Pixel 7a, Android 13
- iPhone 11 Pro Max, IOS 17

### Logs
[Status-debug-logs (2).zip](https://github.com/user-attachments/files/16959963/Status-debug-logs.2.zip)

### PR DESCRIPTION
**Pull request by saledjenic**
This commit fixes `native token not found` issue that occurs only when the input params of an already successfully generated route for a fast chain (refers to a chain that generates new blocks very fast, like optimism, arbitrum) are updated.

The reason for the issue was that the active route remains the same until the resolving of a new route for updated input parameters gets generated, for fast chains that was enough time to generate a new block and send fees update for the previously active route. This commit fixes that possibility by aborting updates in a better way.

Fixes https://github.com/status-im/status-mobile/issues/21252

### CODE REVIEW

**Review by shivekkhurana — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Comment by pavloburykh** [comment]
@saledjenic thank you for this PR. I see 1 Test has failed https://github.com/status-im/status-go/pull/5931#issuecomment-2403326682 Should we look at it before proceeding with testing or we are good to start testing now?

**Comment by saledjenic** [comment]
@pavloburykh I've just updated it now, let's see if all is green and if so you are free to proceed with testing.

**Comment by pavloburykh** [comment]
> @pavloburykh I've just updated it now, let's see if all is green and if so you are free to proceed with testing.

@saledjenic looks good now, thank you. We will proceed with testing tomorrow.

**Comment by saledjenic** [comment]
@pavloburykh please let me know if you're ok with merging this?

**Comment by VolodLytvynenko** [comment]
> @pavloburykh please let me know if you're ok with merging this?

Hi @saledjenic thank you for a fix. PR does not affect mobile and fixes "native token not found" error. PR can be merged

**Review by pavloburykh — APPROVED** [review]

**Pull request merged**
