### PR TITLE
fix(message_persistence): don't return reply data of deleted messages

### PR DESCRIPTION
**Pull request by jrainville**
Needed for https://github.com/status-im/status-desktop/issues/7754

We don't want to populate the QuotedMessage when it was deleted

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Comment by jrainville** [comment]
@cammellos @0x-r4bbit gentle reminder to review

**Review by cammellos — APPROVED** [review]

**Comment by cammellos** [comment]
as usual, it'd be good to have a test @jrainville :)

**Comment by jrainville** [comment]
> as usual, it'd be good to have a test @jrainville :)

Stop being so right!

I'll do it :disappointed:

**Comment by jrainville** [comment]
Improved the reply test in persistence_test to test a deleted reply.
If it passes, I'll merge

**Pull request merged**
