### PR TITLE
Add configuration to enable whisper rate limiter

### PR DESCRIPTION
**Pull request by dshulyak**
whisper changes https://github.com/status-im/whisper/pull/1

### CODE REVIEW

**Comment by chadyj** [comment]
Hey @jacqueswww sent me over here! Today someone sent about 1000 messages to #openbounty. I've also seen this happen in #dapps. 

Will this PR help from this type of spam attack? If not, what can be done?

cc @PombeirP @cammellos @yenda we gotta figure out moderation!

screen shot 2018-10-26 at 1 30 39 pm

**Comment by cammellos** [comment]
Please also keep me in the loop, as for multidevice/group chat we sent multi-envelope messages, so I need to make sure they respect rate-limit

**Comment by chadyj** [comment]
This is what it looked like from the client

img_f9d4d5db13e0-1

**Comment by dshulyak** [comment]
@chadyj unfortunately, this change won't help in the described situation. on the transport level every message looks the same. this change will help if we are receiving more bytes then we expect. for example, we set the limit to 5 mb per second, but we receive from a peer 10 mb per second. such peer will be disconnected.

one extension that is not added in this pr but already implemented, is a per topic/chat rate limit. again it is not content aware. for example, if we set a rate limit for a topic to be 100 per second, but we receive 1 mb per second, we can suspect that someone spams it. but the only thing we can do is to unsubscribe from such topic completely.

as for the described issue, I think the proper way to solve it is to have content aware moderation or visibility stake, that was discussed before.

**Comment by dshulyak** [comment]
I will reopen when we will get back to ratelimiting

**Pull request closed without merging**
