### PR TITLE
markdown: add strong emphasis and fix strikethrough

### PR DESCRIPTION
**Pull request by rasom**
add this commit https://github.com/status-im/markdown/pull/1

What's changed:
Add StrongEmph node for triple `"*"`/`"_"`
Add proper marshaling for Del node

status: ready

### CODE REVIEW

**Review by jakubgs — CHANGES_REQUESTED** [review]
What is "Update markdown module" supposed to mean? It's not telling me what has been changed at all.

**Comment by rasom** [comment]
@jakubgs what's a protocol here regularly? To put an entire changes set from another repo to commit's message? :)

**Comment by jakubgs** [comment]
Explain why are you making this change, or in your words "update". Why was it necessary? I'm sure it's necessary for some reason, otherwise you wouldn't be doing it, right?

**Comment by rasom** [comment]
@jakubgs, added to PR's description. Need more details?

**Comment by jakubgs** [comment]
So is my undestanding correct that these are impvements/fixes for emphasis and strikethrough in our markdown?

Then I'd change the commit message to reflect that. Something like `markdown: improve emphasis and strikethrough`.

**Comment by rasom** [comment]
@jakubgs done, something else?

**Review by jakubgs — APPROVED** [review]
LGTM. Though I'd try it in a PR build for `status-react` first before merging.

**Comment by rasom** [comment]
@jakubgs sure https://github.com/status-im/status-react/pull/11307

**Pull request merged**
