### PR TITLE
migrate to go 1.12 and go modules

### PR DESCRIPTION
**Pull request by adambabik**
This problem surfaced when we wanted to upgrade https://github.com/status-im/migrate to v4. Because dep does not work well with go modules and migrate v4 does support go modules syntax, it is currently not possible to have both work. Check out https://github.com/golang/dep/pull/1963 and https://github.com/golang/dep/issues/1962.

In this PR, Go is upgraded to 1.12 and dependencies are migrated from dep to go modules.

### CODE REVIEW

**Comment by adambabik** [comment]
iOS build fails with:
```
failed (/Users/jenkins/workspace/status-go_prs_ios_PR-1485/src/github.com/status-im/status-go/vendor/github.com/libp2p/go-reuseport/interface.go:33:20: ListenConfig not declared by package net
```
This suggests that `net.ListenConfig` is not declared and `net` means standard library. `ListenConfig` was added in Go 1.11 which suggest we have older Go version on servers building iOS binaries. @jakubgs can you please check that?

**Review by dshulyak — APPROVED** [review]

**Comment by adambabik** [comment]
I confirmed that on macOS Jenkins executors we have Go in version 1.10 and that's why the iOS build does not pass.

**Comment by jakubgs** [comment]
I've migrated the CI hosts to `1.12`: https://github.com/status-im/infra-ci/commit/4c9bcdce
```
 $ ansible ci-slave-linux -o -a 'go version'                                    
linux-01.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12 linux/amd64
linux-05.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12 linux/amd64
linux-04.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12 linux/amd64
linux-03.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12 linux/amd64
linux-02.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12 linux/amd64
```

**Comment by jakubgs** [comment]
Apparently it was supposed to be `1.12.5` so I did that, and also made the role deploy on MacOS:
https://github.com/status-im/infra-ci/commit/11db232b5cbaf0c95cc2faeca05660402bb2d408
Looks good now:
```
 $ ansible ci-slave-linux,ci-slave-macos -o -a '/usr/local/bin/go version' 
linux-03.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 linux/amd64
linux-05.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 linux/amd64
linux-01.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 linux/amd64
linux-04.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 linux/amd64
linux-02.do-ams3.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 linux/amd64
macos-02.ms-eu-dublin.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 darwin/amd64
macos-03.ms-eu-dublin.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 darwin/amd64
macos-01.ms-eu-dublin.ci.misc | CHANGED | rc=0 | (stdout) go version go1.12.5 darwin/amd64
```

**Comment by jakubgs** [comment]
Adjusted the `golang` role to remove old sources before installing new ones: https://github.com/status-im/infra-ci/commit/38d6c6f290de95f90cbfc5a955ad778f6bbebc43

**Comment by jakubgs** [comment]
You can try cherry picking 04c4c84945c992c34a6ed25342d663d048c7e8e5 for your branch.
Seems to work based on this manual build:
https://ci.status.im/job/status-go/job/manual/419/
Only `xgo` build fails, not sure whats that about.

Also e0eaca2ed983cd09b0b8d51c90d0aaee1667d6b7 would probably be a good idea to update the docker image we use for building `status-go` image.

**Pull request merged**
