### PR TITLE
fix: check nil pointer in saveProfileShowcasePreferencesProto

### LINKED ISSUE #13756: Crash when restoring account
# Bug Report

## Description

When I try to restore an account that has money and communities on testnet, including owner tokens, it crashes.

Here is the seed phrase:
```
awesome fee remove flag cable powder link clog eyebrow noodle window hold
```

## Steps to reproduce

1. Open app
2. "Add existing Status user"
3. "I don't have other device"
4. "Enter a seed phrase"
5. Enter the seed phrase above
6. Press Restore
7. Crash

Not many useful logs:
```
WRN 2024-02-27 13:57:06.363-05:00 Error decoding signal                      topics="signals-manager" tid=1152287 file=signals_manager.nim:49 err="Unknown signal received: mediaserver.started"
2024-02-27T13:57:06-0500 unset [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on [::]:43747 (node id 4a4f13ec58087baf8c05cddf9fe8b165cd6dabc9) completed bootstrap ({NumAddrsTried:11 NumResponses:0})
DBG 2024-02-27 13:57:07.351-05:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=1152300 file=threadpool.nim:54 messageType=TimerTaskArg:ObjectType threadid=1152300 task="{\"$type\":\"TimerTaskArg:ObjectType\",\"timeoutInMilliseconds\":1000,\"reason\":\"\",\"vptr\":94524747352432,\"slot\":\"onTimeout\",\"tptr\":94524712399600}"
2024-02-27T13:57:07.660-0500	INFO	communities/manager.go:371	initializing history archive tasks
DBG 2024-02-27 13:57:08.353-05:00 [threadpool task thread] initiating task   topics="task-threadpool" tid=1152302 file=threadpool.nim:54 messageType=TimerTaskArg:ObjectType threadid=1152302 task="{\"$type\":\"TimerTaskArg:ObjectType\",\"timeoutInMilliseconds\":1000,\"reason\":\"\",\"vptr\":94524747352432,\"slot\":\"onTimeout\",\"tptr\":94524712399600}"
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
make: *** [Makefile:815: run-linux] Segmentation fault (core dumped)
```

#### Expected behavior

The restoration works or at least doesn't crash

#### Actual behavior

Crashes almost straight away.

### Additional Information

- Status desktop version: master `6de7032d65386b8d59168ef1908a3866aa3b854d
- Operating System: Ubuntu 20

### LINKED ISSUE #19023: App crashes after restore via seed phrase
Wait until this one https://github.com/status-im/status-mobile/pull/19024 will be merged (status go version bumped) in order to reproduce in mobile develop. 

**Steps:** 

1. Restore user via seedphrase
2. See if app does not crash after restoration

**Actual result:** app crashes. Works fine after relogin. 

[crashlog_restore.log.zip](https://github.com/status-im/status-mobile/files/14418458/crashlog_restore.log.zip)

https://github.com/status-im/status-mobile/assets/97245802/04ae5327-3fc8-4727-b422-3eea63ecfc34

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-mobile/issues/19023
Closes https://github.com/status-im/status-desktop/issues/13756

### CODE REVIEW

**Review by MishkaRogachev — APPROVED** [review]

**Comment by igor-sirotin** [comment]
@pavloburykh can you please make sure this PR fixes https://github.com/status-im/status-mobile/issues/19023? 🙂

**Comment by pavloburykh** [comment]
> @pavloburykh can you please make sure this PR fixes [status-im/status-mobile#19023](https://github.com/status-im/status-mobile/issues/19023)? 🙂

Thank you @igor-sirotin! Could you please rebase this PR so it also includes this commit https://github.com/status-im/status-go/commit/4fb27ec53a48f4621b0f7cb32248bd3f9517d394? I would like to test and make sure it does not cause regressions on mobile.

**Comment by igor-sirotin** [comment]
@pavloburykh sure, done 👌

**Comment by siddarthkay** [comment]
@pavloburykh : here -> https://github.com/status-im/status-mobile/pull/19027

**Review by pavloburykh — APPROVED** [review]

**Comment by pavloburykh** [comment]
@igor-sirotin thank you for the fix! Tested - works fine on mobile. Let's merge it and cherry pick the fix into release go branch.

**Pull request merged**
