### PR TITLE
fix(messenger_handler): fix checkForDeletes logic with images

### PR DESCRIPTION
**Pull request by jrainville**
Merges in a release branch for desktop

Fixes https://github.com/status-im/status-desktop/issues/10627

I messed up when I did the code to checkForDeletes for image albums.

The logic was all tangled up and we were trying to delete even if nothing was a delete. So, well, I fixed it.

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]
Fix LGTM. I'm only missing seeing updated unit tests to cover the correct behavior.

**Review by igor-sirotin — APPROVED** [review]

**Comment by jrainville** [comment]
> Fix LGTM. I'm only missing seeing updated unit tests to cover the correct behavior.

I tried and I can't reproduce the bug in a test :grimacing: 

The issue is such a weird edge case that if I revert the fix and try to make the test fail, it still passes :confused: 

I think I need to send an image with no Album, then delete it, but also have the delete arrive before the image, then try to send another image without an album and that will make it fail to process the new image.
So, I tried doing that in the test and it still passes, so I'm not sure. 

At least we know that the fixed code works in tests and in an in-app scenario :shrug:

**Comment by ilmotta** [comment]
> > Fix LGTM. I'm only missing seeing updated unit tests to cover the correct behavior.
> 
> I tried and I can't reproduce the bug in a test grimacing
> 
> The issue is such a weird edge case that if I revert the fix and try to make the test fail, it still passes confused
> 
> I think I need to send an image with no Album, then delete it, but also have the delete arrive before the image, then try to send another image without an album and that will make it fail to process the new image. So, I tried doing that in the test and it still passes, so I'm not sure.
> 
> At least we know that the fixed code works in tests and in an in-app scenario shrug

Ouch, you really did try, so there's not much to do :shrug: Thanks for the detailed context

**Comment by jrainville** [comment]
Re-asking for review because it turns out the old test was flawed and didn't even have a valid albumID.

So basically, the issue we faced in Desktop might have been caught by the test if the test actually did it's job correctly

**Review by ilmotta — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]

**Pull request merged**
