### PR TITLE
store customization color in settings

### PR DESCRIPTION
**Pull request by flexsurfer**
store customization color in settings

### CODE REVIEW

**Comment by qfrank** [comment]
I thought we only store customization color into table `accounts.customizationColor` ? 🤔 cc @cammellos

**Comment by cammellos** [comment]
> I thought we only store customization color into table `accounts.customizationColor` ? thinking cc @cammellos

we should probably store it in a single place, whether `accounts` or `settings` depends whether is used pre-login (`accounts` or post-login `settings`).

**Comment by qfrank** [comment]
I prefer only store it in `accounts` , implementation of syncing customization color is based on such assuming 😅, 
[draft of sync customization color](https://github.com/status-im/status-go/pull/3702) , currently we need customization color before login, right ?  cc @cammellos

**Comment by flexsurfer** [comment]
> we should probably store it in a single place, whether `accounts` or `settings` depends whether is used pre-login (`accounts` or post-login `settings`).

its needed before and after, same as name and image, but name and image stored in both tables and color not, so i just added color, i created an issue https://github.com/status-im/status-go/issues/3684 for changing this , but for now i just want to make it work similar to other fields

**Comment by cammellos** [comment]
> 

Ok, so probably we want to stop storing name/image in both tables, and just save it in one only (`accounts` if pre-login & only in `settings` for post-login)

**Comment by qfrank** [comment]
FYI, My draft PR added an API for updating customization color, i plan to finish it today or tomorrow @flexsurfer

**Comment by flexsurfer** [comment]
so currently we have an issue, we don't have color in settings, what we gonna do? @qfrank will it be fixed by your PR ?

**Comment by qfrank** [comment]
my two cents, if client want get and display customization color, endpoints `OpenAccounts` should already returned it, if we need update it, we can use [UpdateAccountCustomizationColor](https://github.com/status-im/status-go/blob/396cb285c054edffcd5e4c0eaa8c696cfa726236/services/accounts/multiaccounts.go#L33) , WDYT? cc @flexsurfer

**Comment by flexsurfer** [comment]
> my two cents, if client want get and display customization color, endpoints `OpenAccounts` should already returned it, if we need update it, we can use [UpdateAccountCustomizationColor](https://github.com/status-im/status-go/blob/396cb285c054edffcd5e4c0eaa8c696cfa726236/services/accounts/multiaccounts.go#L33) , WDYT? cc @flexsurfer

OpenAccounts is used only once when we open the app, then we use settings when we login into account, so doesn't looks as a good API, status-go should care about this, client doesn't care where and how status-go stores props, accounts is just part of settings but unencrypted , and im not sure `CustomizationColorUpdatedAt` should be stored in it, its more like a settings, we don't need it before login, but anyway, my suggestion to join tables when we request settings , so we get full settings after login

**Comment by flexsurfer** [comment]
for example when we create account, we login and load settings but there is no account's props in settings, so we have to load accounts get account by settings uid and merge some settings , this doesn't look great, we would expect to have all settings when we request them from status-go

**Comment by qfrank** [comment]
Frontend proberbly don't need to know existence of `CustomizationColorUpdatedAt`, it's used for syncing. 
If we only store CustomizationColor in `accounts` , can you adjust your PR so that we don't have two places store it? And I'll remove the endpoint `UpdateAccountCustomizationColor` in my PR

> for example when we create account, we login and load settings but there is no account's props in settings, so we have to load accounts get account by settings uid and merge some settings , this doesn't look great, we would expect to have all settings when we request them from status-go

Thank you for clarification! 🙂 @flexsurfer

**Comment by flexsurfer** [comment]
> can you adjust your PR so that we don't have two places store it?

i can't adjust it because its needed in both places, but i have an issues for that https://github.com/status-im/status-go/issues/3684 if you are interested you can take it please :)

**Comment by flexsurfer** [comment]
because we need need similar functionality for all "duplicated" fields like name image identical etc , so it should be done all in one PR, and as you (@qfrank) are working on syncing color, name and images are also should be synced, so we need to implement them the same way

**Comment by qfrank** [comment]
> if you are interested you can take it

okay, I'll take it when i got time 🙂

regarding adjusting, let's see what @cammellos would say ❤️

**Comment by flexsurfer** [comment]
hey @qfrank thank you, we decided to pause this PR, and @cammellos will take a look at the issue

**Pull request closed without merging**
