### PR TITLE
config: add new Push notifications fleet

### PR DESCRIPTION
**Pull request by cammellos**
Set push notification servers for status.prod.
Also drop no longer existing `eth.test` fleet.

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Review by qfrank — APPROVED** [review]

**Comment by qfrank** [comment]
oh, forgot to ask: we don't bump version for this minor modification? 🤔 @cammellos

**Comment by jakubgs** [comment]
I have added the `notify.prod` hosts to https://fleets.status.im/:

- https://github.com/status-im/infra-misc/commit/20358c1b - status-fleets: include notify.prod fleet

Result:
```
 > c -L fleets.status.im | jq '.fleets."notify.prod"[]'   
{
  "node-01.do-ams3.notify.prod": "enode://401ba5eda402678dc78a0a40fd0795f4ea8b1e34972c4d15cf33ac01292341c89f0cbc637fa9f7a3ffe0b9dfe90e9cdae7a14925500ab01b6a91c67bae42a97a@178.128.139.80:1443",
  "node-01.gc-us-central1-a.notify.prod": "enode://181141b1d111908aaf05f4788e6778ec07073a1d4e1ce43c73815c40ee4e7345a1cbf5a90a45f601bf3763f12be63b01624ba1f36eeb9572455e7034b8f9f2c4@34.71.141.140:1443",
  "node-01.ac-cn-hongkong-c.notify.prod": "enode://5ffc34d5ffda180d94cd3974d9ed2bb082ede68f342babdbe801ceffb7da902087d43f9aa961c7b85029358874c08ef04ecad9f1d95a1f0e448cbdd5d04350c7@47.242.88.117:1443"
}
```

**Review by jakubgs — APPROVED** [review]

**Comment by jakubgs** [comment]
It's not minor, we should bump version.

Though honestly I'm not sure why we bother with verisons.

**Comment by qfrank** [comment]
> Though honestly I'm not sure why we bother with verisons.

alright, i saw someone forget to do this sometimes, i won't bother with versions again

**Comment by cammellos** [comment]
@qfrank @jakubgs we need versioning to make sure we don't downgrade, if we used only the sha it's not immediately clear a downgrade happened (that's an issue we had in the past).

I should have bumped the version on this one, yes, thank you

**Comment by jakubgs** [comment]
>we need versioning to make sure we don't downgrade, if we used only the sha it's not immediately clear a downgrade happened (that's an issue we had in the past).

We could just include a timestamp of the commit in `status-go-version.json`. But I get it.

**Pull request merged**
