### PR TITLE
add file/stream log handlers to StatusNode

### LINKED ISSUE #819: status-go is not writing any logs on geth.log
# Problem

status-go logs stopped being written to geth.log when running status-react from iOS and Android.

# Implementation

Some research is still needed

# Acceptance Criteria

Logs persisted to geth.log showing up in device filesystem.

# Notes

Even the file `sdcard/Downloads/geth.log` it's created after allowing status-app to have access to the device, no logs are written.

Params are passed from status-react
```
"LogEnabled":true, "LogFile":"\/storage\/emulated\/0\/Download\/geth.log", "LogLevel":"INFO"
```

File is created, file is writable:
```
-rw-rw---- root     sdcard_rw        0 2018-04-10 14:53 geth.log
```

# Future Steps

Evaluate add tests to avoid this regresion

### PR DESCRIPTION
**Pull request by gravityblast**
Add file and stream log handlers for `github.com/ethereum/go-ethereum/log` to StatusNode

Closes #819

### CODE REVIEW

**Comment by adambabik** [comment]
I think we need to solve it differently. We should remove setting log file and log level from the config because the config is passed after the app is started (but before node is started, still there may be some activity before that). Also, it's pretty strange that log configuration is part of node configuration.

Other option is to always log to `stderr` and only set log level via env or something. Forwarding `stderr` would be Objective-C/Java responsibility.

If we need to keep this on Go side, we can provide a binding to configure logging.

**Comment by gravityblast** [comment]
>We should remove setting log file and log level from the config because the config is passed after the app is started (but before node is started, still there may be some activity before that). Also, it's pretty strange that log configuration is part of node configuration.

@adambabik yes I don't think that is the definitive right place but I wanted to have a WIP PR to try the build since the android build is failing in local. We already fixed it in the past with #751 but only for the `statusd` command. That was related to the PR where we switched to #717 .

**Comment by gravityblast** [comment]
>the config is passed after the app is started (but before node is started, still there may be some activity before that)

We can also move this part to our `lib` package if it makes sense, and the native part can still log before calling `StartNode`. Or would you prefer to change it completely?

**Comment by adambabik** [comment]
@pilu if we currently cannot collect logs because of this bug, I would take a shortcut and implement a fix ASAP and create a follow-up issue to do it right.

**Comment by gravityblast** [comment]
I moved the initialisation to the `lib` pkg used by react. It's still not the final way to do it but as you @adambabik said we can create a new Issue for this. Also because the file is created from Java with an hardcoded file name:

https://github.com/status-im/status-react/blob/develop/modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java#L118

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Review by mandrigin — APPROVED** [review]
LGTM

**Review by adambabik — APPROVED** [review]
LGTM We can build on top of this and separate logging configuration from node configuration in the next PRs.

**Pull request merged**
