### PR TITLE
Anon Metrics Broadcast

### PR DESCRIPTION
**Pull request by Samyoul**
## Functionality to:

- Broadcast anon metrics from a status mobile app node
- Receive and decrypt metrics data on a dedicated anon metrics node

## Deactivated by default

By default the functionality to both broadcast and receive metrics is deactivated.

I've added a test that will fail if the broadcast functionality is activated `MessengerAnonMetricsSuite/TestActivationIsOff`

### Client

To activate this functionality EITHER

Add the following string to the `anonMetricsClientConfig`:

```json
{
  "ClientConfig": {
    "Active": "yes i am wanting the activation of the anon metrics client, please thank you lots thank you"
  }
}
```

OR

Remove the all checks in client functionality that evaluate:

```go
const ActiveClientPhrase
```

### Server

To activate this functionality EITHER

Add the following string to the `anonMetricsServerConfig`:

```json
{
  "ServerConfig": {
    "Active": "I was thinking that it would be a pretty nice idea if the server functionality was working now, I express gratitude in the anticipation"
  }
}
```

OR

Remove the all checks in server functionality that evaluate:

```go
const ActiveServerPhrase
```

## Also see

https://notes.status.im/metrics

### CODE REVIEW

**Comment by Samyoul** [comment]
Getting a persistent fail in Jenkins that does not happen locally:

```text
[2021-06-11T14:09:55.914Z] === RUN   TestMessengerAnonMetricsSuite
[2021-06-11T14:09:55.914Z] === RUN   TestMessengerAnonMetricsSuite/TestReceiveAnonMetric
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.250Z	DEBUG	waku/waku.go:121	starting waku with config	{"config": {"MaxMessageSize":1048576,"MinimumAcceptedPoW":0,"BloomFilterMode":false,"LightClient":false,"FullNode":false,"RestrictLightClientsConn":true,"EnableConfirmations":false,"SoftBlacklistedPeerIDs":null}}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.266Z	INFO	protocol/messenger.go:197	opening a database	{"dbPath": ":memory:"}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.310Z	INFO	protocol/messenger.go:212	failed to find Whisper service; trying Waku
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.311Z	DEBUG	node/node.go:185	Epoch processing	{"mvds": {"node": "045754f7", "epoch": 0}}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.481Z	INFO	protocol/messenger.go:434	starting messenger	{"identity": "0x045754f7074fe5fc77f8e2b7bf37dff0991454e76fe7143322bbd38e9e72c438f522077cf688e56e6836c36bc5450a62d45dfd97abd7b8e646bb9802a760e559e0"}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:184	Main Start() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:133	startMainLoop() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:195	stopMainLoop() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	INFO	publisher/publisher.go:47	starting publisher	{"Publisher": {"site": "Start"}}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	protocol/messenger.go:882	watching connection changes
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	protocol/messenger.go:903	watching expired emojis
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	protocol/messenger.go:923	watching identity image changes
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1419	running resending loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	INFO	protocol/messenger.go:434	starting messenger	{"identity": "0x045754f7074fe5fc77f8e2b7bf37dff0991454e76fe7143322bbd38e9e72c438f522077cf688e56e6836c36bc5450a62d45dfd97abd7b8e646bb9802a760e559e0"}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:138	startMainLoop() anonymous go routine triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:117	mainLoop() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:56	sendUnprocessedMetrics() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1478	running registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1419	running resending loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:687	subscribing for message events
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1478	running registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1430	no retriable notifications, quitting
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1485	nothing to do, quitting registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1485	nothing to do, quitting registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	pushnotificationclient/client.go:1430	no retriable notifications, quitting
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:184	Main Start() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:133	startMainLoop() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:195	stopMainLoop() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:198	mainLoopQuit not set, attempting to close
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.482Z	DEBUG	anonmetrics/client.go:66	unprocessed metrics from db	{"uam": {}}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	anonmetrics/client.go:123	mainLoop() wait interval set	{"waitFor": "1s"}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	INFO	publisher/publisher.go:47	starting publisher	{"Publisher": {"site": "Start"}}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	protocol/messenger.go:882	watching connection changes
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	protocol/messenger.go:903	watching expired emojis
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	protocol/messenger.go:923	watching identity image changes
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:687	subscribing for message events
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1478	running registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1485	nothing to do, quitting registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1419	running resending loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1430	no retriable notifications, quitting
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	anonmetrics/client.go:138	startMainLoop() anonymous go routine triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	anonmetrics/client.go:117	mainLoop() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	anonmetrics/client.go:56	sendUnprocessedMetrics() triggered
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	anonmetrics/client.go:66	unprocessed metrics from db	{"uam": {}}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	anonmetrics/client.go:123	mainLoop() wait interval set	{"waitFor": "2s"}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1478	running registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1485	nothing to do, quitting registration loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1419	running resending loop
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.483Z	DEBUG	pushnotificationclient/client.go:1430	no retriable notifications, quitting
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.495Z	INFO	protocol/messenger.go:197	opening a database	{"dbPath": ":memory:"}
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.530Z	INFO	protocol/messenger.go:212	failed to find Whisper service; trying Waku
[2021-06-11T14:09:55.914Z] 2021-06-11T14:09:25.530Z	DEBUG	node/node.go:185	Epoch processing	{"mvds": {"node": "040f9595", "epoch": 0}}
[2021-06-11T14:09:55.914Z] --- FAIL: TestMessengerAnonMetricsSuite (0.29s)
[2021-06-11T14:09:55.914Z]     --- FAIL: TestMessengerAnonMetricsSuite/TestReceiveAnonMetric (0.29s)
[2021-06-11T14:09:55.914Z]         anon_metrics_test.go:86: 
[2021-06-11T14:09:55.914Z]             	Error Trace:	anon_metrics_test.go:86
[2021-06-11T14:09:55.914Z]             	            				suite.go:123
[2021-06-11T14:09:55.914Z]             	Error:      	Received unexpected error:
[2021-06-11T14:09:55.914Z]             	            	file does not exist
[2021-06-11T14:09:55.914Z]             	            	failed to create anonmetrics.Server
[2021-06-11T14:09:55.914Z]             	            	github.com/status-im/status-go/protocol.NewMessenger
[2021-06-11T14:09:55.914Z]             	            		/home/jenkins/workspace/status-go_prs_tests_PR-2198/src/github.com/status-im/status-go/protocol/messenger.go:263
[2021-06-11T14:09:55.914Z]             	            	github.com/status-im/status-go/protocol.newMessengerWithKey
[2021-06-11T14:09:55.914Z]             	            		/home/jenkins/workspace/status-go_prs_tests_PR-2198/src/github.com/status-im/status-go/protocol/messenger_test.go:139
[2021-06-11T14:09:55.914Z]             	            	github.com/status-im/status-go/protocol.(*MessengerAnonMetricsSuite).SetupTest
[2021-06-11T14:09:55.914Z]             	            		/home/jenkins/workspace/status-go_prs_tests_PR-2198/src/github.com/status-im/status-go/protocol/anon_metrics_test.go:85
[2021-06-11T14:09:55.914Z]             	            	github.com/stretchr/testify/suite.Run.func2
[2021-06-11T14:09:55.914Z]             	            		/home/jenkins/workspace/status-go_prs_tests_PR-2198/pkg/mod/github.com/stretchr/testify@v1.5.1/suite/suite.go:123
[2021-06-11T14:09:55.914Z]             	            	testing.tRunner
[2021-06-11T14:09:55.914Z]             	            		/usr/local/go/src/testing/testing.go:909
[2021-06-11T14:09:55.914Z]             	            	runtime.goexit
[2021-06-11T14:09:55.914Z]             	            		/usr/local/go/src/runtime/asm_amd64.s:1357
[2021-06-11T14:09:55.914Z]             	Test:       	TestMessengerAnonMetricsSuite/TestReceiveAnonMetric
[2021-06-11T14:09:55.914Z] FAIL
[2021-06-11T14:09:55.914Z] FAIL	github.com/status-im/status-go/protocol	0.336s
```

The message of note is `file does not exist` which is probably the default OS `internal/oserror/errors.go` error. My presumption is that this error applies to the migration file, but I don't know why

**Review by cammellos — APPROVED** [review]
Looks good, I like the comments, really nice documentation!

**Review by shivekkhurana — APPROVED** [review]
Superb. The tests are well done. 

Just one Q: Are we absolutely sure that the metrics will never be broadcasted? Because this is a dormant feature.

**Comment by Samyoul** [comment]
@shivekkhurana This test https://github.com/status-im/status-go/pull/2198/files#diff-b6974d94cf4dad26a116d0c8ffb77c01852738f1dafdcee5cee074f9583c0f1eR155-R209 will fail if someone tried to activate the feature.

The test specifically checks to see if the broadcast client is present in the case the wrong or no activation phrase is given.

If someone builds the app and enters the activation phrase into the config file, they can activate the functionality, but by default the phrase is not given and it is ridiculously long and improbable to guess or enter by accident.

**Pull request merged**
