### PR TITLE
Fetch details of user when building a contact

### PR DESCRIPTION
**Pull request by alwx**
Required for https://github.com/status-im/status-mobile/pull/15070
Adds fetching of details when building a contact.

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Review by cammellos — COMMENTED** [review]
It would be good to test this behavior, we could create two contacts, have one publish something on their contact code, and then retrieve this info using build contact from the other side.

Would you mind adding a test for this please?

Thanks!

**Comment by alwx** [comment]
@cammellos I'm struggling a bit with that — the problem is it requires a working mailserver and it means a bunch of changes to the test suite — I tried to make it quick but spend most of the day doing that, actually. How about I create a follow up story for the test? Just because the clojure code needs to be merged asap.

**Comment by cammellos** [comment]
> @cammellos I'm struggling a bit with that — the problem is it requires a working mailserver and it means a bunch of changes to the test suite — I tried to make it quick but spend most of the day doing that, actually. How about I create a follow up story for the test? Just because the clojure code needs to be merged asap.

Of course, no problems, if you want we can have a quick session and we can look at it, I think we might be able to get away without using a mailserver, but we can have a deeper look at it together if you'd like

**Comment by alwx** [comment]
@cammellos sure, we can do that. Just ping me in Status when you're ready — I will push the skeleton of the test I wrote yesterday in the meantime.

**Comment by cammellos** [comment]
> @cammellos sure, we can do that. Just ping me in Status when you're ready — I will push the skeleton of the test I wrote yesterday in the meantime.

cool, in the meantime, feel free to merge when tested/ready, thank you!

**Comment by alwx** [comment]
https://github.com/status-im/status-go/issues/3278

**Pull request merged**
