### PR TITLE
fix(wallet)_: use consistent invalid timestamp constant 

### PR DESCRIPTION
**Pull request by belalshehab**
- Replaced `unknownUpdateTimestamp` with `InvalidTimestamp` to maintain consistency.

### CODE REVIEW

**Review by IvanBelyakoff — APPROVED** [review]
@belalshehab good job, just you ll need to fix the tests in ownership_db_test.go.

**Comment by belalshehab** [comment]
@J-Son89 
Hi Jamie, please confirm if you use maxInt64 as an invalid timestamp.
because in the ownership_db.go we sometimes return invalid timestamp as maxInt64 and sometimes we return -1 and I was determined to get rid of maxInt64 value.

**Review by saledjenic — APPROVED** [review]

**Comment by ulisesmac** [comment]
> @J-Son89 Hi Jamie, please confirm if you use maxInt64 as an invalid timestamp. because in the ownership_db.go we sometimes return invalid timestamp as maxInt64 and sometimes we return -1 and I was determined to get rid of maxInt64 value.

Hi @belalshehab 
Seems we don't specifically use `maxInt64` itself, but in our side it is an invalid value when creating a timestamp.

Could you please share some endpoints currently returning `maxInt64` and some returning `-1` as invalid timestamps? I'd like to confirm what happens in those cases for us.

**Comment by belalshehab** [comment]
> > @J-Son89 Hi Jamie, please confirm if you use maxInt64 as an invalid timestamp. because in the ownership_db.go we sometimes return invalid timestamp as maxInt64 and sometimes we return -1 and I was determined to get rid of maxInt64 value.
> 
> Hi @belalshehab Seems we don't specifically use `maxInt64` itself, but in our side it is an invalid value when creating a timestamp.
> 
> Could you please share some endpoints currently returning `maxInt64` and some returning `-1` as invalid timestamps? I'd like to confirm what happens in those cases for us.

Hi @ulisesmac 
right now the only change is in services/wallet/collectibles/ownership_db.go ->  GetOwnership
it will now return -1 as invalid timestamp instead of maxInt64
so if you don't use this function specifically all should be good

**Comment by ulisesmac** [comment]
> > > @J-Son89 Hi Jamie, please confirm if you use maxInt64 as an invalid timestamp. because in the ownership_db.go we sometimes return invalid timestamp as maxInt64 and sometimes we return -1 and I was determined to get rid of maxInt64 value.
> > 
> > 
> > Hi @belalshehab Seems we don't specifically use `maxInt64` itself, but in our side it is an invalid value when creating a timestamp.
> > Could you please share some endpoints currently returning `maxInt64` and some returning `-1` as invalid timestamps? I'd like to confirm what happens in those cases for us.
> 
> Hi @ulisesmac right now the only change is in services/wallet/collectibles/ownership_db.go -> GetOwnership it will now return -1 as invalid timestamp instead of maxInt64 so if you don't use this function specifically all should be good

OK then it seems everything is ok for us! 
Thank you!

**Pull request merged**
