### PR TITLE
chore: upgrade go-waku to v0.5

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by jakubgs** [comment]
Started a manual build to get a Docker image I could test: https://ci.infra.status.im/job/status-go/job/manual/2924/

**Review by jrainville — APPROVED** [review]
Gotta love vendor upgrades in go `+84,297 −65,136`

**Comment by jakubgs** [comment]
If you rebase this I should be able to build a Docker image and testit.

**Comment by richard-ramos** [comment]
@jakubgs PR's been rebased! hopefully it will fix the leak.

I'll still merge it once it's green since it contains some fixes I need for desktop. Tomorrow I'll hunt for memory leaks and send a new PR if the leak wasnt fixed with this new libp2p version i'm using now

**Comment by jakubgs** [comment]
I have deployed the `statusteam/status-go:v0.132.0-c6f6ca` image [I built](https://ci.infra.status.im/job/status-go/job/platforms/job/docker/2523/) to one of the `notify.prod` hosts but it fails to start:
```
INFO [02-23|09:00:00.840] Status backend initialized               backend=geth version=0.132.0 commit=c6f6ca99a IpfsGatewayURL=https://ipfs.status.im/
INFO [02-23|09:00:00.840] status-go version details                package=status-go/api.GethStatusBackend version=0.132.0 commit=c6f6ca99a
WARN [02-23|09:00:00.874] GetDBFilename was passed a nil pointer sql.DB 
ERROR[02-23|09:00:00.875] Node start failed                        package=status-go/cmd/statusd error="node crashed on start: <nil>"
```
@richard-ramos any ideas?

**Comment by richard-ramos** [comment]
hm. It seems to be complaining about the accounts database being nil based on this err: `GetDBFilename was passed a nil pointer sql.DB`. Here's where the error is being triggered: https://github.com/status-im/status-go/blob/develop/multiaccounts/settings/database.go#L35-L38

If I wanted to reproduce this error on my machine, what should I do?

**Comment by jakubgs** [comment]
Try the `statusteam/status-go:v0.132.0-c6f6ca` docker image? I built from `develop` in Jenkins:
https://ci.infra.status.im/job/status-go/job/platforms/job/docker/2523/

You could check out that commit and build `statusd` locally.

**Comment by richard-ramos** [comment]
Hm... i tried the latest commit from this PR and it seems to be fine (even tho that DB error is shown, but looks like it's a WARN and it is also not something introduced in this PR):
```
richard@laptop:~/status/status-go$ ./build/bin/statusd 
INFO [02-23|11:54:41.539] Status backend initialized               backend=geth version=0.132.0 commit=df5b976a8 IpfsGatewayURL=https://ipfs.status.im/
INFO [02-23|11:54:41.539] status-go version details                package=status-go/api.GethStatusBackend version=0.132.0 commit=df5b976a8
WARN [02-23|11:54:41.550] GetDBFilename was passed a nil pointer sql.DB 
WARN [02-23|11:54:41.550] GetDBFilename was passed a nil pointer sql.DB 
INFO [02-23|11:54:41.550] Starting peer-to-peer node               instance=Statusd/v0.132.0/linux-amd64/go1.19.6
INFO [02-23|11:54:41.566] Successful start 
INFO [02-23|11:54:41.566] Handlers registered                      package=status-go/api.GethStatusBackend
INFO [02-23|11:54:41.567] UDP listener up                          net=enode://e6f8fcd765301b0f018fdaeef7f6986262fb0bb8efdbdd931105a95a3efbc49dfeb40a79e4a8fdaab57136af44af166e94536a00c00a9f40b2723467fad18395@[::]:30303
INFO [02-23|11:54:41.567] New local node record                    seq=1,677,167,626,667 id=249850bfac87cb15 ip=127.0.0.1 udp=0 tcp=30303
INFO [02-23|11:54:41.567] Started P2P networking                   self="enode://e6f8fcd765301b0f018fdaeef7f6986262fb0bb8efdbdd931105a95a3efbc49dfeb40a79e4a8fdaab57136af44af166e94536a00c00a9f40b2723467fad18395@127.0.0.1:30303?discport=0"
INFO [02-23|11:54:41.767] handling peer                            peerID=0xe5bd0829cf2736754bfa8cd28fe86eca419259b17ae3dae29be21c9a395f634e
INFO [02-23|11:54:41.871] handling peer                            peerID=0x829fad8fd411906d3bb0447e4c228b902d824c3c7685d4032aeecfb4e09f835d
INFO [02-23|11:54:42.160] handling peer                            peerID=0x88343a58775bcff87ad9044590b4212fd99e33ed4e89240ccafc2e9899227c44
ERROR[02-23|11:54:43.569] failed to compute offset                 error="RPC failed: kiss of death received: RATE; read udp 192.168.0.109:38404->190.122.100.61:123: i/o timeout; read udp 192.168.0.109:60903->190.122.100.61:123: i/o timeout."
INFO [02-23|11:54:44.636] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
```


I'm gonna try with the commit of the logs you shared: `c6f6ca99a`

**Comment by richard-ramos** [comment]
Seems to be fine too:
```
richard@laptop:~/status/status-go$ ./build/bin/statusd 
INFO [02-23|11:58:55.019] Status backend initialized               backend=geth version=0.132.0 commit=c6f6ca99a IpfsGatewayURL=https://ipfs.status.im/
INFO [02-23|11:58:55.019] status-go version details                package=status-go/api.GethStatusBackend version=0.132.0 commit=c6f6ca99a
WARN [02-23|11:58:55.033] GetDBFilename was passed a nil pointer sql.DB 
WARN [02-23|11:58:55.034] GetDBFilename was passed a nil pointer sql.DB 
INFO [02-23|11:58:55.034] Starting peer-to-peer node               instance=Statusd/v0.132.0/linux-amd64/go1.19.6
INFO [02-23|11:58:55.044] New local node record                    seq=1,677,167,626,668 id=249850bfac87cb15 ip=127.0.0.1 udp=0 tcp=30303
INFO [02-23|11:58:55.044] Started P2P networking                   self="enode://e6f8fcd765301b0f018fdaeef7f6986262fb0bb8efdbdd931105a95a3efbc49dfeb40a79e4a8fdaab57136af44af166e94536a00c00a9f40b2723467fad18395@127.0.0.1:30303?discport=0"
INFO [02-23|11:58:55.045] Successful start 
INFO [02-23|11:58:55.045] Handlers registered                      package=status-go/api.GethStatusBackend
INFO [02-23|11:58:55.050] UDP listener up                          net=enode://e6f8fcd765301b0f018fdaeef7f6986262fb0bb8efdbdd931105a95a3efbc49dfeb40a79e4a8fdaab57136af44af166e94536a00c00a9f40b2723467fad18395@[::]:30303
INFO [02-23|11:58:55.124] Difference with ntp servers              offset=8.705323ms
INFO [02-23|11:58:55.231] handling peer                            peerID=0xe5bd0829cf2736754bfa8cd28fe86eca419259b17ae3dae29be21c9a395f634e
INFO [02-23|11:58:55.381] handling peer                            peerID=0x829fad8fd411906d3bb0447e4c228b902d824c3c7685d4032aeecfb4e09f835d
INFO [02-23|11:58:55.633] handling peer                            peerID=0x88343a58775bcff87ad9044590b4212fd99e33ed4e89240ccafc2e9899227c44
INFO [02-23|11:58:58.292] Mapped network port                      proto=tcp extport=30303 intport=30303 interface="UPNP IGDv1-IP1"
```

**Comment by jakubgs** [comment]
Here's the reproduction:
```
 > cat config.json 
{
  "WakuConfig": {
    "Enabled": false
  },
  "WakuV2Config": {
    "Enabled": true
  }
}

 > d run --rm -it -v $PWD/config.json:/config.json statusteam/status-go:v0.132.0-c6f6ca -c /config.json
INFO [02-23|17:29:45.523] Status backend initialized               backend=geth version=0.132.0 commit=c6f6ca99a IpfsGatewayURL=https://ipfs.status.im/
INFO [02-23|17:29:45.523] status-go version details                package=status-go/api.GethStatusBackend version=0.132.0 commit=c6f6ca99a
WARN [02-23|17:29:45.586] GetDBFilename was passed a nil pointer sql.DB 
ERROR[02-23|17:29:45.586] Node start failed                        package=status-go/cmd/statusd error="node crashed on start: <nil>"
```

**Comment by richard-ramos** [comment]
@jakubgs https://github.com/status-im/status-go/pull/3229 fixes the issue you ran into

**Comment by jakubgs** [comment]
Nice, thanks for the fix!

**Pull request merged**
