### PR TITLE
chore: bump go-libp2p, go-waku and golang

### PR DESCRIPTION
**Pull request by siddarthkay**
This PR attempts to bump
- libp2p
- gowaku
- golang

uses the same code which was reverted in : https://github.com/status-im/status-go/pull/4522

status-mobile PR to test : https://github.com/status-im/status-mobile/pull/18564

status: ready

### CODE REVIEW

**Comment by siddarthkay** [comment]
@richard-ramos @cammellos : issue is fixed on status-mobile side, I'll run E2E and have QA look at this next week and then after that lets merge this.

**Comment by ghost** [comment]
`vendor/github.com/pion/webrtc/v3/yarn.lock` changed. Pinging @corpetty

**Review by richard-ramos — APPROVED** [review]

**Comment by richard-ramos** [comment]
Can we merge this?

**Comment by siddarthkay** [comment]
Hi @richard-ramos : it was discussed recently that this and its corresponding status-mobile PR can be merged in a week after the current release testing is done 
cc @status-im/mobile-qa

**Comment by pavloburykh** [comment]
> Can we merge this?

Hi @richard-ramos! How critical it would be to merge this PR after cutting release go branch? We would prefer not to risk before release. I guess we will need another week before release branch is cut.

**Comment by richard-ramos** [comment]
It's not critical. Let's wait after release.  We can still use the older go version with no problems.

**Comment by ghost** [comment]
`vendor/github.com/pion/webrtc/v3/yarn.lock` changed. Pinging @corpetty

**Comment by siddarthkay** [comment]
closing in favour of : https://github.com/status-im/status-go/pull/5027

**Pull request closed without merging**
