### PR TITLE
fix(connector)_: connector response structure to valid json

### PR DESCRIPTION
**Pull request by MishkaRogachev**
For https://github.com/status-im/status-desktop/issues/15879

Important changes:
- [x] Fix `eth_accounts`
- [x] Fix `eth_requestAccounts`
- [x] Fix `wallet_requestPermissions`

### CODE REVIEW

**Comment by MishkaRogachev** [comment]
Tested RPCs:

>> eth_requestAccounts / eth_accounts
```
{
    "jsonrpc": "2.0",
    "id": 37,
    "result": [
        "0x5a734304c8a3ff009b13cda1a0c4869e3ebf4737"
    ]
}
```

>> eth_chainId / wallet_switchEthereumChain
```
{
    "jsonrpc": "2.0",
    "id": 37,
    "result": "0x1"
}
```

>> wallet_requestPermissions
```
{
    "jsonrpc": "2.0",
    "id": 37,
    "result": {
        "parentCapability": "chainId",
        "date": "1722350583154"
    }
}
```

>>  eth_sendTransaction
```
{
    "jsonrpc": "2.0",
    "id": 37,
    "result": "0xb081da2bd565c9f5caf6d36fbcbace2e0f416d7d7a643b0093cad6f8aa6db0ec"
}
```

**Review by jrainville — APPROVED** [review]

**Review by kounkou — APPROVED** [review]
LGTM, thanks

**Review by felicio — CHANGES_REQUESTED** [review]
```
{
    "jsonrpc": "2.0",
    "id": 37,
    "method": "connector_callRPC",
    "params": [
        "{\"method\": \"eth_blockNumber\", \"params\": [], \"url\": \"https://app.uniswap.org\", \"name\": \"https://app.uniswap.org\", \"iconUrl\": \"https://app.uniswap.org\" }"
    ]
}
```

returns

```
{
    "jsonrpc": "2.0",
    "id": 37,
    "result": "{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":\"0x1379a07\"}"
}
```

that's both

- still escaped
- and not just the `result` but nested in another `jsonrpc`

and would guess it's the case for any of these https://github.com/status-im/status-go/blob/5d309e2c64f59eb46fbfd40fd38f5f1102f6ff8f/rpc/route.go#L71C1-L72C1 methods

**Comment by felicio** [comment]
> Tested RPCs:
> 
> > > eth_requestAccounts / eth_accounts
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "id": 37,
>     "result": [
>         "0x5a734304c8a3ff009b13cda1a0c4869e3ebf4737"
>     ]
> }
> ```
> 
>  > > eth_chainId / wallet_switchEthereumChain
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "id": 37,
>     "result": "0x1"
> }
> ```
> 
>  > > wallet_requestPermissions
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "id": 37,
>     "result": {
>         "parentCapability": "chainId",
>         "date": "1722350583154"
>     }
> }
> ```
> 
>  > > eth_sendTransaction
> 
> ```
> {
>     "jsonrpc": "2.0",
>     "id": 37,
>     "result": "0xb081da2bd565c9f5caf6d36fbcbace2e0f416d7d7a643b0093cad6f8aa6db0ec"
> }
> ```

This checks out, good job 👍.

**Comment by felicio** [comment]
Just to have the reported issues complete here

```
{
    "jsonrpc": "2.0",
    "id": 37,
    "method": "connector_callRPC",
    "params": [
        "{\"method\":\"personal_sign\",\"params\":[\"0x446563656e7472616c616e64204c6f67696e0a457068656d6572616c20616464726573733a203078333332303835373339364265313338613842426561426139316364344131396631423132464235320a45787069726174696f6e3a20323032342d30382d33305431363a33343a30312e3935395a\",\"0xafbaba8b62423e8e9f2a7df07c2d7fd73205fca4\"],\"url\":\"https://decentraland.org\",\"name\":\"https://decentraland.org\"}"
    ]
}
```
```
{
    "jsonrpc": "2.0",
    "id": 37,
    "error": {
        "code": -32603,
        "message": "method handler crashed"
    }
}
```

**Review by felicio — APPROVED** [review]

**Pull request merged**
