### PR TITLE
Adding Transactions messages to the localnotifications

### LINKED ISSUE #2141: Notifications are not dispatched for RequestTransaction/SendTransaction
See https://github.com/status-im/status-go/pull/2130#issuecomment-770709112

> There is at least one issues: notifications are not dispatch for RequestTransaction/SendTransaction and related messages.

### PR DESCRIPTION
**Pull request by Samyoul**
## What's Changed?

I've added functionality that creates `MessageNotificationBody`s for validated transaction messages and adds the notifications to the `localnotification` queue to be sent to the OS.

Also I've moved the original functionality that created `MessageNotificationBody`s from new chat messages to the bottom of the `handleRetrievedMessages` function so that we only notify about new messages and are not dependant on specific handlers for adding `MessageNotificationBody` to `Response.Notifications` list.

Closes #2141

## Note

**DO NOT MERGE** until https://github.com/status-im/status-go/pull/2130 has been merged.

### CODE REVIEW

**Comment by rasom** [comment]
@Samyoul notifications are not passed to the client side for some reason

**Comment by rasom** [comment]
```
t=2021-02-06T19:09:52+0000 lvl=info msg="Pushing a new push notification" info="&{ID:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Platform:0 Body:{Message:clock:1612638592299 timestamp:1612638592299 text:\"Why?\" chat_id:\"0x047e9d4c3f3bba429d8d5bb3dd2b24eb6e9bb3d2bd21642577b9b8dbc97e1ffeb3614f2bb213a4465582f76c5f91f9cc778dc46e0ac22f75287fe302c225b86b97\" message_type:ONE_TO_ONE content_type:TEXT_PLAIN  Contact:<nil> Chat:<nil>} BodyType:message Category:newMessage Deeplink: Image: IsScheduled:false ScheduledTime:}"
```
both `Contact` and `Chat` look a bit too nil

**Comment by Samyoul** [comment]
So Transaction notifications are created but the client doesn't receive them? Is that right?

Also the `Contact` and `Chat` nils are not entirely unexpected, I'm pretty sure I've got a fix for the `Contact` nil, I'll check again on what can be done about the `Chat` nil.

**Comment by rasom** [comment]
```
t=2021-02-08T18:56:00+0000 lvl=info msg="Pushing a new push notification" info="&{ID:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] Platform:0 Body:{Message:clock:1612810560932 timestamp:1612810560932 text:\"Wut?\" chat_id:\"0x04958351af704af9e6a426224ce83b3de3d055e8bb566b226614096626edcbfba896aec864e0fa0544a07c0b16fa7503edb30ae3da71191cfe8142af54e13bfc23\" message_type:ONE_TO_ONE content_type:TEXT_PLAIN  Contact:0x400048cf70 Chat:0x4001834000} BodyType:message Category:newMessage Deeplink: Image: IsScheduled:false ScheduledTime:}"
```
@Samyoul That's how PN for 1-1 chat's message looks in `develop`, both `Contact` and `Chat` are not `nil`.

**Comment by rasom** [comment]
> So Transaction notifications are created but the client doesn't receive them? Is that right?

sorry, that was a false statement. They are received by the client, but as `Contact` and `Chat` are `nil` they are not handled as expected.

**Comment by rasom** [comment]
@Samyoul I had to rewrite client side a bit but it works now, thanks

**Comment by Samyoul** [comment]
@rasom it looks like your last force push removed a previous commit that should have given you at least an attached `Contact`. I've added a little bit of additional code to the `Contact` side and you should always get a `Contact` now.

I'll have fix for `Chat` in a little bit.

**Comment by Samyoul** [comment]
Ok, you should always have `Chat` now.

**Review by rasom — APPROVED** [review]

**Comment by Samyoul** [comment]
@rasom Why are you force pushing this PR? You keep removing commits.

**Comment by rasom** [comment]
@Samyoul I'm rebasing it onto develop, that will happen before merging anyway. Is there any problem with that?

**Pull request merged**
