### PR TITLE
[DEBUG] Increase verbosity for api and node e2e tests

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by dshulyak** [comment]
I am almost sure that ethnode.Start is executed right after ethnode.Stop but unfortunately, i can't reproduce it with at least with some logs.

Also, it seems probable, that Travis sent interrupt signal:

https://github.com/status-im/status-go/blob/develop/geth/node/utils.go#L39-L40

**Comment by divan** [comment]
@dshulyak mind providing more information on why this is needed? Are you debugging a specific problem that can be only reproduced in CI?
We removed verbosity from CI tests some time ago, because logs are too verbose, to the extent they do not make any sense for non-failing tests.

**Comment by dshulyak** [comment]
@divan yes, https://github.com/status-im/status-go/issues/539 

quite a few builds are failing with the same problem

**Comment by divan** [comment]
Ok, I see. I commented on that issue, but will post here as well — it looks like a dup of https://github.com/status-im/status-go/issues/429

Is it possible to hunt this panic in a separate branch? Travis will build any branch. Also, @dshulyak, as you're incredibly productive (for the first days of January at least :) ), would you want to join our Slack chat to speed up things?

**Comment by dshulyak** [comment]
@divan it would be easier of course, but I didn't know that everyone has a permission to push a branch to status-im. sure, i can join

**Comment by dshulyak** [comment]
@divan the only problem is that it is not really a public chat ;)

**Comment by divan** [comment]
@dshulyak yeah, you're right. We also have Riot (https://chat.status.im) but it's not very heavily used. Anyway, let's postpone this task a bit — it requires an access to Ci (in order to reproduce) or, at least, faster communication channel.

**Comment by divan** [comment]
@dshulyak seems there a pending fix available: https://github.com/status-im/go-ethereum/pull/38

**Comment by dshulyak** [comment]
@divan thanks, i noticed

**Pull request closed without merging**
