### PR TITLE
fix(events): fix malformed events missing request

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/14106

I'm currently running this fix. I'm waiting to see if the crash happens again.

I'm not sure why the event might have been malformed in the first place, but protecting against it is important.

### CODE REVIEW

**Comment by jrainville** [comment]
I let it run for a few hours and it didn't crash. It's ready for review

**Review by osmaczko — COMMENTED** [review]
Invalid events should be filtered before processing, here is the check:
https://github.com/status-im/status-go/blob/296b44f9ab5a0e1d987dfb07bbb213145951f639/protocol/communities/community_event.go#L182-L185

Could you please double-check if you see these warnings you've just added in the logs? If that is indeed the case, it means the filtering is not working properly and that's serious, because it will most likely crash in different place as well.

**Comment by osmaczko** [comment]
> Could you please double-check if you see these warnings you've just added in the logs? If that is indeed the case, it means the filtering is not working properly and that's serious, because it will most likely crash in different place as well.

We don't validate events that are read from the database because they were validated before being saved. What I suspect happened is that the database event writing or reading is buggy.

**Comment by osmaczko** [comment]
> What I suspect happened is that the database event writing or reading is buggy.

Since you have reproducible environment, could you please confirm that with:
```diff
diff --git a/protocol/communities/community_events_processing.go b/protocol/communities/community_events_processing.go
index d37a50043..cd81d1938 100644
--- a/protocol/communities/community_events_processing.go
+++ b/protocol/communities/community_events_processing.go
@@ -106,7 +106,21 @@ func (e *eventsProcessor) filterEvents() {
 
 // Merge message's events with community's events.
 func (e *eventsProcessor) mergeEvents() {
+    validateEvent := func(event *CommunityEvent) error {
+        signer, err := event.RecoverSigner()
+        if err != nil {
+            return err
+        }
+        return e.community.validateEvent(event, signer)
+    }
+
     if e.community.config.EventsData != nil {
+        for _, event := range e.community.config.EventsData.Events {
+            err := validateEvent(&event)
+            if err != nil {
+                e.logger.Error("invalid event read from database", zap.String("EventTypeID", event.EventTypeID()), zap.Error(err))
+            }
+        }
         e.eventsToApply = append(e.eventsToApply, e.community.config.EventsData.Events...)
     }
 }


```

**Comment by mprakhov** [comment]
Agree, this is not a root cause fix and the same behavior can happen to other events

Look at the invalid event 2. It has the correct payload and signature (the same as event 1) so there could be an issue with deserialization or reading from DB

From the Jo log in the ticket description:

```
[
    {
        CommunityEventClock: 1710425207
        Type: COMMUNITY_REQUEST_TO_JOIN_ACCEPT
        CommunityConfig: <nil>
        TokenPermission: <nil>
        CategoryData: <nil>
        ChannelData: <nil>
        MemberToAction: 0x04beeae3dc636e7632665387ccb444dd90745840d5e112d1f0b4a4370e719054764efcbe7092b38e20bc74e84c151af790ee93cec37b81b7ad8cc6a9e497cfdebf
        RequestToJoin:
            clock:1710425198 
            ens_name:"rich-owner" 
            community_id:"\x033\xea\x96Q\x10wG0\x02\x9d綤,\x90\xa1\x91~\xc9\xdbA\xed\xfe\x02]\x82\xd3ݦ+\xf0\xab"
        TokenMetadata: <nil>
        Payload: [8 247 136 204 175 6 16 12 82 190 1 10 132 1 48 120 48 52 98 101 101 97 101 51 100 99 54 51 54 101 55 54 51 50 54 54 53 51 56 55 99 99 98 52 52 52 100 100 57 48 55 52 53 56 52 48 100 53 101 49 49 50 100 49 102 48 98 52 97 52 51 55 48 101 55 49 57 48 53 52 55 54 52 101 102 99 98 101 55 48 57 50 98 51 56 101 50 48 98 99 55 52 101 56 52 99 49 53 49 97 102 55 57 48 101 101 57 51 99 101 99 51 55 98 56 49 98 55 97 100 56 99 99 54 97 57 101 52 57 55 99 102 100 101 98 102 18 53 8 238 136 204 175 6 18 10 114 105 99 104 45 111 119 110 101 114 34 33 3 51 234 150 81 16 119 71 48 2 157 231 182 164 44 144 161 145 126 201 219 65 237 254 2 93 130 211 221 166 43 240 171]
        Signature: [178 157 14 205 238 32 138 112 88 66 26 197 29 109 70 50 216 214 235 106 50 221 100 167 14 230 88 117 142 153 182 73 100 254 42 249 51 195 38 251 13 134 117 186 235 248 253 13 169 154 157 216 190 178 216 189 147 72 153 113 169 237 244 140 0]
    }
    {
        CommunityEventClock: 1710425207
        Type: COMMUNITY_REQUEST_TO_JOIN_ACCEPT
        CommunityConfig: <nil>
        TokenPermission: <nil>
        CategoryData: <nil>
        ChannelData: <nil>
        MemberToAction:  
        RequestToJoin: <nil>
        TokenMetadata: <nil>
        Payload: [8 247 136 204 175 6 16 12 82 190 1 10 132 1 48 120 48 52 98 101 101 97 101 51 100 99 54 51 54 101 55 54 51 50 54 54 53 51 56 55 99 99 98 52 52 52 100 100 57 48 55 52 53 56 52 48 100 53 101 49 49 50 100 49 102 48 98 52 97 52 51 55 48 101 55 49 57 48 53 52 55 54 52 101 102 99 98 101 55 48 57 50 98 51 56 101 50 48 98 99 55 52 101 56 52 99 49 53 49 97 102 55 57 48 101 101 57 51 99 101 99 51 55 98 56 49 98 55 97 100 56 99 99 54 97 57 101 52 57 55 99 102 100 101 98 102 18 53 8 238 136 204 175 6 18 10 114 105 99 104 45 111 119 110 101 114 34 33 3 51 234 150 81 16 119 71 48 2 157 231 182 164 44 144 161 145 126 201 219 65 237 254 2 93 130 211 221 166 43 240 171]
        Signature: [178 157 14 205 238 32 138 112 88 66 26 197 29 109 70 50 216 214 235 106 50 221 100 167 14 230 88 117 142 153 182 73 100 254 42 249 51 195 38 251 13 134 117 186 235 248 253 13 169 154 157 216 190 178 216 189 147 72 153 113 169 237 244 140 0]
    }
    {
        CommunityEventClock: 1710425240
        Type: COMMUNITY_EDIT
        CommunityConfig:
            identity:{display_name:"hello"  description:"fewff"  color:"#88B0FF"} 
            permissions:{access:AUTO_ACCEPT} 
            admin_settings:{} 
            intro_message:"dqwd" 
            outro_message:"wqdqw"
        TokenPermission: <nil>
        CategoryData: <nil>
        ChannelData: <nil>
        MemberToAction: <nil>
        RequestToJoin: <nil>
        Payload: [8 152 137 204 175 6 16 1 26 44 10 23 34 5 104 101 108 108 111 42 5 102 101 119 102 102 50 7 35 56 56 66 48 70 70 18 2 24 1 26 0 34 4 100 113 119 100 42 5 119 113 100 113 119]
        Signature: [221 184 133 36 214 184 1 49 59 40 209 37 241 73 150 239 60 190 127 65 165 202 111 190 200 32 199 20 152 150 29 127 109 84 228 245 6 182 89 98 104 65 170 187 55 165 21 168 82 204 214 25 122 158 172 92 146 81 119 69 83 206 50 137 1]
    }
]

```

**Comment by osmaczko** [comment]
I've just read the issue comments and I've noticed something strange:
```
    {
        CommunityEventClock: 1710425207
        Type: COMMUNITY_REQUEST_TO_JOIN_ACCEPT
        CommunityConfig: <nil>
        TokenPermission: <nil>
        CategoryData: <nil>
        ChannelData: <nil>
        MemberToAction: 0x04beeae3dc636e7632665387ccb444dd90745840d5e112d1f0b4a4370e719054764efcbe7092b38e20bc74e84c151af790ee93cec37b81b7ad8cc6a9e497cfdebf
        RequestToJoin:
            clock:1710425198 
            ens_name:"rich-owner" 
            community_id:"\x033\xea\x96Q\x10wG0\x02\x9d綤,\x90\xa1\x91~\xc9\xdbA\xed\xfe\x02]\x82\xd3ݦ+\xf0\xab"
        TokenMetadata: <nil>
        Payload: [8 247 136 204 175 6 16 12 82 190 1 10 132 1 48 120 48 52 98 101 101 97 101 51 100 99 54 51 54 101 55 54 51 50 54 54 53 51 56 55 99 99 98 52 52 52 100 100 57 48 55 52 53 56 52 48 100 53 101 49 49 50 100 49 102 48 98 52 97 52 51 55 48 101 55 49 57 48 53 52 55 54 52 101 102 99 98 101 55 48 57 50 98 51 56 101 50 48 98 99 55 52 101 56 52 99 49 53 49 97 102 55 57 48 101 101 57 51 99 101 99 51 55 98 56 49 98 55 97 100 56 99 99 54 97 57 101 52 57 55 99 102 100 101 98 102 18 53 8 238 136 204 175 6 18 10 114 105 99 104 45 111 119 110 101 114 34 33 3 51 234 150 81 16 119 71 48 2 157 231 182 164 44 144 161 145 126 201 219 65 237 254 2 93 130 211 221 166 43 240 171]
        Signature: [178 157 14 205 238 32 138 112 88 66 26 197 29 109 70 50 216 214 235 106 50 221 100 167 14 230 88 117 142 153 182 73 100 254 42 249 51 195 38 251 13 134 117 186 235 248 253 13 169 154 157 216 190 178 216 189 147 72 153 113 169 237 244 140 0]
    }
    {
        CommunityEventClock: 1710425207
        Type: COMMUNITY_REQUEST_TO_JOIN_ACCEPT
        CommunityConfig: <nil>
        TokenPermission: <nil>
        CategoryData: <nil>
        ChannelData: <nil>
        MemberToAction:  
        RequestToJoin: <nil>
        TokenMetadata: <nil>
        Payload: [8 247 136 204 175 6 16 12 82 190 1 10 132 1 48 120 48 52 98 101 101 97 101 51 100 99 54 51 54 101 55 54 51 50 54 54 53 51 56 55 99 99 98 52 52 52 100 100 57 48 55 52 53 56 52 48 100 53 101 49 49 50 100 49 102 48 98 52 97 52 51 55 48 101 55 49 57 48 53 52 55 54 52 101 102 99 98 101 55 48 57 50 98 51 56 101 50 48 98 99 55 52 101 56 52 99 49 53 49 97 102 55 57 48 101 101 57 51 99 101 99 51 55 98 56 49 98 55 97 100 56 99 99 54 97 57 101 52 57 55 99 102 100 101 98 102 18 53 8 238 136 204 175 6 18 10 114 105 99 104 45 111 119 110 101 114 34 33 3 51 234 150 81 16 119 71 48 2 157 231 182 164 44 144 161 145 126 201 219 65 237 254 2 93 130 211 221 166 43 240 171]
        Signature: [178 157 14 205 238 32 138 112 88 66 26 197 29 109 70 50 216 214 235 106 50 221 100 167 14 230 88 117 142 153 182 73 100 254 42 249 51 195 38 251 13 134 117 186 235 248 253 13 169 154 157 216 190 178 216 189 147 72 153 113 169 237 244 140 0]
    }
```

These are two same events, one valid, the other one not.

**Review by MishkaRogachev — APPROVED** [review]

**Comment by jrainville** [comment]
@osmaczko @mprakhov you guys are right, this wasn't the root cause.

And yeah, the validate function should have caught it, but it didn't... because it was never called :joy: 

I don't know why, it was called for `HandleCommunityEventsMessageRejected`, but not for `HandleCommunityEventsMessage`, so I added it. See the last commit.

I think this can be considered like a real fix for the issue. Not sure why it received the event twice in the first place, but it could be network shenanigans or a corrupted community, since it came from a test community.

**Comment by jrainville** [comment]
@osmaczko I found that you're the one that removed it here: https://github.com/status-im/status-go/commit/e2cab1a8aed130932c3796f85c7e255c3acaf5da#diff-0c22647108517d38489ae5faa65a914ade3be02ea7a7e37355a82739da9aeb69L1842

Was there a reason that I'm not aware of or it was just an oopsie?

Disclaimer: I can't repro the issue. I guess I no longer receive the signal :shrug:

**Comment by osmaczko** [comment]
> I think this can be considered like a real fix for the issue. Not sure why it received the event twice in the first place, but it could be network shenanigans or a corrupted community, since it came from a test community.

It isn't a real fix :sweat: The validation of message events is happening right now as well, see below.

> @osmaczko I found that you're the one that removed it here: [e2cab1a#diff-0c22647108517d38489ae5faa65a914ade3be02ea7a7e37355a82739da9aeb69L1842](https://github.com/status-im/status-go/commit/e2cab1a8aed130932c3796f85c7e255c3acaf5da#diff-0c22647108517d38489ae5faa65a914ade3be02ea7a7e37355a82739da9aeb69L1842)
> 
> Was there a reason that I'm not aware of or it was just an oopsie?
> 
> Disclaimer: I can't repro the issue. I guess I no longer receive the signal 🤷

I refactored events, the filtering and validation happens here:
https://github.com/status-im/status-go/blob/aa13fbdab20828a179bc4b369701677df2f469a8/protocol/communities/manager.go#L2008
->
https://github.com/status-im/status-go/blob/e878f89b65b1fab080be38047a58dc3332add605/protocol/communities/community_events_processing.go#L46

**Comment by jrainville** [comment]
Closing as it doesn't actually fix the issue.

**Pull request closed without merging**
