### PR TITLE
Fix generating mocks for Jenkins

### PR DESCRIPTION
**Pull request by adambabik**
Switch `mockgen` to use reflect mode as source mode does not support vendored packages.

---

I will investigate and create a bug ticket in https://github.com/golang/mock but it looks like source mode can't import vendored packages. 

Error in Jenkins:
```
mockgen -source=geth/mailservice/mailservice.go -destination=geth/mailservice/mailservice_mock.go -package=mailservice
2018/04/04 10:46:48 failed to import package by path github.com/ethereum/go-ethereum/node: cannot find package "github.com/ethereum/go-ethereum/node" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/node (from $GOROOT)
	/home/jenkins/workspace/status-go/status-go-manual/src/github.com/ethereum/go-ethereum/node (from $GOPATH) - fallback to import path suffix
2018/04/04 10:46:48 failed to import package by path github.com/ethereum/go-ethereum/p2p: cannot find package "github.com/ethereum/go-ethereum/p2p" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/p2p (from $GOROOT)
	/home/jenkins/workspace/status-go/status-go-manual/src/github.com/ethereum/go-ethereum/p2p (from $GOPATH) - fallback to import path suffix
2018/04/04 10:46:48 imported package collision: "" imported twice
Makefile:117: recipe for target 'mock' failed
```

`/home/jenkins/workspace/status-go/status-go-manual/src/github.com/ethereum/go-ethereum` did not exist because `github.com/ethereum/go-ethereum` is in `vendor/`.

I successfully built this branch in Jenkins.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/golang/mock">golang/mock</a></strong></div><div>GoMock is a mocking framework for the Go programming language.</div></blockquote>

### CODE REVIEW

**Review by themue — APPROVED** [review]
LGTM, even if I'm still no fan of generated mocks. ;)

**Review by mandrigin — APPROVED** [review]

**Comment by divan** [comment]
@adambabik why does it work locally and doesn't work in Jenkins? Maybe it's related to the package resolution code, that depends on GOPATH being set correctly? The path you showed in the description (/home/jenkins/workspace/status-go/status-go-manual) suggests that it's not a proper GOPATH used for build.

**Comment by adambabik** [comment]
@divan It works because you probably have `github.com/ethereum/go-ethereum` in `GOPATH`. In the Jenkins build, `github.com/ethereum/go-ethereum` is present only in the `vendor/` and `gomock` does not check that location. It's a proper path and it's set explicitly to the current build workspace.

**Comment by divan** [comment]
@adambabik I just tried both options (without go-ethereum package in GOPATH and with GOPATH set to a different path) and can't reproduce this.
Okay, anyway, if the reflect mode doesn't have any obvious pitfalls, let's use it.

**Comment by adambabik** [comment]
I still can reproduce it. Also, in the log, it says that `GOPATH` is examined but not `vendor/` dir. 

I haven't noticed and pitfalls and tests pass. Reflect mode is preferred actually.

**Pull request merged**
