### PR TITLE
[#ISSUE-937] : Move mail server implementation to status-go repo

### LINKED ISSUE #936: Move mail server implementation to status-go repo
# Problem

The current implementation of the mail server is in go-ethereum repo which does not give us any control over it (except for making patches).

# Implementation

Move the implementation of the mail server to status-go repo.

# Acceptance Criteria

1. Mail server implementation belongs to status-go repo,
2. `statusd` uses it to register the mail server capability.

# Notes

We will introduce more changes to the mail server implementation, mainly security improvements.

### PR DESCRIPTION
**Pull request by adriacidre**
Move `github.com/ethereum/go-ethereum/whisper/mailserver` implementation to status-go repo

In order to introduce future changes on mailserver, mainly security improvements, we're porting the geth mailserver to status-go codebase

Important changes:
- [x] Moved geth mailserver to status-go mailserver
- [x] Removed `github.com/ethereum/go-ethereum/whisper/mailserver` dependency
- [x] Fixed minor lint problems

Closes #936

### CODE REVIEW

**Review by dshulyak — CHANGES_REQUESTED** [review]
i think it should be copied with tests (can be found in original go-ethereum)

**Comment by adriacidre** [comment]
Strange, tests weren't checked out on my vendor folder. 

They've been recovered now from v1.8.5 used on develop.

BTW, code on go-ethereum master branch looks different from the one used here and on status-go/develop, it's ok to use current `v1.8.5` or we should try an upgrade?

**Comment by adambabik** [comment]
We do not have `develop` in `status-im/go-ethereum` anymore. There is only master branch which should be updated to 1.8.5. 

The MailServer implementation code should be taken from go-ethereum 1.8.5 release.

**Comment by adambabik** [comment]
Oh, actually @divan's change was merged recently. We can take https://github.com/ethereum/go-ethereum/blob/master/whisper/mailserver/mailserver.go (`d2fe83d`) then.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/ethereum/go-ethereum">ethereum/go-ethereum</a></strong></div><div>go-ethereum - Official Go implementation of the Ethereum protocol</div></blockquote>

**Comment by adriacidre** [comment]
yup, i'll get those changes here too :)

**Comment by adriacidre** [comment]
okay, all done :)

**Review by dshulyak — APPROVED** [review]

**Review by adambabik — APPROVED** [review]

**Comment by adambabik** [comment]
CI is failing. Maybe you need to remove `mailserver` package from `vendor/`?

**Comment by adriacidre** [comment]
Cheers updating dependencies fixed all CI issues :)

**Pull request merged**
