### PR TITLE
feat: introduce new `joined` property in `Chat` struct

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
This property is useful for clients to know when a channel or chat
was joined so they can use that to calculate the order of channels
and chats shown in applications.

Changes include a new `joined` property on the `Chat` struct,
as well as adjustments in the persistence layer to retreive and
update chat data in the database.

In addition there's a migration script that alters the existing
chat table to introduce a new column for the `joined` field.

A short summary which serves as a squashed-commit message.

A description to understand introduced changes without reading the code.

Important changes:
- [x] Something worth noting for reviewers.

Closes #

### CODE REVIEW

**Comment by 0x-r4bbit** [comment]
>  Have you updated the documentation, if impacted (e.g. docs.status.im)?

To be fair, that link gives a 404

**Review by Samyoul — COMMENTED** [review]
Hey @PascalPrecht thanks for the PR.

Where the time for the `Joined` field is set? At the moment this implementation seems to only ever save a `0` value.

**Comment by 0x-r4bbit** [comment]
Because "joining a chat" is essentially "saveChat" with certain parameters, it's the client's job to send a `joined` value along with it. So in other words, in Status Desktop for example, this is happening in our `join()` API: https://github.com/status-im/status-desktop/blob/d4bf29085c7aafbc0aaf72b6b6b748ce010451c5/src/status/chat.nim#L100-L101

**Comment by Samyoul** [comment]
Ah, I see.

**Review by Samyoul — APPROVED** [review]

**Review by cammellos — CHANGES_REQUESTED** [review]
I think with `joined` you need to `Scan` a `NullInt`, as it will be `null` for existing databases (setting `DEFAULT` to `0` will only work on new rows).
So it will probably throw an error on existing databases post-migration.

You can either use `sql.NullInt` or add a statement to the migration `UPDATE chats SET joined = 0` so that all the existing chats have a value, in that case the code does not have to be changed.

Could you also rebase to the latest develop? (make sure that your migration is the latest, otherwise it might be skipped), and bum the VERSION please?

Thanks!

**Comment by 0x-r4bbit** [comment]
@cammellos I've updated the commit. re: the `VERSION`: Since what I did is rather a feature, I've incremented the `minor` version. Let me know if you aren't following SemVer and prefer a patch udpate.

**Review by cammellos — APPROVED** [review]

**Comment by 0x-r4bbit** [comment]
Failing tests seem to be unrelated to this commit

**Comment by cammellos** [comment]
some tests are flaky, you can re run them frim Jenkins, i am afk, but
@samyoul can assist

**Comment by 0x-r4bbit** [comment]
Re-ran the tests on jenkins, still failing due to missing test file for `shhClient`
Also, looks like I need to rebase this one once more

**Comment by cammellos** [comment]
ok, I will rebase it and merge it once ready

**Comment by cammellos** [comment]
@PascalPrecht I have rebased it on feat/add-joined-prop-to-chat-2 if you want to copy over the branch (I can't push on this one as it's on your repo)

**Comment by 0x-r4bbit** [comment]
@cammellos Done!

But it **seems** your branch needs rebase as well. Will do it now.. :D

**Pull request merged**
