### PR TITLE
fix_:skip run TestLoginAndMigrationsStillWorkWithExistingMobileUser

### PR DESCRIPTION
**Pull request by qfrank**
The failed test(TestLoginAndMigrationsStillWorkWithExistingMobileUser) seems can be reproduced easily on CI, however, not easy to reproduce with locally run for 1000 times. Let's skip it for now to avoid blocking other PRs and restore it once it's fixed. I doubt it's because Login twice catched weird errors.

relate CI error log: [log link](https://ci.status.im/job/status-go/job/prs/job/tests/job/PR-5520/7/artifact/api/test_1.log)

```
âœ–  api (2m0.557s)

=== Failed
=== FAIL: api  (0.00s)
panic: test timed out after 2m0s
running tests:
	TestOldMobileUserUpgradingFromV1ToV2 (7s)
	TestOldMobileUserUpgradingFromV1ToV2/TestLoginAndMigrationsStillWorkWithExistingMobileUser (4s)
```

### CODE REVIEW

**Review by mprakhov — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by osmaczko — COMMENTED** [review]
This test seems to be failing due to a timeout of the whole package (API) rather than an issue with the test itself.

```
panic: test timed out after 2m0s
```

I suggest increasing the timeout first. Additionally, it is worth investigating why the current timeout is no longer sufficient. Perhaps more tests were added, and we were already close to the limit.

**Comment by qfrank** [comment]
> This test seems to be failing due to a timeout of the whole package (API) rather than an issue with the test itself.
> 
> ```
> panic: test timed out after 2m0s
> ```
> 
> I suggest increasing the timeout first. Additionally, it is worth investigating why the current timeout is no longer sufficient. Perhaps more tests were added, and we were already close to the limit.

```
TestParseAppType: 0.00s
TestBackendStartNodeConcurrently: 2.21s
TestBackendRestartNodeConcurrently: 8.45s
TestBackendGettersConcurrently: 2.21s
TestBackendConnectionChangesConcurrently: 0.00s
TestBackendConnectionChangesToOffline: 0.00s
TestBackendCallRPCConcurrently: 2.22s
TestAppStateChange: 0.00s
TestBlockedRPCMethods: 2.21s
TestCallRPCWithStoppedNode: 0.00s
TestStartStopMultipleTimes: 4.28s
TestHashTypedData: 2.23s
TestBackendGetVerifiedAccount: 2.44s
TestRuntimeLogLevelIsNotWrittenToDatabase: 4.28s
TestLoginWithKey: 4.29s
TestLoginAccount: 5.85s
TestVerifyDatabasePassword: 2.19s
TestDeleteMultiaccount: 0.35s
TestConvertAccount: 6.21s
TestLoginAndMigrationsStillWorkWithExistingDesktopUser: 4.40s
TestChangeDatabasePassword: 0.65s
TestCreateWallet: 8.59s
TestSetFleet: 8.97s
TestWalletConfigOnLoginAccount: 5.93s
TestTestnetEnabledSettingOnCreateAccount: 7.59s
TestRestoreAccountAndLogin: 1.94s
TestCreateAccountPathsValidation: 0.00s
TestRestoreKeycardAccountAndLogin: 0.53s
TestCreateAccountAndLogin: 6.09s
TestBuildDefaultNetworks: 0.00s
TestBuildDefaultNetworksGanache: 0.00s
TestOverrideApiConfig: 0.00s
TestOverrideApiConfigTest: 0.00s
TestMessengerRawMessageResendTestSuite: 11.25s
TestOldMobileUserUpgradingFromV1ToV2: 6.77s
TestHashMessage: 2.23s
TestSerialisePublicKey: 0.00s
TestDeserialisePublicKey: 0.00s
TestSerializeLegacyKey: 0.00s
```

made a local test on package `API`, so now I guess `TestMessengerRawMessageResendTestSuite` is the cause, it might take longer, maybe first let's increasing the timeout to `3m` , WDYT ? @osmaczko

**Comment by osmaczko** [comment]
Thanks for investigation.

> maybe first let's increasing the timeout to `3m`

Sounds good to me :+1:

**Comment by qfrank** [comment]
created another [PR](https://github.com/status-im/status-go/pull/5553) to increase the timeout of unit test

**Pull request closed without merging**
