### PR TITLE
chore_: take fixes from go-waku

### PR DESCRIPTION
**Pull request by chaitanyaprem**
Take in fixes from go-waku for various issues noticed.

1. https://github.com/waku-org/go-waku/pull/1224
2. https://github.com/waku-org/go-waku/pull/1221
3. https://github.com/waku-org/go-waku/pull/1217

item 3 has already been dogfooded by me and had not noticed any side-effects. 
item-1 will be dogfooded using status mobile. 

@richard-ramos is item 2 dogfooded already? If not, we can create a PR using desktop to dogfood?

Closes #https://github.com/status-im/status-mobile/issues/21120

### CODE REVIEW

**Comment by richard-ramos** [comment]
It's not dogfooded yet!

**Comment by chaitanyaprem** [comment]
> It's not dogfooded yet!

let's create a desktop PR and dogfood it, so that this status-go PR can be merged.

**Comment by chaitanyaprem** [comment]
not sure why codecoverage is showing as reduced eventhough i have not touched the files in which it shows as drop in code coverage?
cc @igor-sirotin @osmaczko

**Comment by igor-sirotin** [comment]
> not sure why codecoverage is showing as reduced

@chaitanyaprem looks ok to me, don't bother about it.

1. `codeclimate/total-coverage` is always ±0.2%, because of the integration nature of the tests.
    But it's not a required check to merge, so far just informational.
    image

2. `codeclimate/diff-coverage` is quite stable, so it's required. But it's 100% here, which makes sense 🙂 
    image

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem looks ok to me, don't bother about it.

ok, thanks!

**Review by plopezlpz — APPROVED** [review]

**Comment by chaitanyaprem** [comment]
Closing this PR as the underlying changes got merged as part of https://github.com/status-im/status-go/pull/5909

**Pull request closed without merging**
