### PR TITLE
chore_: upgrade go to 1.21

### PR DESCRIPTION
**Pull request by siddarthkay**
Upgrade go to 1.21

- [x] Pending verification with status-mobile PR https://github.com/status-im/status-mobile/pull/20157

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Review by yakimant — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]
:rocket:

**Review by igor-sirotin — APPROVED** [review]
🎉 Thank you!

**Comment by richard-ramos** [comment]
Looking fwd for this PR to get merged so I can try upgrade go-waku to 1.21 too

**Comment by igor-sirotin** [comment]
Do we want to test this with Desktop as well?

**Comment by siddarthkay** [comment]
> we want to test this with Desktop as well?

yes ideally this upgrade should be tested with Desktop as well.
I will wait for someone from Desktop to confirm

**Comment by igor-sirotin** [comment]
> yes ideally this upgrade should be tested with Desktop as well. I will wait for someone from Desktop to confirm

Well it doesn't work 😄 

```shell
➜  status-desktop git:(master) ✗ make -j10 status-go
Building: status-go
ln: /Users/igorsirotin/Repositories/Status/status-desktop/vendor/status-go//.git/hooks: Not a directory
go: errors parsing go.mod:
/Users/igorsirotin/Repositories/Status/status-desktop/vendor/status-go/go.mod:5: unknown directive: toolchain
make[1]: *** [statusgo-shared-library] Error 1
make: *** [vendor/status-go/build/bin/libstatus.dylib] Error 2
```

**Comment by siddarthkay** [comment]
@igor-sirotin : Looking here it seems that the `go` version in case of `status-desktop` is not pinned to a specific version like we have in status-mobile.

https://github.com/status-im/status-desktop/blob/9523e6b7641a576db8648814a5a1cf8120564517/Makefile#L430-L434

pls correct me if I'm wrong @yakimant 

The toolchain directive was introduced in `go` version `1.21` so this error would make me think that your environment has a lower version of `go`.
I'll also try to reproduce this locally. Thank you for testing this PR with `status-desktop`.

**Comment by siddarthkay** [comment]
@igor-sirotin 
I was able to reproduce this error with `go 1.20`

Screenshot 2024-05-28 at 12 54 53 PM

And this is fixed when i switch locally to `go 1.21`

Screenshot 2024-05-28 at 12 55 53 PM

**Comment by igor-sirotin** [comment]
> I was able to reproduce this error with `go 1.20`

@siddarthkay but shouldn't nix override the go version used to build status-go? 🤔

**Comment by siddarthkay** [comment]
status-go is built with go 1.21, its the status-desktop environment that does not have go 1.21 and hence the issue.
I see 2 problems : 
1) nix shell is avoided here -> https://github.com/status-im/status-desktop/blob/9523e6b7641a576db8648814a5a1cf8120564517/Makefile#L433
2) even in nix shell go 1.19 is pulled in -> https://github.com/status-im/status-desktop/blob/9523e6b7641a576db8648814a5a1cf8120564517/shell.nix#L23

**Comment by anastasiyaig** [comment]
I've created a draft PR on desktop https://github.com/status-im/status-desktop/pull/14940 to see if it builds (and if yes, to launch autotests). Perhaps it is useless (reading comments from Igor) but lets see

Well it does not work
```

[2024-05-28T08:36:42.943Z] + make status-go

[2024-05-28T08:36:43.383Z] Building: status-go

[2024-05-28T08:36:43.383Z] ln: /Users/jenkins/workspace/s_macos_aarch64_package_PR-14940/vendor/status-go//.git/hooks: Not a directory

[2024-05-28T08:36:43.383Z] go: errors parsing go.mod:

[2024-05-28T08:36:43.383Z] /Users/jenkins/workspace/s_macos_aarch64_package_PR-14940/vendor/status-go/go.mod:5: unknown directive: toolchain

[2024-05-28T08:36:43.383Z] make[1]: *** [statusgo-shared-library] Error 1

[2024-05-28T08:36:43.383Z] make: *** [vendor/status-go/build/bin/libstatus.dylib] Error 2

script returned exit code 2
```

**Comment by igor-sirotin** [comment]
> 1. nix shell is avoided here -> https://github.com/status-im/status-desktop/blob/9523e6b7641a576db8648814a5a1cf8120564517/Makefile#L433

Indeed: https://github.com/status-im/status-desktop/pull/14407
Should we keep maintaining go version manually? Or is there any solution upcoming? 🤔 
cc @jakubgs 

> 2. even in nix shell go 1.19 is pulled in -> https://github.com/status-im/status-desktop/blob/9523e6b7641a576db8648814a5a1cf8120564517/shell.nix#L23

I think nobody is using nix for desktop builds 😄 
Should we?

**Comment by anastasiyaig** [comment]
@igor-sirotin we are planning to use Nix for building linux soon, there is a plan

**Review by apentori — APPROVED** [review]

**Comment by jakubgs** [comment]
@igor-sirotin a proper solution would involve building both `status-go` and `status-desktop` using Nix flakes, where `status-go` is one of the `inputs` to the `status-desktop` flake. That would be kosher. But we have some work before that could happen.

**Comment by siddarthkay** [comment]
@anastasiyaig : I have `tested-ok` from @status-im/mobile-qa for this. I think test results were okay in status-desktop as well..
I'm looking for confirmation from your end regarding status-desktop compatibility before I merge this PR.

**Comment by anastasiyaig** [comment]
i was waiting for green mac os build (commented in corresponding desktop pr):) 
yes, we can merge if all is good with it now, last time i checked M1 mac build was not successful @siddarthkay

**Comment by siddarthkay** [comment]
Thanks for reminding @anastasiyaig! I'll take a look at why Jenkins couldn't find any ARM macs with go 1.21 to test my PR

**Comment by siddarthkay** [comment]
@anastasiyaig 
Screenshot 2024-05-30 at 1 42 52 PM

**Comment by anastasiyaig** [comment]
amazing @siddarthkay ! please proceed with merging

**Pull request merged**
