### PR TITLE
chore_: remove endpoint InitLogging

### PR DESCRIPTION
**Pull request by qfrank**
Because mobile [PR](https://github.com/status-im/status-mobile/pull/21677) and status-go [PR](https://github.com/status-im/status-go/pull/6117) have been merged, `InitLogging` should has no usage now, could you help check if desktop used it? @igor-sirotin

### CODE REVIEW

**Review by osmaczko — APPROVED** [review]
:broom: :ok_hand:

Technically, it is a breaking change and should be marked as such I believe.

**Comment by qfrank** [comment]
> Technically, it is a breaking change and should be marked as such I believe.

If the desktop and mobile are no longer using this endpoint, it shouldn't be considered a breaking change, right? @osmaczko

**Comment by osmaczko** [comment]
> > Technically, it is a breaking change and should be marked as such I believe.
> 
> If the desktop and mobile are no longer using this endpoint, it shouldn't be considered a breaking change, right? @osmaczko

Not sure. From API point of view, removal is a breaking change. We shouldn't assume desktop and mobile already removed the endpoint usage. Moreover, theoretically, there might be more clients.

**Review by igor-sirotin — APPROVED** [review]
Thanks @qfrank!
I confirm `InitLogging` is not used in desktop.

> Technically, it is a breaking change and should be marked as such I believe.

@osmaczko fair point, and I'm not sure as well. 
I think it makes no sense to mark as breaking in this case.

**Pull request merged**
