### PR TITLE
Orphaned generated code

### LINKED ISSUE #3677: Orphaned Encryption Protobuf
This file [protocol/encryption/github.com/protocol/encryption/protocol_message.pb.go](https://github.com/status-im/status-go/blob/b8b402da8d5ee94ab1019e034156b425bd6b0f78/protocol/encryption/github.com/protocol/encryption/protocol_message.pb.go) appears to be orphaned, probably due to an old bug we had with `protoc` a while back.

Just check this code is actually orphaned and then delete it and all of its directories.

### PR DESCRIPTION
**Pull request by Azanul**
Closes #3677

### CODE REVIEW

**Review by igor-sirotin — APPROVED** [review]

**Comment by igor-sirotin** [comment]
@Azanul thank you for your contribution and congrats on your first PR.
Sorry for the long review 😄 

Please rebase to the latest `develop` branch to make all CI checks pass, and I'll merge it in.

**Comment by Azanul** [comment]
@igor-sirotin I think the branch is up to date

**Comment by igor-sirotin** [comment]
> @igor-sirotin I think the branch is up to date

Your fork is 1282 commits behind latest `develop` in status-im/status-go.
image

Because of this (I think) CI checks are not running, there're something outdated.

**Comment by igor-sirotin** [comment]
@Azanul thanks for updating the fork, I can run all the checks now.
There will be an issue though.

1. We require commit messages to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), but with `_` for non-breaking changes. 
    So in your case it should be something like 
    ```
    fix_: Orphaned generated code
    ```

2. We use git [rebase](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) strategy over merge strategy.
    So having a merge-commit cc3f6464382c066a408714c3d324c3d2a99e47e5 won't work.
    GitHub might be smart enough to just drop it when merging the PR, but we still require Conventional Commits (look clause 1).

Until this is fixed, CI checks won't pass and, unfortunately, I'll not be able to merge 🙁 

-----

I suggest you to hard-reset your fork on top of latest develop and cherry-pick 07acd6718655992ea804ba0748c7439331fb1392 on top, while changing the commit message to `fix_: Orphaned generated code`.
OR use [interactive rebase](https://www.gitkraken.com/learn/git/problems/git-interactive-rebase#git-interactive-rebase-in-the-command-line) git feature, drop merge commit and rename your commit.

Sorry for such difficulties. But we do this do automatically calculate version/changes based on commit messages.

**Comment by igor-sirotin** [comment]
@jakubgs how do we work with forks? For such PR, should I start each check manually on Jenkins?
I started `tests` manually, but I expected it to happen automatically 🤔

**Comment by Azanul** [comment]
@igor-sirotin Check it out. I rebased, soft reset and re-commit with updated message

**Comment by igor-sirotin** [comment]
> @igor-sirotin Check it out. I rebased, soft reset and re-commit with updated message

Thank you. I'll figure out what's happening with fork jenkins checks and come back to you.

**Comment by jakubgs** [comment]
Sorry, our permissions model for Jenkins CI only allows jobs to be started for contributors. I've added you to the repo:

image

Once you accept the invite and you push again to this branch jobs should start.

**Comment by Azanul** [comment]
> Sorry, our permissions model for Jenkins CI only allows jobs to be started for contributors. I've added you to the repo:
> 
> image
> 
> Once you accept the invite and you push again to this branch jobs should start.

I did accept and pushed but nothing happend

**Comment by igor-sirotin** [comment]
> I did accept and pushed but nothing happend

Don't worry, everything that should have happened, happened 👍 

image

Thank you for your contribution!

**Pull request merged**
