### PR TITLE
feat(waku)_: add lightpush rate-limiter

### PR DESCRIPTION
**Pull request by vpavlin**
This PR enables rate-limiting on Lightpush protocol with 1 msg/s rate.

Important changes:
- [x] Enable 1 msg/s rate limit on Lightpush by default

Related to #4857

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
Wondering if we should follow rate-limits similar to how they are sent in nwaku or use a smaller size than fleet nodes.
@jm-clius @richard-ramos any thoughts?

**Comment by vpavlin** [comment]
IIUC this is mainly for the Status Desktop instances - hence the rate limits should be probably smaller than a fleet node - although 1 msg/s might be a bit too low:)

**Comment by jm-clius** [comment]
Actually I can't see rate limits being set anywhere (yet) for nwaku fleets. `--request-rate-limit` is not yet set for any fleet deployment and is in fact not yet part of the role: https://github.com/status-im/infra-role-nim-waku/blob/master/templates/config.toml.j2 (or am I missing something @NagyZoltanPeter?)

In other words, I'm not sure what the intended rate limits for the fleets are. 1 msg/second for Status Desktop nominally sounds reasonable, though this may require real world feedback to confirm. :)

**Comment by NagyZoltanPeter** [comment]
> Actually I can't see rate limits being set anywhere (yet) for nwaku fleets. `--request-rate-limit` is not yet set for any fleet deployment and is in fact not yet part of the role: https://github.com/status-im/infra-role-nim-waku/blob/master/templates/config.toml.j2 (or am I missing something @NagyZoltanPeter?)
> 
> In other words, I'm not sure what the intended rate limits for the fleets are. 1 msg/second for Status Desktop nominally sounds reasonable, though this may require real world feedback to confirm. :)

Yes, it is not applied yet. 
We may need to open discussion on this topic as I'm just finished with the last phase of request rate limitation.
That will apply default per peer request rate for filter service.
lightpush and store and store legacy are default switched off.

There are number of questions how to apply DOS protection properly.
- I think we cannot apply one single rule for lightpush and store. 
   - Do we need separate CLI arguments or defaults?
   - RLN and dos protection are a bit competing feature: for lightpush we may consider different approach for DOS protection. The current solution is flexible on that.
   - What are the acceptable query rates for store service?
   ... probably there come more questions to discuss.

**Review by richard-ramos — APPROVED** [review]
LGTM. We can always change the rate limit values if needed

**Review by chaitanyaprem — APPROVED** [review]
LGTM

**Pull request merged**
