### PR TITLE
fix: proper usage of CreateAccount RootDataDir

### LINKED ISSUE #5186: Cannot login on Windows
# Problem

During login of existing account, or creation o new account or syncing between two apps, Windows desktop client will error out and not login 

image

logs:

```
DEBUG[05-17|21:05:54.175|github.com/status-im/status-go/services/wallet/collectibles/commands.go:340]       end loadOwnedCollectiblesCommand         chain=10 account=0x4d910637189E01cbd5f3BF310f92Ed7993DC707f in=593.4971ms
DEBUG[05-17|21:05:54.185|github.com/status-im/status-go/node/get_status_node.go:510]                        status node stopped                      package=status-go/node.StatusNode
ERROR[05-17|21:05:54.185|github.com/status-im/status-go/mobile/status.go:319]                               loginAccount failed                      error="mkdir D:\\Projects\\status-desktop\\Status\\data\\D:: The filename, directory name, or volume label syntax is incorrect."
``` 

# Notes
It looks like 
vendor\status-go\api\geth_backend.go
```
conf.ShhextConfig.BackupDisabledDataDir = filepath.Join(b.rootDataDir, conf.ShhextConfig.BackupDisabledDataDir)
```
is causing this problem, because in 
vendor\status-go\services\ext\service.go
```
func (s *Service) InitProtocol(nodeName string, identity *ecdsa.PrivateKey, appDb, walletDb *sql.DB, httpServer *server.MediaServer, multiAccountDb *multiaccounts.Database, acc *multiaccounts.Account, accountManager *account.GethManager, rpcClient *rpc.Client, walletService *wallet.Service, communityTokensService *communitytokens.Service, wakuService *wakuv2.Waku, logger *zap.Logger) error {
....
	dataDir := filepath.Clean(s.config.ShhextConfig.BackupDisabledDataDir)

	if err := os.MkdirAll(dataDir, os.ModePerm); err != nil {
		return err
	}

...
```

there dataDir  will contain 'self-duplicated' path (in my case it is  D:\Projects\status-desktop\Status\data\ D:\Projects\status-desktop\Status\data\

Commenting out ```conf.ShhextConfig.BackupDisabledDataDir = filepath.Join(b.rootDataDir, conf.ShhextConfig.BackupDisabledDataDir)
``` locally will make the app to properly login and ```dataDir := filepath.Clean(s.config.ShhextConfig.BackupDisabledDataDir)``` contain proper path

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-go/issues/5186

1. Deprecate `CreateAccount.BackupDisabledDataDir`
2. Add `CreateAccount.RootDataDir` (with fallback to `BackupDisabledDataDir` until both clients update)
3. Set `nodeConfig.ShhextConfig.BackupDisabledDataDir` to `./` by default
4. Check for datadir existence during `loadNodeConfig` and stop on error
5. Completely remove `ShhextConfig.BackupDisabledDataDir`. It was only used once as RootDataDir. Which was wrong and very confusing.

### CODE REVIEW

**Comment by pavloburykh** [comment]
Hey @igor-sirotin! Thanx for the PR. Could you please clarify, does this branch still valid https://github.com/status-im/status-go/pull/5255 or we should continue testing this new branch? Seems both branches a linked to the same issue https://github.com/status-im/status-go/issues/5186

**Comment by igor-sirotin** [comment]
@pavloburykh sorry for confusing. I closed https://github.com/status-im/status-go/pull/5284 now. 
I probably should've just kept the work in that PR, but did want to keep them separate. No idea what for 😄

**Comment by pavloburykh** [comment]
> @pavloburykh sorry for confusing. I closed #5284 now. I probably should've just kept the work in that PR, but did want to keep them separate. No idea what for 😄

no worries, thank you for clarification @igor-sirotin

**Review by Seitseman — APPROVED** [review]
LGTM!

**Review by yqrashawn — APPROVED** [review]

**Comment by pavloburykh** [comment]
@igor-sirotin thanks for the PR, no issues from mobile side. Tested in https://github.com/status-im/status-mobile/pull/20316

What has been tested: 

1. Migration
2. Create/restore/login 
3. local pairing
4. verified this [ISSUE](https://github.com/status-im/status-mobile/pull/20296#issuecomment-2144769202) is fixed on IOS

**Pull request merged**
