### PR TITLE
Build binaries for various platforms in CI

### PR DESCRIPTION
**Pull request by adambabik**
This PR provides a Jenkinsfile and enables automatic builds of status-go binaries for various platforms and deploys them to the artifacts manager.

**TBD: deploy strategy** 
1. Deploy artifacts for every commit for every branch (version like `feature-ci-build-024b3c5`; lots of artifacts, many can be broken),
2. Deploy artifacts just per branch (will overwrite with each commit; version like `feature-ci-build`; changing binary of once released version is confusing),
3. Deploy only after merge to `develop` (version like `0.9.8-024b3c5`).

I recommend the third option for the time being, with an additional Jenkins job which one can use to manually generate binaries for an arbitrary branch if needed.

@tiabc @rasom which strategy is the most useful for you?

**Todo:**
- [ ] ~~is `pom.xml` required? (cc @rasom)~~ (not needed)
- [x] should we enabled iOS builds or Android is enough for now? (cc @rasom)

### CODE REVIEW

**Comment by tiabc** [comment]
I like the second option. It also means that once we have a release (read: a release branch), it'll also be automatically built.
If we reason from usage patterns, the request for status-react to use some specific branch is the most popular, in my opinion so I'd stick to the second option.

**Comment by divan** [comment]
Second makes more sense to me as well.

**Comment by rasom** [comment]
2) and 3)

**Comment by adambabik** [comment]
Thanks for response, I proceed with the solution number 2. The first successful build is `/job/status-go/313`.

It builds Android and iOS simulator binaries in parallel and took 13 minutes.

@rasom is it required to generate `pom.xml` files? I have seen them when creating lib releases manually.

**Comment by rasom** [comment]
Yes `pom.xml` is required for maven as far as i know

**Comment by adambabik** [comment]
After further examination, it turned out that `pom.xml` is not required.

**Pull request merged**
