### PR TITLE
add api to create community for testing

### PR DESCRIPTION
**Pull request by qfrank**
relate mobile [issue](https://github.com/status-im/status-mobile/issues/16362)

### CODE REVIEW

**Review by siddarthkay — APPROVED** [review]
Looks good!

**Comment by osmaczko** [comment]
@qfrank, the inclusion of test-related code in the production environment can lead to scope pollution in the messenger. It's crucial for production code to remain separate from testing to maintain clean and efficient codebases. Please move this to the testing utilities. Additionally, status-go should remain client-agnostic. Introducing mobile-specific files goes against this principle. Let's keep status-go versatile and avoid platform-specific implementations.

**Comment by qfrank** [comment]
> @qfrank, the inclusion of test-related code in the production environment can lead to scope pollution in the messenger. It's crucial for production code to remain separate from testing to maintain clean and efficient codebases. Please move this to the testing utilities. Additionally, status-go should remain client-agnostic. Introducing mobile-specific files goes against this principle. Let's keep status-go versatile and avoid platform-specific implementations.

i see, maybe move it into `status-mobile` would be better. @osmaczko

**Comment by osmaczko** [comment]
> > @qfrank, the inclusion of test-related code in the production environment can lead to scope pollution in the messenger. It's crucial for production code to remain separate from testing to maintain clean and efficient codebases. Please move this to the testing utilities. Additionally, status-go should remain client-agnostic. Introducing mobile-specific files goes against this principle. Let's keep status-go versatile and avoid platform-specific implementations.
> 
> i see, maybe move it into `status-mobile` would be better. @osmaczko

Yes, that makes much more sense to me. Thank you.

**Comment by qfrank** [comment]
> > > @qfrank, the inclusion of test-related code in the production environment can lead to scope pollution in the messenger. It's crucial for production code to remain separate from testing to maintain clean and efficient codebases. Please move this to the testing utilities. Additionally, status-go should remain client-agnostic. Introducing mobile-specific files goes against this principle. Let's keep status-go versatile and avoid platform-specific implementations.
> > 
> > 
> > i see, maybe move it into `status-mobile` would be better. @osmaczko
> 
> Yes, that makes much more sense to me. Thank you.

created a [feature issue](https://github.com/status-im/status-mobile/issues/18715) to track @osmaczko

**Pull request merged**
