### PR TITLE
feat_: connector revoke permissions and accounts

### PR DESCRIPTION
**Pull request by MishkaRogachev**
For https://github.com/status-im/status-desktop/issues/15962

- add `wallet_revokePermissions` rpc endpoint
- add signals for notifying the UI when dApp permission granted or revoked
- add getter api for permitted dApps list

### CODE REVIEW

**Comment by felicio** [comment]
@MishkaRogachev please, request the requiring reviews from repo's maintainers. And once the desktop PR is up, ping me there.

**Comment by felicio** [comment]
> @MishkaRogachev please, request the requiring reviews from repo's maintainers. And once the desktop PR is up, ping me there.

I'll try https://github.com/status-im/status-desktop/pull/15954, since it should include it https://github.com/status-im/status-go/compare/8787da1b899d25a65332b0aee2440b8453062343...1c37e4d2a083dfa989802c1cca02d70f98eb1b5e.

**Comment by felicio** [comment]
> > @MishkaRogachev please, request the requiring reviews from repo's maintainers. And once the desktop PR is up, ping me there.
> 
> I'll try [status-im/status-desktop#15954](https://github.com/status-im/status-desktop/pull/15954), since it should include it [8787da1...1c37e4d](https://github.com/status-im/status-go/compare/8787da1b899d25a65332b0aee2440b8453062343...1c37e4d2a083dfa989802c1cca02d70f98eb1b5e).

I've tested the RPC methods, and functionality-wise it's good to go.

**Review by kounkou — APPROVED** [review]

**Review by jrainville — APPROVED** [review]

**Comment by kounkou** [comment]
merging on behalf of @MishkaRogachev

**Pull request merged**
