### PR TITLE
fix(wallet): activity duplicate in case of non-native transfer - 0.177.x - cherry-pick 

### PR DESCRIPTION
**Pull request by stefandunca**
Cherrypick: https://github.com/status-im/status-go/pull/5017

Also [disabled ENS API](https://github.com/status-im/status-go/pull/5081/commits/9285a730bc8439ab45c513a43171f87d1258245f)

### CODE REVIEW

**Review by Cuteivist — APPROVED** [review]

**Review by dlipicar — APPROVED** [review]

**Review by igor-sirotin — CHANGES_REQUESTED** [review]
we shouldn't comment out code. Just skip the tests.
I also opened a PR: https://github.com/status-im/status-go/pull/5086

**Comment by igor-sirotin** [comment]
@stefandunca my PR is merged now. The tests are back alive. I'll close this PR if you don't mind 🙂

**Comment by igor-sirotin** [comment]
Oh, there was also a cherry-pick, my bad

**Comment by igor-sirotin** [comment]
I've removed the ENS commit from this branch. 
UPD: oh crap, I should've reopened the PR first, before rebasing 🤦 Now I can't reopen the PR. 
Reopened here: https://github.com/status-im/status-go/pull/5091

**Pull request closed without merging**
