### PR TITLE
Temporarily revert "Remove shh and shhext from APIModules and update tests (#993)"

### PR DESCRIPTION
**Pull request by pedropombeiro**
This reverts commit 7581766470ca7ff7a86685268b2d932edea3fcb5.

Context: https://status-im.slack.com/archives/C8QP8S5UH/p1528290805000573

<blockquote><div><strong><a href="https://status-im.slack.com/archives/C8QP8S5UH/p1528290805000573">Slack</a></strong></div></blockquote>

### CODE REVIEW

**Review by adriacidre — APPROVED** [review]

**Review by themue — APPROVED** [review]
Pretty straight.

**Comment by adriacidre** [comment]
Flaky test report:
```
--- FAIL: TestPeerPoolSimulationSuite (20.16s)
    --- PASS: TestPeerPoolSimulationSuite/TestPeerPoolCache (0.08s)
    --- FAIL: TestPeerPoolSimulationSuite/TestSingleTopicDiscoveryWithFailover (20.07s)
	Error Trace:	peerpool_test.go:101
			peerpool_test.go:192
	Error:      	timed out waiting for a peer
	Error Trace:	peerpool_test.go:193
	Error:      	Not equal: 
	            	expected: discover.HexID("64c9c51c51e9ff100a974fe000610ca05a3c06ce6b42156df9b14f74a08d721bea0686dfe40f44ae6b90da8016dcbd2f6ea9ebbdabd03fbb15327d9cfe4b735d")
	            	actual: discover.HexID("00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000")
	            	
	            	Diff:
	            	--- Expected
	            	+++ Actual
	            	@@ -1,2 +1,2 @@
	            	-(discover.NodeID) (len=64) 64c9c51c51e9ff100a974fe000610ca05a3c06ce6b42156df9b14f74a08d721bea0686dfe40f44ae6b90da8016dcbd2f6ea9ebbdabd03fbb15327d9cfe4b735d
	            	+(discover.NodeID) (len=64) 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	            	 
	Error Trace:	peerpool_test.go:112
			peerpool_test.go:195
	Error:      	timed out waiting a pool event
```

**Comment by pedropombeiro** [comment]
Had some more time to test this in depth after the meeting in Zurich and it turns out that this doesn't break things in status-react, it's only the changes there that caused issues (changing from CallRPC to CallPrivateRPC). Closing this unmerged as a result.

**Comment by pedropombeiro** [comment]
That's what you get when you're always context-switching: I later noticed that the local Go build was being deleted by the react Makefile, so my tests were flawed. Tested it again and confirmed that with the #993 PR, you get this in react:

```
06-06 23:51:50.734 27094 27184 E ReactNativeJS: ERROR [status-im.transport.shh:124] - :shh/get-new-sym-key-error Error: The method shh_addSymKey does not exist/is not available
06-06 23:51:50.750 27094 27184 E ReactNativeJS: ERROR [status-im.transport.shh:124] - :shh/get-new-sym-key-error Error: The method shh_addSymKey does not exist/is not available
06-06 23:51:50.755 27094 27184 W ReactNativeJS: WARN [status-im.transport.filters:20] - :add-filter-error {"topics":["0xf8946aac"],"privateKeyID":"0x04325367620ae20dd878dbb39f69f02c567d789dd21af8a88623dc5b529827c2812571c380a2cd8236a2851b8843d6486481166c39debf60a5d30b9099c66213e4","allowP2P":true} Error: The method shh_newMessageFilter does not exist/is not available
06-06 23:51:50.758 27094 27184 E ReactNativeJS: ERROR [status-im.transport.shh:124] - :shh/get-new-sym-key-error Error: The method shh_addSymKey does not exist/is not available
06-06 23:51:50.761 27094 27184 E ReactNativeJS: ERROR [status-im.transport.shh:124] - :shh/get-new-sym-key-error Error: The method shh_addSymKey does not exist/is not available
06-06 23:51:50.765 27094 27184 E ReactNativeJS: ERROR [status-im.transport.shh:124] - :shh/get-new-sym-key-error Error: The method shh_addSymKey does not exist/is not available
06-06 23:51:50.786 27094 27184 E ReactNativeJS: ERROR [status-im.transport.shh:124] - :shh/get-new-sym-key-error Error: The method shh_addSymKey does not exist/is not available
```

By trying to fix it in react by moving to the private RPC endpoint, we break transaction signing, so we need to spend some time to figure out why that happens. In the meantime I'll merge this commit and update react to use latest develop.

**Pull request merged**
