### PR TITLE
Feat/restore connector service

### PR DESCRIPTION
**Pull request by MishkaRogachev**
### Description

Restore https://github.com/status-im/status-go/pull/5375

### Changes: 
- [x] Add nodeconfig field and migration for connector service

This PR is a continuation from [5375](https://github.com/status-im/status-go/pull/5375)

### Tests

To test I had to update some non-committed file to enable the connector service.

🟢 Tested (example for account `eth_accounts` above)
🟠 (In progress) Tried command without required parameters
🔴 Not supported

| Method                               | State | Comments |
|--------------------------------------|-------|----------|
| `eth_requestAccounts`                  | 🔴    | `the method eth_requestAccounts does not exist/is not available` |
| `eth_sendTransaction`|🔴|`method is unsupported by RPC interface`|
| `eth_chainId`|🔴|`the method eth_chainId does not exist/is not available`|
| `eth_protocolVersion`                  | 🟢    |  |
| `eth_accounts` |🟢||
| `eth_syncing`                          | 🟢    |  |
| `eth_coinbase`                         | 🟠    | `The method eth_coinbase does not exist/is not available'. run error was 'etherbase must be explicitly specified` |
| `eth_mining`                           | 🟢    |  |
| `eth_hashrate`                         | 🟢    |  |
| `eth_gasPrice`                         | 🟢    |  |
| `eth_maxPriorityFeePerGas`             | 🟢    |  |
| `eth_feeHistory`                       | 🟢    | |
| `eth_blockNumber`                      | 🟢    |  |
| `eth_getBalance`                       | 🟢     | |
| `eth_getStorageAt`                     | 🟢      |  |
| `eth_getTransactionCount`              | 🟠     | `fallback failed with 'missing value for required argument 0'. run error was 'Relay request failed validation: invalid relay request: invalid eth_getTransactionCount parameters object: empty params array` |
| `eth_getBlockTransactionCountByHash`   | 🟠     | `fallback failed with 'missing value for required argument 1'. run error was 'missing value for required argument 0` |
| `eth_getBlockTransactionCountByNumber` | 🟠     | `fallback failed with 'missing value for required argument 1'. run error was 'missing value for required argument 0` |
| `eth_getUncleCountByBlockHash`         | 🟠     | `fallback failed with 'missing value for required argument 0'. run error was 'missing value for required argument ` |
| `eth_getUncleCountByBlockNumber`       | 🟠     | `fallback failed with 'missing value for required argument 0'. run error was 'missing value for required argument 0` |
| `eth_getCode`                          | 🟠     | `fallback failed with 'missing value for required argument 0'. run error was 'Relay request failed validation: invalid relay request: invalid eth_getCode parameters object: empty params array` |
| `eth_sendRawTransaction`               | 🟠     | `fallback failed with 'invalid parameters: not enough params to decode'. run error was 'missing value for required argument 0` |
| `eth_call`                             | 🟠     | `fallback failed with 'missing value for required argument 0'. run error was 'Relay request failed validation: invalid relay request: invalid eth_call parameters object: empty params array` |
| `eth_estimateGas`                      | 🟠     | `fallback failed with 'missing value for required argument 0'. run error was 'Relay request failed validation: invalid relay request: invalid eth_estimateGas parameters object: empty params array` |
| `eth_getBlockByHash`                   | 🟠     | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getBlockByNumber`                 | 🟠     | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getTransactionByHash`             | 🟠     | `fallback failed with 'missing value for required argument 1'. run error was 'missing value for required argument 0` |
| `eth_getTransactionByBlockHashAndIndex` | 🟠     | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getTransactionByBlockNumberAndIndex` | 🟠  | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getTransactionReceipt`            | 🟠     | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getUncleByBlockHashAndIndex`      | 🟠    | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getUncleByBlockNumberAndIndex`    | 🟠    | `fallback failed with 'missing value for required argument 2'. run error was 'missing value for required argument 0` |
| `eth_getLogs`                          | 🟠     | `fallback failed with 'Invalid params: invalid length 0, expected a tuple of size 1.'. run error was 'Relay request failed validation: invalid relay request: invalid eth_getLogs parameters object: empty params array` |
| `eth_getWork`                          | 🟠     | `fallback failed with 'the method eth_getWork does not exist/is not available'. run error was 'not supported, consensus engine is not ethash` |
| `eth_submitWork`                       | 🟠     | `the method eth_submitWork does not exist/is not available'. run error was 'missing value for required argument 0` |
| `eth_submitHashrate`                   | 🟠     | `fallback failed with 'the method eth_submitHashrate does not exist/is not available'. run error was 'missing value for required argument 0` |
| `net_version`                          | 🟢    |  |
| `net_peerCount`                        | 🟢    |  |
| `net_listening`                        | 🟢    |  |

### CODE REVIEW

**Comment by kounkou** [comment]
Tested that everything works as expected

```bash
curl -X POST http://127.0.0.1:8545      -H 'Content-type: application/json'      -d '{
         "jsonrpc": "2.0",
         "id": 37,
         "method": "connector_callRPC",
         "params": ["{\"method\": \"eth_accounts\", \"params\": []}"]
     }' | jq
```

```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   292  100   128  100   164   118k   151k --:--:-- --:--:-- --:--:--  285k
{
  "jsonrpc": "2.0",
  "id": 37,
  "result": "{\"jsonrpc\":\"2.0\",\"id\":0,\"result\":[\"0x6f29cea3011904b143dea3a09f736f8cbf83c0c1\"]}"
}
```

**Review by igor-sirotin — APPROVED** [review]
haha, lucky day!
image

**Review by kounkou — APPROVED** [review]

**Comment by kounkou** [comment]
Approved on @MishkaRogachev behalf since he opened the PR

**Comment by MishkaRogachev** [comment]
I can't review this PR since i've opened it. @kounkou i think you can merge it!

**Pull request merged**
