### PR TITLE
fix(activity)_: report other token types than ERC20

### LINKED ISSUE #15233: Activity API is broken
@ulisesmac reported the following issues with the activity API

- [x] NFT incremental updates (lazy load) is not sending proper data
  - The identities for the NFTs are wrong. The event is not received in Desktop
- [x] `requestID` is not returned
  - In desktop we use the session based API that provides a self incrementing `sessionID`
  - After checking the request ID is not delivered with the payload but with the `walletevent.Event`; see https://github.com/status-im/status-go/blob/3bb5c9c815382f978ed614ba2a0a8cec21d1678f/services/wallet/walletevent/events.go#L31
- [x] Token type `Erc721`, `Erc1155` is not returned (always `Erc20`)
  - Activity doesn't support anything else; see [activity.go#L592](https://github.com/status-im/status-go/blob/a300e12853cc0a62d0a6e2c407d208dce3db9875/services/wallet/walletevent/events.go#L31)

### PR DESCRIPTION
**Pull request by stefandunca**
### Closes: [#15233](https://github.com/status-im/status-desktop/issues/15233)

This fixes incremental updates for tokens and proper report of token type for mobile (in desktop we didn't use it)

### CODE REVIEW

**Comment by stefandunca** [comment]
Hey @ulisesmac please have a look at my changes and check if it fixes the issues you reported. It works for desktop, I get the notifications, the NFT name si reported on the client side. The token URL is missing though, that must be a collectible fetching issue at first glance.

**Comment by ulisesmac** [comment]
> Hey @ulisesmac please have a look at my changes and check if it fixes the issues you reported. It works for desktop, I get the notifications, the NFT name si reported on the client side. The token URL is missing though, that must be a collectible fetching issue at first glance.

Hey @stefandunca !

Thanks for the update, and sorry for the late response on this.

1. :white_check_mark:  The collectible type is now fixed!

2.  :white_check_mark:
    > After checking the request ID is not delivered with the payload but with the walletevent.Event
    
    Yes, you are right!, thanks for the clarification



2. The signal `wallet-activity-filtering-entries-updated` seems still btoken, it returns repeated entries and doesn't return the data for all the NFT transactions.

    This is the signal response for the address `0x779425b89cd705c83ae588e458efed05c9f90f9b`:

```json
[{"payloadType":2,"transaction":{"chainId":11155111,"hash":"0xba9acc92d9dc5c442f6fe8bca970673c0cb8dba4c74fdd89aba680ef8d6d161b","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0x9d043a75b0687780fa6d5d668effab920d511ba953f37993a8b993985e4a84fa","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0x9d043a75b0687780fa6d5d668effab920d511ba953f37993a8b993985e4a84fa","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0xba9acc92d9dc5c442f6fe8bca970673c0cb8dba4c74fdd89aba680ef8d6d161b","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0xba9acc92d9dc5c442f6fe8bca970673c0cb8dba4c74fdd89aba680ef8d6d161b","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0xba9acc92d9dc5c442f6fe8bca970673c0cb8dba4c74fdd89aba680ef8d6d161b","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0xba9acc92d9dc5c442f6fe8bca970673c0cb8dba4c74fdd89aba680ef8d6d161b","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0xba9acc92d9dc5c442f6fe8bca970673c0cb8dba4c74fdd89aba680ef8d6d161b","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""},
 {"payloadType":2,"transaction":{"chainId":11155111,"hash":"0x9d043a75b0687780fa6d5d668effab920d511ba953f37993a8b993985e4a84fa","address":"0x779425b89cd705c83ae588e458efed05c9f90f9b"},"nftName":"Genesis","nftUrl":""}]
```

4. The balances for 1155 tokens are not in WEI, is it right?

5. 
    > The token URL is missing though, that must be a collectible fetching issue at first glance.

    Will we open a follow-up to address it?

**Comment by Cuteivist** [comment]
@ulisesmac 
I updated the PR .

> The signal wallet-activity-filtering-entries-updated seems still btoken, it returns repeated entries and doesn't return the data for all the NFT transactions.

I added fix for that.

> The token URL is missing though, that must be a collectible fetching issue at first glance.

It could be investigated further. UI should implement loading fail states too for NFT as it is not always possible to get nft image.
https://github.com/status-im/status-desktop/issues/15459

cc @stefandunca

**Comment by stefandunca** [comment]
> The balances for 1155 tokens are not in WEI, is it right?

`amountIn`/`amountOut` should be the count of token transfered and not the transaction cost if that is what you are asking.

**Comment by ulisesmac** [comment]
@Cuteivist @stefandunca 

I've tested it and now the transactions are not repeated:
```json
[{"payloadType" :2, "transaction" : {"chainId" :11155111, "hash" : "0xce2a483bf696be9ce68803bf551419a6b5425486f22719adefd83a0e6f1339ad", "address" : "0x779425b89cd705c83ae588e458efed05c9f90f9b"}, "nftName" : "Genesis", "nftUrl" : ""},
 {"payloadType" :2, "transaction" : {"chainId" :11155111, "hash" : "0x1d465d9f229968a7d31e29797361347ed5314a80691a59913adcde5de9a496c0", "address" : "0x779425b89cd705c83ae588e458efed05c9f90f9b"}, "nftName" : "Genesis", "nftUrl" : ""}]
```

But there are still many transactions involving NFTs that are missing, not sure but seems we are just returning the last two transactions.

**Comment by stefandunca** [comment]
> But there are still many transactions involving NFTs that are missing, not sure but seems we are just returning the last two transactions.

@Cuteivist can the wallet core team help move things forward here?

@IvanBelyakoff you recently found that there are some problems downloading historical data. Can the historical data access be the root problem for this missing entries?

**Comment by Cuteivist** [comment]
@ulisesmac 
This event will return currently filtered values. That means, when we limit 10 entries in desktop that means only first 10 entries will be checked.
Just making sure that they are actually fetched to the app.

**Comment by ulisesmac** [comment]
> @ulisesmac This event will return currently filtered values. That means, when we limit 10 entries in desktop that means only first 10 entries will be checked. Just making sure that they are actually fetched to the app.

I'm asking for the last 50 transactions for that account, I got the transactions and some of them involve NFTs, after getting those transactions I receive the signal `wallet-activity-filtering-entries-updated` but it only contains data for two entries, it should contain data for more.

I think you could replicate it by adding the address as a watch-only account

**Comment by Cuteivist** [comment]
@ulisesmac I had an another looking into the PR. I misunderstood code a little. 
I added new commit that restore update results.
Duplicated values you listed in https://github.com/status-im/status-go/pull/5406#issuecomment-2195749275 were most likely created because of another issue, which is fixed here: https://github.com/status-im/status-go/pull/5435

Now it updates all of the activity entries instead of first one for each nft.

**Review by IvanBelyakoff — APPROVED** [review]
Thanx Stefan and Emil!

**Comment by IvanBelyakoff** [comment]
> @IvanBelyakoff you recently found that there are some problems downloading historical data. Can the historical data access be the root problem for this missing entries?

This happened only on Arbitrum and Optimsm

**Review by belalshehab — APPROVED** [review]

**Pull request merged**
