### PR TITLE
Run tests with race flag on develop by Travis cron

### PR DESCRIPTION
**Pull request by adambabik**
Run tests with `-race` flag by Travis' cron if being on the develop branch so that we have an automated way of detecting race condition issues.

### CODE REVIEW

**Comment by mandrigin** [comment]
@adambabik don't we have exactly that working on Jenkins already?

**Comment by adambabik** [comment]
@mandrigin regular `make ci` is executed: https://github.com/status-im/status-go/blob/develop/_assets/ci/Jenkinsfile-manual#L62

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Review by gravityblast — APPROVED** [review]
LGTM

**Comment by pedropombeiro** [comment]
@adambabik, @mandrigin we have a nightly Jenkins build which runs `make test-unit-race` and `make test-e2e-race` targets: https://status-im.slack.com/archives/C95SNE0LB/p1524017181000089

It is outputting this warning every night to #go-team-updates until we fix the race issues. I'm guessing it is either not visible enough, or we just got used to ignoring that channel?

**Comment by adambabik** [comment]
@PombeirP I haven't noticed that actually. Can it ping `@go` if failing?

**Comment by adambabik** [comment]
Closing as we have Jenkins job checking this.

**Comment by pedropombeiro** [comment]
@adambabik It is mentioning `GoTeam`. I'm not sure if I can have it unfurl the `@go` text automatically, that's why I've chosen `GoTeam`. Do you have Slack set up to highlight `GoTeam`?

**Comment by adambabik** [comment]
Yes, I do but I don't see notifications or the counter in the channel... I will figure it out.

**Comment by pedropombeiro** [comment]
I've kicked a build which will mention `@go` just to be sure that it doesn't unfurl.

**Pull request closed without merging**
