### PR TITLE
Use same kdf_iter as for protocol db

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by adambabik** [comment]
We have very similar code in https://github.com/status-im/status-protocol-go/blob/master/sqlite/db.go. Maybe we can agree on a single version here and remove duplicated part from status-protocol-go? Currently, the one in status-protocol-go has more features.

**Comment by dshulyak** [comment]
@adambabik would be nice. it will be easier to integrate that code once i finish/merge this https://github.com/status-im/status-go/pull/1553 , cause all migrations assets will be already consolidated

**Comment by adambabik** [comment]
@dshulyak #1553 is merged now :)

**Comment by dshulyak** [comment]
@adambabik oh i linked wrong pr :) i meant my change that does the same for db's in status-go https://github.com/status-im/status-go/pull/1540

**Comment by dshulyak** [comment]
@adambabik can i please merge this change ? :) this is kinda a bug that needs to be addressed before release

**Review by adambabik — APPROVED** [review]

**Comment by adambabik** [comment]
@dshulyak sure, sorry, forgot about it.

**Pull request merged**
