### PR TITLE
Remove xgo builds

### PR DESCRIPTION
**Pull request by adambabik**
We don't need xgo anymore because we switched to gomobile for iOS and Android and building from source for Status Desktop.

### CODE REVIEW

**Comment by adambabik** [comment]
@jakubgs in which repo do we keep content of our website? I need to change fifth point on https://status.im/build_status/status_go.html.

**Comment by jakubgs** [comment]
Right here:
https://github.com/status-im/status.im/blob/5edafcbbf41/source/build_status/status_go.md#L106-L113

**Review by jakubgs — APPROVED** [review]
Love removing stuff.

**Comment by adambabik** [comment]
Docs changed: https://github.com/status-im/status.im/pull/411

**Pull request merged**
