### PR TITLE
Android mute notifications

### PR DESCRIPTION
**Pull request by jo-mut**
Disables sending notifications to muted chats

### CODE REVIEW

**Review by cammellos — APPROVED** [review]
Don't forget to bump the `VERSION` file

**Comment by jo-mut** [comment]
what do you mean by bump the version file

**Comment by cammellos** [comment]
@jo-mut when you make a change to status-go, you should increase version here:

https://github.com/status-im/status-go/blob/develop/VERSION

the format is 0.x.y where `y` is for non-breaking changes, and `x` is for breaking changes.
So say the version is currently 0.95.1
If you add a breaking change -> 0.96.0
If you add a non-breaking change (such as your case, though is arguable) -> 0.95.2

**Comment by jo-mut** [comment]
oooh cool i understand now

**Review by Samyoul — APPROVED** [review]

**Pull request merged**
