### PR TITLE
Use newer CHT defined in go-ethereum

### PR DESCRIPTION
**Pull request by dshulyak**
We merged update to 1.8.1 but our CHTs were not updated. I propose to remove our patch and use original CHTs for ropsten and mainnet until we will want to update them again.

Maybe we won't even need a patch and will simply update go-ethereum to 1.8.x

### CODE REVIEW

**Comment by divan** [comment]
> until we will want to update them again.
We actually have to update it regularly to shorten the time to initial sync.
Some context: before introducing patches, latest updated CHT hash has been stored in `cht.json` file.

I'm working now on the autoupdate CHT hash root from bootnodes, then it can be removed safely, yes.

**Comment by dshulyak** [comment]
> We actually have to update it regularly to shorten the time to initial sync.

go-ethereum publishes minor releases quite frequently

> I'm working now on the autoupdate CHT hash root from bootnodes, then it can be removed safely, yes.

even better 👍 let's start to call them static nodes instead, calling them bootnodes is very misleading to new people

**Review by mandrigin — APPROVED** [review]
The less patches — the better :)

**Comment by themue** [comment]
@dshulyak See https://github.com/status-im/status-go/issues/708 , working on renaming them everywhere.

**Comment by dshulyak** [comment]
@themue yes, my point was that they never were boot nodes in terms of go-ethereum. but it is good that we are renaming them in our configuration file as well.

**Comment by themue** [comment]
@dshulyak Yeah, naming didn't match.

**Review by themue — APPROVED** [review]

**Pull request merged**
