### PR TITLE
Bump go-waku to latest

### PR DESCRIPTION
**Pull request by kaichaosun**
Important changes:
- [x] isFilterSubAlive is temporarily set to nil

### CODE REVIEW

**Comment by chaitanyaprem** [comment]
Can you indicate the reason for this change? If it is just for testing, hope this won't need to be merged.

**Comment by kaichaosun** [comment]
I was thinking the filter subscription is not used in production, so should be safe to set `isFilterSubAlive` to not return err, or is there better way to fix this bump? @chaitanyaprem 
We should bump go-waku to unblock other features.

**Comment by chaitanyaprem** [comment]
> I was thinking the filter subscription is not used in production, so should be safe to set `isFilterSubAlive` to not return err, or is there better way to fix this bump? @chaitanyaprem We should bump go-waku to unblock other features.

Ok, got it. Then it should be ok.

**Comment by kaichaosun** [comment]
Close to in favor of https://github.com/status-im/status-go/pull/5258, using https://github.com/waku-org/go-waku/tree/status-go

**Pull request closed without merging**
