### PR TITLE
fix: archive decryption fail

### LINKED ISSUE #13105: Infinite importing message archive
# Bug Report

I get this in DESKTOP (should be status-go actually I suppose) logs:
This turns into a loop and never stops.

```go
2023-12-26T19:41:10.620Z        INFO    communities/manager.go:313      importing message archive, 59 left
2023-12-26T19:41:10.627Z        INFO    communities/manager.go:313      extracting messages from history archive        {"archive id": "0xd3a07a7d95e6c4565d7635c293f58ba5b5ccc663edafa655a3d0c37a042ac55d"}
2023-12-26T19:41:10.627Z        INFO    communities/manager.go:313      loading history archive data into memory        {"data_size_MB": 1.175980567932129}
2023-12-26T19:41:10.630Z        INFO    communities/manager.go:313      failed to decrypt message archive       {"error": "Hash ratchet group id not found"}
2023-12-26T19:41:10.630Z        INFO    communities/manager.go:313      failed to extract history archive messages      {"error": "Hash ratchet group id not found"}
2023-12-26T19:41:10.726Z        INFO    communities/manager.go:313      importing message archive, 59 left
2023-12-26T19:41:10.728Z        INFO    communities/manager.go:313      extracting messages from history archive        {"archive id": "0xd3a07a7d95e6c4565d7635c293f58ba5b5ccc663edafa655a3d0c37a042ac55d"}
2023-12-26T19:41:10.728Z        INFO    communities/manager.go:313      loading history archive data into memory        {"data_size_MB": 1.175980567932129}
2023-12-26T19:41:10.731Z        INFO    communities/manager.go:313      failed to decrypt message archive       {"error": "Hash ratchet group id not found"}
2023-12-26T19:41:10.731Z        INFO    communities/manager.go:313      failed to extract history archive messages      {"error": "Hash ratchet group id not found"}
2023-12-26T19:41:10.820Z        INFO    communities/manager.go:313      importing message archive, 59 left
2023-12-26T19:41:10.825Z        INFO    communities/manager.go:313      extracting messages from history archive        {"archive id": "0xd3a07a7d95e6c4565d7635c293f58ba5b5ccc663edafa655a3d0c37a042ac55d"}
2023-12-26T19:41:10.825Z        INFO    communities/manager.go:313      loading history archive data into memory        {"data_size_MB": 1.175980567932129}
2023-12-26T19:41:10.829Z        INFO    communities/manager.go:313      failed to decrypt message archive       {"error": "Hash ratchet group id not found"}
2023-12-26T19:41:10.829Z        INFO    communities/manager.go:313      failed to extract history archive messages      {"error": "Hash ratchet group id not found"}
```

### PR DESCRIPTION
**Pull request by igor-sirotin**
Closes https://github.com/status-im/status-desktop/issues/13105

➡️ Pro Tip: review by commits.

The problem was that we kept trying to decrypt the archives in a loop, though we obviously didn't have hash ratchet keys for it (for the archives themselves, not the messages inside). The fix is to postpone the next attempt import attempt. If we don't have the key for this archive, we don't have all the further ones as well.

I also wrote a test that ensures that the the archive protocol works properly for the community channel-level encryption.

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks good! Nice find and test

**Review by osmaczko — APPROVED** [review]
Very nice test indeed! And a good candidate for -count=1000 :police_officer:

**Comment by igor-sirotin** [comment]
> And a good candidate for -count=1000 👮

😬 

```go
communities_messenger_token_permissions_test.go:1837: 
     Error Trace:	/Users/igorsirotin/Repositories/Status/status-desktop/vendor/status-go/protocol/communities_messenger_token_permissions_test.go:1837
     Error:      	"[]" should have 1 item(s), but has 0
     Test:       	TestMessengerCommunitiesTokenPermissionsSuite/TestImportDecryptedArchiveMessages
```

**Comment by igor-sirotin** [comment]
So I have 2 main reasons for the test flakiness:

1. `user can't post in community`
Owner sends an unencrypted message because of the members reevaluation race condition. 
Then Bob is able to decrypt the message, but finds the empty members list (because he doesn't have permissions to read channel members)
Fixed here: https://github.com/status-im/status-go/pull/5117

2. `failed to decrypt hash  {"error": "cipher: message authentication failed"}`
This one is still unobvious. But will be easier to investigate with the changes made.

**Comment by igor-sirotin** [comment]
Required:
- https://github.com/status-im/status-go/pull/5138
- https://github.com/status-im/status-go/pull/5137
- https://github.com/status-im/status-go/pull/5139

**Pull request merged**
