### PR TITLE
Update for status-protocol-go API changes

### PR DESCRIPTION
**Pull request by pedropombeiro**
This PR integrates the changes from https://github.com/status-im/status-protocol-go/pull/88.

This PR is part of a group of 3 PRs (https://github.com/status-im/status-protocol-go/pull/88, https://github.com/status-im/status-go/pull/1627, https://github.com/status-im/status-console-client/pull/128) and we should only merge when we're happy with the 3 of them.

### CODE REVIEW

**Comment by cammellos** [comment]
@PombeirP this is a non breaking change correct?

**Comment by pedropombeiro** [comment]
> @PombeirP this is a non breaking change correct?

Correct.

**Review by cammellos — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@cammellos on second thought, there is one aspect that can be considered a breaking change, so we might want to not merge this as-is. I've commented out the envelope monitor in status-protocol-go. We have 2 alternatives: mark this as WIP and continue with Nimbus effort, or I can spend some more time trying to isolate the envelope monitor as I did for the rest of the services. The reason I didn't touch the envelope monitor is that I'm not sure whether we want to port that implementation to Nimbus.

**Comment by cammellos** [comment]
@PombeirP yes, we need envelopes monitor otherwise all messages in status-react will be marked as pending and never confirmed, probably best to port it before merging

**Comment by pedropombeiro** [comment]
Ready for final review. This is now a non-breaking change. cc @cammellos

**Review by cammellos — APPROVED** [review]

**Pull request merged**
