### PR TITLE
Fix/unblocked contact messages receival

### LINKED ISSUE #7127: Chat - Cannot send messages to unblocked user
# Bug Report

## Description

After unblocking a user it is not possible to send them messages

## Steps to reproduce

1. Have a 1 to 1 chat with two users
2. User 1 blocks user 2
3. User 1 unblocks user 2
4. User 1 can now receive messages from user 2 but not send them.

#### Expected behavior

After unblocking, both users can message each other.

#### Actual behavior

https://user-images.githubusercontent.com/50769329/186411216-2cd55951-47a5-4e15-803b-dadd3999e7d4.mp4

### Additional Information

- Status desktop version: https://ci.status.im/job/status-desktop/job/platforms/job/macos/lastSuccessfulBuild/artifact/pkg/StatusIm-Desktop-220824-111243-1c7719.dmg
- Operating System: Mac

### PR DESCRIPTION
**Pull request by osmaczko**
make blocking contact local only
fixes: https://github.com/status-im/status-desktop/issues/7127

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks good to me. 

I'll just tag the people who worked on that initially to let them know. @pavloburykh @audriu 
We are removing the propagation, because blocking should stay local. See here: https://github.com/status-im/status-desktop/issues/7127#issuecomment-1292459256

**Comment by jrainville** [comment]
Maybe they don't work here anymore? @cammellos can we have your input on this PR?

**Comment by cammellos** [comment]
@jrainville looks good to me

**Review by cammellos — APPROVED** [review]

**Comment by pavloburykh** [comment]
> Looks good to me.
> 
> I'll just tag the people who worked on that initially to let them know. @pavloburykh @audriu We are removing the propagation, because blocking should stay local. See here: [status-im/status-desktop#7127 (comment)](https://github.com/status-im/status-desktop/issues/7127#issuecomment-1292459256)

Hey @jrainville Sorry, I have missed your mention. Let me test this changes on status-mobile side. I will provide feedback and then we are good to merge this changes I guess.

**Comment by pavloburykh** [comment]
@osmaczko Thanx for the PR. On mobile I am currently facing the following ISSUE.

### ISSUE 1 Unblocked user can send messages but another user cannot receive messages until adding him as contact

**Preconditions:** User A and User B are mutual contacts (mutual contact requests are enabled for both users)

**Steps:** 
1. User A blocks User B
2. User A unblocks User B
3. User A sends messages to User B
4. User B sends messages to User A
5. Observe the result

**Actual result:** 
1. After User A blocks User B, User B is removed from contacts of User A. User A remains in contacts of User B
2. The messages sent by User A are received by User B but are not visible for User A in 1-1 chat
3. The messages sent by User B to User A are not visible for User A in 1-1 chat
4. The sent and received messages appear in User's A chat after he adds User B as a contact again


https://user-images.githubusercontent.com/97245802/200559454-df8822a1-0e76-42b7-b967-1c9433c95cd0.mp4

[IOS_geth.log](https://github.com/status-im/status-go/files/9960896/IOS_geth.log)
[IOS_Status.log](https://github.com/status-im/status-go/files/9960897/IOS_Status.log)

[IOS_geth.log](https://github.com/status-im/status-go/files/9960908/IOS_geth.log)
[IOS_Status.log](https://github.com/status-im/status-go/files/9960909/IOS_Status.log)


**Expected result:**  (sorry for long read)

As for me, current changes are in a small contradiction with the logic of mutual contacts feature. 
After User A blocks User B we have a case when User A is still a contact to User B, but User B is not a contact to User A. In such situation it should be impossible for User A to send messages to User B as in fact they are not mutual contacts any more. But User B can send messages to User A and those messages will not be seen by User A even after he unblocks User B until he adds User B as mutual contact again. 

An example of expected behaviour (that is working now) is the case when User A removes User B from contacts and he is mutually been removed from contacts of User B too. In this situation users cannot send/receive messages from each other until they become mutual contacts again. 

Also, there is a question regarding the requirement: "We don't want the person who is blocked to know they've been blocked." But at the same time we are okay with the above behaviour when mutual contacts are mutually removed from each other contacts when one removes another from contacts. Why we are okay with the fact that user will know that they have been removed from contacts but not okay when they know about it as a result of been blocked? In fact, the person will never know about the fact that he/she has been blocked, but will know only the fact that has been removed from contacts. 

It would be great if someone (designers or product managers) provide expected behaviour of how these changes should correspond to mutual contact request feature. 

Thanx and sorry once again for long read. I just want to make sure that these changes will be in consistency with the logic of mutual contact request feature. 

cc @cammellos

**Comment by 0x-r4bbit** [comment]
Can we get an update here on the outstanding discussion?
We'd like to merge this

**Comment by cammellos** [comment]
> Can we get an update here on the outstanding discussion? We'd like to merge this

let me have a look at it today, to check what's the behavior on mobile and if this needs adjustment, I'll get back to it as soon as I verified the behavior

**Comment by 0x-r4bbit** [comment]
Thank you @cammellos

**Comment by cammellos** [comment]
@pavloburykh @PascalPrecht this a UI mobile bug, I will create a separate issue for it, but this can be merged as not related.
Thank you for your patience

**Comment by 0x-r4bbit** [comment]
Thank you for taking the time to check on this

**Pull request merged**
