### PR TITLE
Remove `cancelOutgoingContactRequest` from api and messenger

### PR DESCRIPTION
**Pull request by MishkaRogachev**
For https://github.com/status-im/status-desktop/issues/9901 and https://github.com/status-im/status-desktop/issues/9898

Its possible to spam with contact requests using `cancelOutgoingContactRequest`. See https://github.com/status-im/status-desktop/issues/9901#issuecomment-1469761308

### CODE REVIEW

**Comment by ilmotta** [comment]
@MishkaRogachev, I've created https://github.com/status-im/status-mobile/issues/15357 yesterday and I'll play it now to catch up to this status-go change so we don't break anything on mobile. I'll let you know once it's done on Mobile.

**Comment by ilmotta** [comment]
@MishkaRogachev, I just tested `status-mobile` with (supposedly) all the code removed, but it looks like there's more code to be removed/changed in `status-go`.

My steps to test, pointing to this `feat/remove-cancel-contact-request` branch were:

1. User `A` and `B` are not mutual contacts.
2. `A` sends a CR to `B`.
3. `A` should NOT see a notification, but the app still sees an increment in the unread counter. So the endpoint has been removed, but a notification is still generated. I double checked the unencrypted db and a single notification was indeed created for the CR sender.

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev, I just tested `status-mobile` with (supposedly) all the code removed, but it looks like there's more code to be removed/changed in `status-go`.
> 
> My steps to test, pointing to this `feat/remove-cancel-contact-request` branch were:
> 
> 1. User `A` and `B` are not mutual contacts.
> 2. `A` sends a CR to `B`.
> 3. `A` should NOT see a notification, but the app still sees an increment in the unread counter. So the endpoint has been removed, but a notification is still generated. I double checked the unencrypted db and a single notification was indeed created for the CR sender.

I was recently discussing with John about the notification for pending outgoing CRs, and we can't find why we removed it. It is present in both the new and old design. So in this PR I think we should just remove the ability to cancel pending outgoing CR but do nothing about notifications. Further, I think we need to clarify the requirements for the whole contact request mechanism and unify the endpoints for mobile and desktop. In the current state, a lot of functionality is broken for desktop.

**Review by alwx — APPROVED** [review]
Sad to see it being removed but code-wise looks good.

**Comment by ilmotta** [comment]
> Sad to see it being removed but code-wise looks good.

Yeah, it was an interesting feature @alwx

@MishkaRogachev, I'm a bit confused. Merging this PR will introduce a bug for clients. Removing the endpoint is half of the work. Why not also update the code that generates the outgoing contact request notification?

> Further, I think we need to clarify the requirements for the whole contact request mechanism and unify the endpoints for mobile and desktop. In the current state, a lot of functionality is broken for desktop.

Cool! The CR flows in mobile are generally simple since the heavy work is all on `status-go`. But we can definitely adjust if the existing solution is suboptimal for Desktop.

**Comment by MishkaRogachev** [comment]
> @MishkaRogachev, I'm a bit confused. Merging this PR will introduce a bug for clients. Removing the endpoint is half of the work. Why not also update the code that generates the outgoing contact request notification?

As i understand @John-44 we want to remove feature to cancel outgoing contact request (hope temporary) but we still want to have notifications for outgoing CRs in pending state. It can be found [here](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=4537-515620&t=ol5pTYQ7vKIEpltw-0) (just curious how to share a figma link with defined viewport)

**Comment by ilmotta** [comment]
> As i understand @John-44 we want to remove feature to cancel outgoing contact request (hope temporary) but we still want to have notifications for outgoing CRs in pending state. It can be found [here](https://www.figma.com/file/eDfxTa9IoaCMUy5cLTp0ys/Shell-for-Mobile?node-id=4537-515620&t=ol5pTYQ7vKIEpltw-0) (just curious how to share a figma link with defined viewport)

All right, so it's just the canceling that's going away, but we still want to show the notification. In that case we're good in this PR @MishkaRogachev. I tested it locally. I'll open the PR today and on Monday it'll probably be merged since it's easy to be reviewed.

Could you hold this PR from being merged until Monday, max Tuesday?

**Comment by MishkaRogachev** [comment]
> Could you hold this PR from being merged until Monday, max Tuesday?

Sure!

**Pull request merged**
