### PR TITLE
[WIP] Proxy records found in ethereum network to rendezvous

### PR DESCRIPTION
**Pull request by dshulyak**
Standalone proxy binary that will store records in rendezvous.
I implemented it as a separate thing, separate from peer pool, cause it seems to be much simpler this way.

Consumer will have to check Proxied field and restore original identity from ENR records that contain such field. The idea is to make topic pool aware of this field and consume it through common interface.

Strictly speaking we still can run discovery v5 on mobile device, but it can easily take 10m (and noticeable amount of discovery traffic) to find a LES node.

# HOW-TO rollout proxy servers

Image is built from the following Dockerfile - https://github.com/status-im/status-go/blob/2c0ad8d1b1538b68922a47aadebc73eaf8fef686/_assets/build/Dockerfile-proxy

Usage:
```
  -bootnode value
    	Discovery v5 node.
  -laddr string
    	Listening address for discovery v5. (default "0.0.0.0:31143")
  -les int
    	Proxy les topic for a given network.
  -rendezvous-node value
    	Rendezvous server.
  -topic value
    	Topic that will be proxied
  -use-ethereum-boot
    	If true ethereum bootnodes will be used
  -v string
    	Logger verbosity (default "info")
```

Important options:
- `les` must be set to 1 or 3, in order to proxy LES nodes running in mainnet or ropsten
- `rendezvous-node` allows to set multiple nodes
- `use-ethereum-boot` will use discovery v5 bootnodes used in ethereum network, therefore usually we will need to set `bootnode` options only for tests.

# HOW-TO sync from nodes discovered by rendezvous

## launch rendezvous instance for tests
I am usinng binaries but the same can be done with images

```
./rsvr --keyhex 6f7065ad50fb49f128e363cd38170c02f25db5038c21b057b039d03faeff8b48
```

## launch proxy with test rendezvous instance and upstream bootnodes
Proxy needs to be compiled from this PR
```
go build ./cmd/proxy
```

Run it with les=1, which will tell it to proxy nodes with specific topic which is derived from mainnet genesis
```
./proxy -les 1 -use-ethereum-boot --rendezvous-node /ip4/0.0.0.0/tcp/9090/ethv4/16Uiu2HAmABXGJRVjiY1emJo5Lr6skhNHN5HS6anzgSutizSpQoeB
```

## launch statusd with clean state
Needs to be compiled from this PR

```
go build -o statusd ./cmd/statusd/
```

```
./statusd -rendezvous -rendezvous-node /ip4/0.0.0.0/tcp/9090/ethv4/16Uiu2HAmABXGJRVjiY1emJo5Lr6skhNHN5HS6anzgSutizSpQoeB -les -networkid 1 --topic.search LES2@d4e56740f876aef8=3,3 -log=info --datadir=/tmp/clean1
```

For now topic **LES2@d4e56740f876aef8** is passed using command line arguments, i will extend initializer to construct this topic when LES is launched.

# Results

Nodes discovered almost instantly (using just discovery v5 it can take up to 10 minutes).
Syncing from last CHT (~35 days old) took slightly more than 10 minutes:
```
INFO [08-10|08:48:14.195] Imported new block headers               count=192 elapsed=2.028s number=5898431 hash=81a1f9…5b5f62 ignored=0
...
INFO [08-10|08:59:20.831] Imported new block headers               count=1    elapsed=7.644ms   number=6120677 hash=413b14…ed3e06 ignored=0
```

State on disk after sync:

```
du -lh /tmp/clean1
20K	/tmp/clean1/status-db
125M	/tmp/clean1/Statusd/ethash
180M	/tmp/clean1/Statusd/lightchaindata
304M	/tmp/clean1/Statusd
4,0K	/tmp/clean1/keystore
304M	/tmp/clean1
```

### CODE REVIEW

**Comment by adambabik** [comment]
`304M	/tmp/clean1/Statusd` -- not a trivial number for mobile nodes but it's over 30 days. 

Great instructions and explanation what's going on here and how to do it piece by piece! 👏

**Comment by dshulyak** [comment]
> 304M /tmp/clean1/Statusd -- not a trivial number for mobile nodes but it's over 30 days.

but that also means that for 2 month it will be around 600mb, and so on. I don't think that it is sustainable/usable for mobile client

we should plan for enabling generating CHT on light client side, and pruning everything older than that.

**Comment by dshulyak** [comment]
Another thing that I noticed after running tests periodically: it is common that all found peers disconnect me with "to many peers" reason, and I am not able to find any peer with "free" slot over prolonged periods of time.

It can be reproduced by using rendezvous and status client or discovery v5 and original geth client.
So, it seems that it will be pretty hard or even impossible to guarantee that peers for mobile devices can be simply discovered whenever you want.

**Comment by adambabik** [comment]
Tested successfully on `eth.staging` with:
```
./build/bin/statusd \
    -rendezvous \
    -rendezvous-node=/ip4/174.138.107.239/tcp/30703/ethv4/16Uiu2HAkyJHeetQ4DNpd4NZ2ntzxMo25zcdpvGQRqkD5pB9BE6RU \
    -les \
    -networkid 1 \
    -topic.search LES2@d4e56740f876aef8=3,3 \
    -log=DEBUG \
    -datadir=./proxy-les \
    -ipc
```

**Comment by adambabik** [comment]
Can we close this one as it looks like replaced with #1165?

**Comment by dshulyak** [comment]
yes i was going to close it

**Pull request closed without merging**
