### PR TITLE
Fix a race condition in whisper time source setter.

### PR DESCRIPTION
**Pull request by mandrigin**
Fixes a race condition uncovered by `make test-unit-race` in Whisper time source code.

### CODE REVIEW

**Review by themue — APPROVED** [review]
LGTM

**Review by dshulyak — CHANGES_REQUESTED** [review]
please disable unit tests with race then, there is no need to use mutex for a thing that needs to be set once. i planned to pass it as a config value today

**Comment by themue** [comment]
@dshulyak So will remove `SetTimeSource()` to? Would expect a config value set only once to be passed in constructor function.

**Comment by mandrigin** [comment]
@dshulyak 
1) with the current code, the time source can be set up at any time, so mutex makes sense
2) I disagree about disabling checks for race conditions in tests 😛

**Comment by dshulyak** [comment]
@themue yes, i will remove SetTimeSource too, TimeSource will become a value on a WhisperConfig

**Comment by mandrigin** [comment]
yeah, and it blocks my other PR: https://travis-ci.org/status-im/status-go/jobs/375981045

<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/jobs/375981045">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@dshulyak my take on that would be then: when you remove the setter, you can remove the mutex. That way we keep the code correct at any time and not somewhere in the future.

**Comment by mandrigin** [comment]
closing because the problem was fixed in a better way by #915

**Pull request closed without merging**
