### PR TITLE
Add probot settings

### PR DESCRIPTION
**Pull request by pedropombeiro**
This tiny PR adds a reference to the baseline probot settings

### CODE REVIEW

**Comment by adambabik** [comment]
What is probot? What are we using it for?

**Comment by oskarth** [comment]
@PombeirP @adambabik We use it for automating common PR reviews, especially wrt https://github.com/status-im/status-react/projects/7 (moving to REVIEW, welcoming new contributors etc).

I guess the flow would work a bit different and have to be adapted to the existing/desirable flow for status-go. @PombeirP how easy is this to do? For example, welcoming new contributors would be universally welcome, but moving to "REVIEW" board currently doesn't make sense with the existing status-go workflow.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-react">status-im/status-react</a></strong></div><div>status-react - a free (libre) open source, mobile OS for Ethereum</div></blockquote>

**Comment by pedropombeiro** [comment]
@oskarth this config file is customizable for each repository (right now it is just importing the defaults from the https://github.com/status-im/probot-settings repo). So in theory we should be able to make a config structure that would fit both repositories. Right now nothing happens for status-go since the bot can't find the project by name, but we could just leave the project name empty in the config to signify that we want to disable the functionality for this repo.

**Comment by pedropombeiro** [comment]
Oh, nice to see that link unfurling by the bot is working.

**Pull request merged**
