### PR TITLE
Create a script that auto-applies geth-patches #603

### LINKED ISSUE #603: Create a script that auto-applies `geth-patches`.
# Problem

We have a number of patches for `go-ethereum` that are located in `/geth-patches` folder.
We apply all of them manually.
We need a script that will apply these patches automatically.

# Acceptance Criteria

1. There is a script that applies `/geth-patches` to a specified directory.
2. If there is no directory specified — apply it to `./vendor/ethereum/go-ethereum`
3. If the patch was already applied — do not apply it > 1 time. (e.g. keep track of applied patches in the target directory).
4. The script should exit if a patch could not be successfully applied.
5. (Preferably) no external dependencies should be brought by this script. (We assume `bash` and `git` are installed).
6. The patch that failed should be rolled back, so a developer using this script is able to fix it and try again.

### PR DESCRIPTION
**Pull request by canercidam**
Add patcher. Usage `./patcher -p <base_path> -r -v`. `-r` flag causes the script to revert all patches in reverse order and exit. `-v` is for making error reporting verbose.

Default behaviour:
- Checks each patch by reverting in reverse order. If it can, then stores each as an applied patch.
- Applies all patches starting from first one and reports the ones which haven't been applied previously. Also stops and reverts the last failing patch.

Closes #603

### CODE REVIEW

**Comment by divan** [comment]
Thanks @canercidam! Great bash kung-fu skills!

I'm currently getting this output (0004 patch have been removed, but still lives in geth-patches, that's another issue):
```
$ ./patcher

Previously applied:
===================
/Users/divan/src/github.com/status-im/status-go/geth-patches/0000-accounts-hd-keys.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0002-les-api-status.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0003-dockerfiles-wnode-swarm.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0006-latest-cht.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0007-README.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0008-tx-pool-nonce.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0009-whisper-envelopes-tracing.patch
/Users/divan/src/github.com/status-im/status-go/geth-patches/0010-geth-17-fix-npe-in-filter-system.patch
===================

Applying: /Users/divan/src/github.com/status-im/status-go/geth-patches/0004-whisper-notifications.patch
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/notifications/discovery.go:0
error: vendor/github.com/ethereum/go-ethereum/whisper/notifications/discovery.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/notifications/provider.go:0
error: vendor/github.com/ethereum/go-ethereum/whisper/notifications/provider.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/notifications/server.go:0
error: vendor/github.com/ethereum/go-ethereum/whisper/notifications/server.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/notifications/utils.go:0
error: vendor/github.com/ethereum/go-ethereum/whisper/notifications/utils.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/whisperv2/whisper.go:134
error: vendor/github.com/ethereum/go-ethereum/whisper/whisperv2/whisper.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/api.go:313
error: vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/api.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/doc.go:32
error: vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/doc.go: patch does not apply
error: patch failed: vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/whisper.go:77
error: vendor/github.com/ethereum/go-ethereum/whisper/whisperv5/whisper.go: patch does not apply

Failed and reverting: /Users/divan/src/github.com/status-im/status-go/geth-patches/0004-whisper-notifications.patch
```
So perhaps output from failed patch attempt can be just a one liner, if possible.

Also, there is a plan to add support for temporary release-bound patches: https://github.com/status-im/status-go/issues/575 It'll be a separate issue I guess, but it might affect the code a bit.

**Comment by canercidam** [comment]
Thanks @divan!

When I revert all and apply again, all seems to be working fine except for one error in the end, which I don't know the reason yet:
```
Applying: /home/mo/gopath/src/github.com/status-im/status-go/geth-patches/README.md
error: unrecognized input
```
After trying to re-apply, I get the same output as you do which I think is because there are ~~conflicting~~ intercepting patches. In other words, if patch 7 overwrites what path 4 writes previously, it's not possible to do a valid revert check on patch 4 anymore in top-to-bottom order so it reports that as a unapplied patch and applying it eventually fails.

We can do revert-checking in the reverse order by actually applying without `--check` flag I just added, then applying all from beginning. That way, I don't think there will be any conflicts or errors. But please confirm if it sounds good. :)

About the reported attempt: I left them to be verbose because otherwise it gets very confusing to know the reason sometimes (a target file could be missing). But I can turn that off as well if it still sounds like a better option.

**Comment by mandrigin** [comment]
@canercidam in this error message. Did it try to apply `README.md`?

We have number prefixed in the filenames, so they should be patched in that order and reversed in the opposite, I think.

**Comment by canercidam** [comment]
@mandrigin Ah, lol. I didn't look carefully enough to realize that's not a patch file. :smile: I'll change it to use `*.patch` files only. And will correct the loop order.

**Comment by canercidam** [comment]
Updated the PR description accordingly after last changes. @divan the problem about 0004 is gone now. So basically, the current way to work with the script is:
1) Try to apply all patches and see an error.
2) Fix the problem.
3) Run the script again so it reverts all while saving paths of previously applied.
4) Applies all from the beginning but reports only previously unapplied.
5) Problem again. Do another fix, it reverts all again and so on until all are successfully applied.

@mandrigin The issue mentioned "not applying an applied patch again" as an acceptance criteria. Does this workflow conflict with anything expected? Starting from any given patching state, I'm not sure if there is a more healthy way of knowing if a patch is applied or not. Another option is using a `.patcher-state` file but that can be more problematic IMHO.

**Comment by mandrigin** [comment]
@canercidam yeah, as long as there is a decent process of fixing one patch and re-applying it, it is just fine.
With every new upstream update, some patches might fail, so we need a decent process of tweaking them.

**Review by mandrigin — APPROVED** [review]
LGTM!

**Review by adambabik — APPROVED** [review]
1. Do we want to keep it in the project root directory?
2. Please add a comment with usage section. I can see that it's possible to provide options `-p`, `-r` and `-v` but it would be great to have a comment explaining what they do at the beginning of the file.

**Review by b00ris — APPROVED** [review]
Thanks a lot, @canercidam! Looks good to me.

**Comment by mandrigin** [comment]
@adambabik regarding where to keep it: we can move it as a part of https://github.com/status-im/status-go/pull/630

**Comment by canercidam** [comment]
@adambabik 
1) Adding now, also with a small explanation of default behaviour.
2) I can move it into `_assets/patches` if everyone is okay with that. (#630)

**Review by mandrigin — CHANGES_REQUESTED** [review]
Yeah, what @adambabik said. 
At least a comment on how to use this script and it's command-line flags would be awesome to have.

**Comment by mandrigin** [comment]
"Requested changes" so no one merges it by mistake 😅

**Comment by canercidam** [comment]
Done!

**Review by mandrigin — APPROVED** [review]

**Review by divan — APPROVED** [review]

**Comment by mandrigin** [comment]
@canercidam 👍

**Pull request merged**
