### PR TITLE
Create patch files to replicate our whisperv5 notification patches in whisperv6

### LINKED ISSUE #637: Apply notifications patch to whisperV6
# Problem

We need notifications and few changes in whisper servise that present in notifications patch.

# Implementation

Apply patch `geth-patches/0004-whisper-notifications.patch` to whisperV6. Make new patch for whisperV6 (not temporary).

# Acceptance Criteria

Status-go tests are passed.

Part of #634

### PR DESCRIPTION
**Pull request by pedropombeiro**
Migrates the Whisper v5 patches to the new baseline Whisper v6.

Closes #637

### CODE REVIEW

**Comment by dshulyak** [comment]
These whisper/notifications module looks super sketchy, I would be surprised if it actually works. Who can know more details (@adambabik @divan)? Firstly they can be implemented on status-go side simply by moving that codebase, but it looks like we can simply drop them, am I wrong?

**Comment by JekaMas** [comment]
It looks like notification module isnt used or can be moved to our code base.
The new issue to investigate that can be created. But first of all we need new fast and less resource consuming messaging.

**Review by JekaMas — APPROVED** [review]
LGTM

**Comment by adambabik** [comment]
As far as I know, all code related to Push Notifications is in status-go now. However, we have this fragment which initializes it: https://github.com/status-im/status-go/blob/develop/geth/node/node.go#L186-L192

Should we create an issue to remove it and get rid of this `notifications` package from go-ethereum? This issue should also make sure that after removal push notifications work properly.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>status-go - The Status module that consumes go-ethereum</div></blockquote>

**Comment by pedropombeiro** [comment]
Closed with 857b72e9fd5f7521bae8be235bb0255d3891ea86

**Pull request closed without merging**
