### PR TITLE
Add back notification code

### PR DESCRIPTION
**Pull request by cammellos**
Notification code was a breaking change with status-react, I have reverted it in a separate PR that has been merged, and re-enabling here, please merge only once status-react has been tested succefully and is ready to be merged.

### CODE REVIEW

**Review by Samyoul — APPROVED** [review]
I should have read your description fully before reviewing this code, it was seeming very familiar. 😆

**Comment by rasom** [comment]
@Samyoul 
There is at least one issues: notifications are not dispatch for RequestTransaction/SendTransaction and related messages.

Can you help with fixing that? If so do you prefer to open a separate pull request or to add another commit here?

**Comment by Samyoul** [comment]
> @Samyoul
> There is at least one issues: notifications are not dispatch for RequestTransaction/SendTransaction and related messages.
> 
> Can you help with fixing that? If so do you prefer to open a separate pull request or to add another commit here?

Hey @rasom , I'll create an issue for this and I'll track this separately

**Comment by Samyoul** [comment]
@rasom see for handling validated transaction notifications https://github.com/status-im/status-go/pull/2142

**Pull request merged**
