### PR TITLE
chore_: skip flaky wallet tests

### PR DESCRIPTION
**Pull request by igor-sirotin**
Issue opened here: https://github.com/status-im/status-go/issues/5601

### CODE REVIEW

**Review by osmaczko — APPROVED** [review]

**Review by ilmotta — APPROVED** [review]

**Comment by igor-sirotin** [comment]
Merged as part of https://github.com/status-im/status-go/pull/5606

**Comment by saledjenic** [comment]
@igor-sirotin this is very odd, cause running those tests locally many times didn't get any failed tests.
But I see the potential issue, there is no order of the paths within a generate route, that means if the user sends 12 USDC, but has 10 on mainnet and 10 on optimism router may take any of the following as the best route:
- route 1:
  - 10 from mainnet
  - 2 from optimism
- route 1 - variant 2:
  - 2 from optimism
  - 10 from mainnet
 
- route 2:
  - 2 from mainnet
  - 10 from optimism
- route 2, variant 2:
  - 10 from optimism
  - 2 from mainnet

so checking only the error code, not the details part of an error, or sorting paths within a route should fix this.

Will create a PR for that.

**Comment by igor-sirotin** [comment]
> running those tests locally many times didn't get any failed tests.

It did fail for me 🗿

> there is no order of the paths within a generate route

Yeah, thought of the same
Maybe we could introduce some order here? Maybe sort by increasing chain id or smth.

**Comment by saledjenic** [comment]
Addressed here https://github.com/status-im/status-go/pull/5618

**Pull request closed without merging**
