### PR TITLE
Fix/flaky test sync installation

### PR DESCRIPTION
**Pull request by qfrank**
we may get unexpected error after submit a PR to status-go:
```
[2023-04-27T02:26:45.662Z]     messenger_installations_test.go:292: 
[2023-04-27T02:26:45.662Z]          Error Trace:  /home/jenkins/workspace/status-go_prs_tests_PR-3388/protocol/messenger_installations_test.go:292
[2023-04-27T02:26:45.662Z]          Error:        Not equal: 
[2023-04-27T02:26:45.662Z]                        expected: 1
[2023-04-27T02:26:45.662Z]                        actual  : 0
[2023-04-27T02:26:45.662Z]          Test:         TestMessengerInstallationSuite/TestSyncInstallation
```
this PR should fix the error

### CODE REVIEW

**Review by ilmotta — APPROVED** [review]

**Comment by jrainville** [comment]
Seems like all PRs are failing in tests now. I think it's some sort of time out. 
I tried a PR with no changes and it still fails. https://github.com/status-im/status-go/pull/3451

There is no `FAIL:`, but I did find that there is a `timed out` after twenty minutes.

Maybe we just have too many tests now and they take more than 20 minutes and that's our hard coded limit?

**Comment by jrainville** [comment]
Yeah we have a 20m timeout 
```
go test -tags '$(BUILD_TAGS)' -timeout 20m -v -failfast $(UNIT_TEST_PACKAGES) $(gotest_extraflags)
```
Maybe it's worth upping?

**Comment by jrainville** [comment]
Hmm, but this PR succeeded in less than 10 minutes. So we do have one or multiple tests that take too much time then 
https://ci.status.im/job/status-go/job/prs/job/tests/view/change-requests/job/PR-3449/

**Comment by qfrank** [comment]
looking forward to [add per-test timeouts](https://github.com/golang/go/issues/48157)  @jrainville

**Pull request merged**
