### PR TITLE
optimize mention

### PR DESCRIPTION
**Pull request by qfrank**
- combine api `ChatMentionRecheckAtIdxs` `ChatMentionNewInputTextWithMention` into one 
- rename function
- add some comments for mention api

relate optimization for status-mobile coming soon..

### CODE REVIEW

**Review by rasom — APPROVED** [review]

**Comment by OmarBasem** [comment]
@qfrank good work!

Did you tryout that commit on status-mobile

**Comment by qfrank** [comment]
The corresponding pr for status mobile will be pushed in an hour, it was already done, afk for 1 hour ☺️ @OmarBasem

**Review by ilmotta — APPROVED** [review]
Great practice to start documenting the public endpoints @qfrank.

**Comment by qfrank** [comment]
> Great practice to start documenting the public endpoints @qfrank.

time to introduce it to desktop team 😉

**Review by OmarBasem — APPROVED** [review]

**Pull request merged**
