### PR TITLE
Remove extkeys and use github.com/status-im/extkeys instead

### PR DESCRIPTION
**Pull request by adambabik**
`github.com/status-im/status-go/extkeys` led to a circular dependency on the module level because our fork of go-ethereum required it and status-go required the go-ethereum fork.

A new repo has been created https://github.com/status-im/extkeys and `github.com/status-im/extkeys` is an independent module now.

### CODE REVIEW

**Review by gravityblast — APPROVED** [review]

**Comment by gravityblast** [comment]
@adambabik @corpetty is the new extkeys repo going to be audited?

**Comment by adambabik** [comment]
@gravityblast This is copy-and-paste without a single change but it's a good point and they should be aware. 

@corpetty can you inform them about this move, please? There is no single change compared to `github.com/status-im/status-go/extkeys` if they already reviewed it. I just copied and pasted code to another repo in order to remove dependency cycle.

**Comment by gravityblast** [comment]
@adambabik yeah I saw it's exactly the same, but I didn't know if it was already audited

**Review by pedropombeiro — APPROVED** [review]

**Comment by adambabik** [comment]
Closing this and instead I will create a submodule in `extkeys` dir.

**Pull request closed without merging**
