### PR TITLE
fix: split waku2 queries in 1d batches

### PR DESCRIPTION
**Pull request by richard-ramos**
This should reduce some lock contention in the storenodes

### CODE REVIEW

**Comment by cammellos** [comment]
@richard-ramos it would be good to make sure this is tested in nim-waku, just wondering what happens if there's many messages with the same timestamps for example etc (i.e if there are many messages at the batch boundary, how does nim-waku behaves? does it skip messages, does it duplicate messages etc), do you know if that's something we looked at?

**Review by alaibe — APPROVED** [review]

**Comment by LNSD** [comment]
Could you provide some context about which is the problem you are trying to work around with this "1-day batches" strategy?

> This should reduce some lock contention in the storenodes

What do you mean by "lock contention"? 🤔

**Comment by richard-ramos** [comment]
> Could you provide some context about which is the problem you are trying to work around with this "1-day batches" strategy?
> 
> > This should reduce some lock contention in the storenodes
> 
> What do you mean by "lock contention"? thinking

I was reading about [WAL](https://www.sqlite.org/wal.html) and [locking](https://www.sqlite.org/lockingv3.html) and saw that while WAL mode lets you have multiple readers, while a single writer writes to the wal file, there will be periodic checkpoints when the writer will need to do an exclusive lock on the DB to commit the wal file back into the database. If i understood correctly, while this happens, no new readers will be allowed, and the writer will wait until existing readers finish retrieving results

Using a smaller range of time should reduce the execution time of these queries (as well as probably reducing the memory usage as it would not have to work with 30d of data (either by using the indexes or scanning the table depending on how the execution plan decided to do the query) allowing the writer to commit the wal file faster. 

It's probably a good idea to check the execution plan in sqlite to know if this change is worth it, so in the meantime this PR should not be merged...

**Comment by richard-ramos** [comment]
I converted the PR to draft to avoid merging it by mistake :)

**Pull request closed without merging**
