### PR TITLE
fix(contact)_: fix trust status not being saved to cache when changed

### LINKED ISSUE #16392: Untrusted contract is marked as trusted if message is sent from mobile
# Bug Report

## Description

Untrasted contact became trusted after receiving message from mobile from them.

## Steps to reproduce

1. User A (desktop): add User B as contact
2. User A (desktop): mark User B untrusted
3. User B (mobile): send message to User A

#### Expected behavior
User B stays as "untrusted" on desktop

 #### Actual behavior
User B is marked as Trusted

https://github.com/user-attachments/assets/964b2f58-f1da-4843-af3f-4cdbb421eed0

### Additional Information

- Status desktop version: master 23/09/24
- Operating System: Mac Osx

### PR DESCRIPTION
**Pull request by jrainville**
Fixes https://github.com/status-im/status-desktop/issues/16392

The problem was that we were saving the trust status to the DB, but not the cache, so the next time a message got received or the contact was updated, the received contact on the client side would have an outdated `trustStatus`, since it comes from the cache.

### CODE REVIEW

**Comment by jrainville** [comment]
@igor-sirotin @friofry reminder to review please

**Review by osmaczko — APPROVED** [review]
LGTM, except diff-coverage is feeling a little left out :police_officer:

**Review by alaibe — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]

**Comment by jrainville** [comment]
> LGTM, except diff-coverage is feeling a little left out 👮

I added tests for the TrustStatus function, so it covers the actual changes I did.

I think CodeCov complains mostly about the fact that I used constants for the errors. So I'm paying for the fact that I tried to leave the code cleaner :unamused: :joy: 

Since the functions touched are mostly functions for the ID verification, I don't think it's worth investing time into improving their tests, so if it doesn't let merge, I'll ping Igor.

**Comment by igor-sirotin** [comment]
@mendelskiv93 just FYI, windows build seem to not work on this PR

**Review by friofry — COMMENTED** [review]
LGTM, sorry for the late review

**Pull request merged**
