### PR TITLE
delete imported key

### PR DESCRIPTION
**Pull request by flexsurfer**
delete imported key

### CODE REVIEW

**Comment by flexsurfer** [comment]
@Samyoul could you pls assist, i have no idea whats wrong with codeclimate and tests

**Comment by gravityblast** [comment]
shall we also pass the password to the delete method so that we can verify we are removing the right one?

**Comment by Samyoul** [comment]
Hey @flexsurfer I've had a look the codeclimate issue isn't a major problem it can be ignored. It is just an arbitrary code quality feature that checks the length of files. So this can be safely ignored.

Tests:

The test in question looks like a flaky test. It runs perfectly on your branch on my local machine.

```
[2021-08-13T17:27:00.754Z] --- FAIL: TestWakuV1 (0.60s)
[2021-08-13T17:27:00.754Z]     --- PASS: TestWakuV1/TestConfirmationEventsExtendedWithErrors (0.30s)
[2021-08-13T17:27:00.754Z]     --- PASS: TestWakuV1/TestConfirmationEventsReceived (0.30s)
[2021-08-13T17:27:00.754Z]     --- FAIL: TestWakuV1/TestConfirmationHandshakeExtension (0.00s)
[2021-08-13T17:27:00.754Z]         waku_version_test.go:154: 
[2021-08-13T17:27:00.754Z]             	Error Trace:	waku_version_test.go:154
[2021-08-13T17:27:00.754Z]             	            				waku_version_test.go:161
[2021-08-13T17:27:00.754Z]             	Error:      	Not equal: 
[2021-08-13T17:27:00.754Z]             	            	expected: true
[2021-08-13T17:27:00.754Z]             	            	actual  : false
[2021-08-13T17:27:00.754Z]             	Test:       	TestWakuV1/TestConfirmationHandshakeExtension
[2021-08-13T17:27:00.754Z] FAIL
[2021-08-13T17:27:00.754Z] FAIL	github.com/status-im/status-go/waku	9.354s
```

I've started retesting the unit tests, so if the test is flaky this should work without needing any changes to your code. Looking at your code, I don't think it could affect the test that failed.

**Review by Samyoul — APPROVED** [review]
Looks good.

**Comment by flexsurfer** [comment]
@gravityblast that's a good point, do we have a similar verification in the codebase?

**Comment by gravityblast** [comment]
@flexsurfer yeah we do it here https://github.com/status-im/status-go/blob/17d1d31b185f34c1af73d687dac9004340cb10d8/account/accounts.go#L171

**Comment by flexsurfer** [comment]
@gravityblast done

**Pull request merged**
