### PR TITLE
Upgrade to Go 1.9

### PR DESCRIPTION
**Pull request by adambabik**
Upgrade to Go 1.9. 

Go 1.9 has been released weeks ago.

Solves #337

### CODE REVIEW

**Review by themue — APPROVED** [review]
LGTM

**Comment by adambabik** [comment]
All tests pass except for `Test e2e on public network` which constantly breaks.

**Comment by JekaMas** [comment]
@adambabik Are `Test e2e on public network` fails localy too? They should pass.

**Comment by adambabik** [comment]
@JekaMas it constantly fails because of 
```
--- FAIL: TestCallContextResult (7.32s)
        Error Trace:    rpc_test.go:166
	Error:      	Should be true
	Messages:   	balance should be higher than 0
```

All other tests pass.

**Review by JekaMas — APPROVED** [review]

**Pull request merged**
