### PR TITLE
Add error to login signal

### LINKED ISSUE #1583: Signal needed when login fails
# Problem

When the user inputs the wrong password, status-go doesn't inform status-react and status-react hangs https://github.com/status-im/status-react/issues/8829

# Implementation

We need a signal from status-go that login failed

Currently I see this in the logs:
```
08-24 04:03:10.191 17362 17408 D StatusModule: clearStorageAPIs
08-24 04:03:10.209 17362 17408 D StatusModule: login
08-24 04:03:10.251 17362 17408 D StatusModule: Login result: {"error":""}
08-24 04:03:10.325 17362 17413 E GoLog   : ERROR[08-24|02:03:10.322] failed to start a node                   address=0xc91f5F264Ab6472cB88c79e533d278792Df61b19 error="file is encrypted or is not a database"
```

# Acceptance Criteria

I would propose that "node.login" signal is replaced by "login.success" and "login.failed" but I am open to suggestions

### PR DESCRIPTION
**Pull request by cammellos**
Fixes: #1583 
We add an error to login signal so that the caller can tell whether
login was successful or not

### CODE REVIEW

**Review by adambabik — APPROVED** [review]

**Comment by yenda** [comment]
@cammellos could  you rename the branch so that it doesn't include a `/` I can't build because of that

**Comment by cammellos** [comment]
@yenda you can use the hash of the commit:
`c5b387a66148247d1a4246ce70138f28c94c21b6`

**Comment by yenda** [comment]
Works I think we can merge?

**Comment by yenda** [comment]
Actually I get a "node is already running" error when I put the right password

**Comment by cammellos** [comment]
@yenda I will have a look

**Comment by yenda** [comment]
@cammellos thanks! It was my mistake though because I was checking for error not empty error, maybe it is possible to not send error at all if it is empty? Anyway my branch takes that into account now and trying to stop the node is probably good hygene

**Comment by cammellos** [comment]
@yenda sure no probs

**Comment by cammellos** [comment]
@yenda merged

**Pull request merged**
