### PR TITLE
fix env variables pointing at android ndk for gomobile

### PR DESCRIPTION
**Pull request by jakubgs**
The `NDK_GOMOBILE`  env variable is set for `jenkins` user in CI via Bash profile:
https://github.com/status-im/infra-misc/blob/ba9db5dbf543425cdc01d421dd2175330b3488fa/ansible/roles/jenkins-slave-linux/tasks/user.yml#L22-L26
Also added `disableConcurrentBuilds()` to fix clashing ports in tests run on the same host.

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
@jakubgs probably we should also get rid of `gomobile init`

**Comment by jakubgs** [comment]
```
gomobile init -ndk /opt/android-ndk-r16b
flag provided but not defined: -ndk
usage: gomobile init [-openal dir]
```
Doesn't seem to help...

**Comment by mandrigin** [comment]
@jakubgs yeah, because we don't need `gomobile init` anymore

**Comment by jakubgs** [comment]
Tests appear to be failing due to listen port clashes:
```
--- FAIL: TestPeerPoolSimulationSuite (1.06s)
    --- PASS: TestPeerPoolSimulationSuite/TestMailServerPeersDiscovery (1.03s)
    --- PASS: TestPeerPoolSimulationSuite/TestPeerPoolCacheEthV5 (0.02s)
    --- FAIL: TestPeerPoolSimulationSuite/TestSingleTopicDiscoveryWithFailoverEthV5 (0.00s)
        assertions.go:239: 
                          
	Error Trace:	peerpool_test.go:87
            
	            	
			suite.go:88
            
	Error:      	Received unexpected error:
            
	            	listen tcp 0.0.0.0:33741: bind: address already in use
        peerpool_test.go:179: Skipping due to being flaky
FAIL
FAIL	github.com/status-im/status-go/peers	1.158s
```
Maybe there's a leftover process on that host that holds it from some build. I'm not sure if that port is static or randomly selected.

**Comment by jakubgs** [comment]
Both the #2 and #3 builds failed with the same port and same test, so I guess it's not selected randomly:
```
listen tcp 0.0.0.0:33741: bind: address already in use
```
https://ci.status.im/job/status-go/job/prs/job/android/job/PR-1393/2/console

<blockquote><div><strong><a href="https://ci.status.im/job/status-go/job/prs/job/android/job/PR-1393/2/console">status-go » prs » android » PR-1393 #2 Console [Jenkins]</a></strong></div></blockquote>

**Comment by mandrigin** [comment]
@adambabik can you take a look?

**Comment by jakubgs** [comment]
And both of those tests failed on the same host: [`linux-02`](https://ci.status.im/computer/linux-02/)
```
admin@linux-02.do-ams3.ci.misc:~ % pgrep statusd
admin@linux-02.do-ams3.ci.misc:~ % echo $?
1
admin@linux-02.do-ams3.ci.misc:~ % sudo netstat -lpnt | grep 33741
admin@linux-02.do-ams3.ci.misc:~ %
```
I see no leftover processes on that host though.

**Comment by adambabik** [comment]
@jakubgs if two builds run on the same machine and that test will execute at the same time, the ports will clash. They are not selected randomly. If we continue having two builds at the same machine, I suggest fixing that test.

**Comment by jakubgs** [comment]
I've added `disableConcurrentBuilds()` to `options` as a temporary fix to clashing ports.

**Comment by jakubgs** [comment]
Seems to be working fine this way. Find with you @adambabik ?

**Review by mandrigin — APPROVED** [review]
Lgtm now

**Review by adambabik — APPROVED** [review]

**Pull request merged**
