### PR TITLE
LAN connection string

### PR DESCRIPTION
**Pull request by Samyoul**
This PR introduces the `ConnectionParams` struct, this struct is responsible for the generating and parsing the server / client connection string data. This connection string is used to ensure a server and client can communicate using a common set of connection data.

```go
type ConnectionParams struct {
	version    ConnectionParamVersion
	netIP      net.IP
	port       int
	privateKey *ecdsa.PrivateKey
	notBefore  time.Time
	serverMode ServerMode
}
```

An example of a connection string is as follows:
`2:4FHRnp:H6G:6jpbvo2ucrtrnpXXF4DQYuysh697isH9ppd2aT8uSRDh:eQUriVtGtkWhPJFeLZjF:3`

Format is byte encoded elements encoded into a base58 string, delimited by ":"

|Field Name|Type|Used to Generate|
|---|---|---|
|`version`|`int`|connection compatibility|
|`netIP`|`net.IP`|network address and root CA|
|`port`|`int`|network address|
|`privateKey`|`ecdsa.PrivateKey.D`|root CA|
|`notBefore`|`asn1.Marshal`ed `time.Time`|root CA|
|`serverMode`|`int`|connection type|

The string uses a delimiter because the `version`, `netIP`, `port` and `notBefore` fields may not be of a fixed byte length.

---

Required for #2506
Dependant on #2626

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status_go.html))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Review by bitgamma — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Review by richard-ramos — APPROVED** [review]

**Comment by churik** [comment]
Is it ready for client testing, @Samyoul ?

**Comment by anastasiyaig** [comment]
@Samyoul please rebase this one, and sorey for delay!

**Comment by Samyoul** [comment]
@anastasiyaig Ok, all rebased, sorry for my delay

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-desktop/pull/6093 will be tested here

**Pull request merged**
