### PR TITLE
Add CallPrivateRPC binding

### PR DESCRIPTION
**Pull request by adambabik**
In https://github.com/status-im/status-go/pull/815, we changed `CallRPC` binding to only allow calling whitelisted or public APIs. This PR provides `CallPrivateRPC` binding, which can call both public and private bindings but should not be used in web3.js provider implementations.

cc @rasom

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]
is it used only for admin_peers?

**Review by themue — APPROVED** [review]
Any example where `CallPrivateRPC()` is used?

**Comment by adambabik** [comment]
@dshulyak This one for sure, but there may be more. For example, we can remove `AddPeer` binding because there is `admin_addPeer`. cc @themue

**Comment by dshulyak** [comment]
@adambabik right, i initially thought that we have that binding because we don't want any dapp adding peers. but it turned out to be a bit worse than that :)

**Pull request merged**
