### PR TITLE
fix: wakuv2 failing tests 

### LINKED ISSUE #5439: Broken wakuv2 tests
# Problem

`wakuv2` package tests are broken.

image

-----

They were disabled here:
- https://github.com/status-im/status-go/pull/4237

And brought back here:
- https://github.com/status-im/status-go/pull/5437

In the meantime they got broken 😢

### PR DESCRIPTION
**Pull request by chaitanyaprem**
Closes #5439

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Review by igor-sirotin — COMMENTED** [review]
Thanks for a quick fix!
Looks like one of the tests is fixed, but the other one still feels bad 😢 

image

**Comment by chaitanyaprem** [comment]
> Thanks for a quick fix! Looks like one of the tests is fixed, but the other one still feels bad 😢
> image

Oh, this has passed locally. Odd that it failed here.

**Comment by chaitanyaprem** [comment]
Added some randomness in contentTopic used and removed peerExchangeClient config so that test uses only fleet nodes. This should make it non-flaky.
Ran 10 times locally and no failures noticed.

**Review by igor-sirotin — APPROVED** [review]
Thank you! ❤️

**Pull request merged**
