### PR TITLE
Pull all recent changes to 1.8.21 tag

### PR DESCRIPTION
**Pull request by dshulyak**
Lately there were few change to 1.8.21 tag in our fork, but they weren't pulled into status-go.

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
It still lacks a watchdog for peer shutdown.

**Comment by dshulyak** [comment]
@mandrigin i just pulled everything that was under this tag https://github.com/status-im/go-ethereum/tree/v1.8.21 . i don't see mentioned change there

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/go-ethereum">status-im/go-ethereum</a></strong></div><div>Official golang implementation of the Ethereum protocol - status-im/go-ethereum</div></blockquote>

**Comment by mandrigin** [comment]
oh, I merged it to patched/1.8; I will update the `1.8.21` too

**Comment by mandrigin** [comment]
@dshulyak I created a new tag `v1.8.21.status.1`, because I had no idea about versioning ;-P

**Comment by dshulyak** [comment]
@mandrigin i think we are trying to use same tag as a released version of ethereum, but with our patches. so i just re-created v1.8.21 using latest version of patched/1.8

**Comment by mandrigin** [comment]
@dshulyak thanks! looks good to be merged now

**Pull request merged**
