### PR TITLE
remove change.Counter logic to fix inc/dec metrics

### PR DESCRIPTION
**Pull request by corpetty**
A short summary which serves as a squashed-commit message.

A description to understand introduced changes without reading the code.

Important changes:
- [x] Something worth noting for reviewers.

Closes #

### CODE REVIEW

**Review by adambabik — APPROVED** [review]

**Comment by adambabik** [comment]
Has it been verified by running status-go locally?

**Comment by corpetty** [comment]
no it has not.

**Comment by corpetty** [comment]
conflicts with https://github.com/status-im/status-go/pull/1648, and that one should take priority.  @jakubgs is attempting to incorporate this into his.

**Comment by jakubgs** [comment]
I included this change in my PR: https://github.com/status-im/status-go/pull/1648/files#diff-9ca605189c82817624f00e8d9464da83R52

**Pull request closed without merging**
