### PR TITLE
Add new bootnodes (DO and Ukr)

### PR DESCRIPTION
**Pull request by pedropombeiro**
This tiny PR adds 3 new bootnodes (2 from DO fleet and 1 in Ukraine). List is in https://github.com/status-im/status-react/issues/4623#issuecomment-394419433

Increasing public blockchain sync time from 30m to 45m since it is not enough at the moment in Travis CI:
```
ERROR[06-05|13:56:50] syncAndStopNode: failed to sync the chain package=status-go/cmd/statusd          error="timeout during node synchronization"
WARN [06-05|13:56:50] Rolled back headers                      count=2048 header=2076672->2074624 fast=0->0 block=0->0
```

### CODE REVIEW

**Review by gravityblast — APPROVED** [review]
LGTM

**Review by adambabik — COMMENTED** [review]
LGTM 

It would be nice to comment on which servers they run. For example, the first one is `boot-01.do-ams3.eth.beta`.

**Review by adambabik — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@adambabik yeah, I was thinking the same. I'll update PR with that and then merge. Thanks!

**Comment by pedropombeiro** [comment]
@adambabik by the way, I realized that I didn't update the mainnet bootnode list! I'll add that in as well.

**Review by divan — APPROVED** [review]

**Pull request merged**
