### PR TITLE
Add test for everyone tag & fix migration order

### LINKED ISSUE #9598: Mentions and replies don't appear until app restart
# Bug Report

## Description

Big issue. If you mention or reply to someone, that person will **not** receive that before they restart the app.

Something is broken with how we handle the signal.

## Steps to reproduce

1. Have both apps open
2. send a mention or reply to account B
3. account B doesn't receive it. They will only see it if they restart

[Screencast 2023-02-20 13:43:48mention.webm](https://user-images.githubusercontent.com/11926403/220180251-fdeaebed-590f-4573-b260-f6757503b34a.webm)

### Additional Information

- Status desktop version: master `c23f4e173e22e468f32a46322da004e84f844106`
- Operating System: Ubuntu 20

### PR DESCRIPTION
**Pull request by cammellos**
A migration was added out-of-order, which meant that in clients who had already run the migration after, it would be skip. This commit re-adds the migration so it's run, tested against an empty account and one that had already migrated.

This was causing the issue with mentions and the error with activity_center_states table on some devices.

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Review by jrainville — APPROVED** [review]
LGTM

**Comment by jrainville** [comment]
I confirm that it fixes the mention and reply bug. Thanks! Fixes https://github.com/status-im/status-desktop/issues/9598

**Review by MishkaRogachev — APPROVED** [review]
Thanks!

**Review by ilmotta — APPROVED** [review]

**Pull request merged**
