### PR TITLE
feat: wallet - emoji and color

### PR DESCRIPTION
**Pull request by OmarBasem**
This PR sets customization color and emoji for the wallet account when creating a Status account

status-mobile PR: https://github.com/status-im/status-mobile/pull/17906

### CODE REVIEW

**Review by qfrank — APPROVED** [review]
LGTM

**Comment by cammellos** [comment]
tests please :)

**Comment by cammellos** [comment]
@OmarBasem one thing, is the user passing  the emoji from the client or you are just choosing a random one in the client?
If you are just choosing a random one, maybe it makes more sense to generate on status-go, the least choices the frontend makes the better, but up to you

**Comment by OmarBasem** [comment]
> @OmarBasem one thing, is the user passing the emoji from the client or you are just choosing a random one in the client? If you are just choosing a random one, maybe it makes more sense to generate on status-go, the least choices the frontend makes the better, but up to you

@cammellos The emoji is passed from the client. To generate it on status-go we would need to have all of the emojis data on status-go

**Comment by cammellos** [comment]
@OmarBasem oh I see, and I take that's something we don't have already, that's cool then, thank you

**Review by vkjr — APPROVED** [review]

**Pull request merged**
