### PR TITLE
Integrate Nimbus status-protocol-go

### PR DESCRIPTION
**Pull request by pedropombeiro**
This PR serves simply to update the vendored status-protocol-go.

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status_go.html))?

**Comment by pedropombeiro** [comment]
The tests seem to be quite brittle, it only passed the 3rd time I restarted the build.

**Comment by pedropombeiro** [comment]
Ping @adambabik and @cammellos for review, so we can get this merged.

**Review by adambabik — APPROVED** [review]

**Comment by pedropombeiro** [comment]
@adambabik Do you have any idea what is causing the linting error in https://ci.status.im/blue/organizations/jenkins/status-go%2Fprs%2Ftests/detail/PR-1666/27/pipeline/ ? Seems complete nonsense.

UPDATE: OK, seems like we were using a much older version of golangci (1.17.1) in status-go compared to what we use in status-console-client (1.19.1)

**Pull request merged**
