### PR TITLE
Add community request to response when a response handled

### PR DESCRIPTION
**Pull request by cammellos**
Adds the updated community request when a response is received.

In general, any time a piece of state is updated in the backend, that
should be propagated to the client through signals.

In this case, when a request was accepted, the client wasn't notified,
requiring them to re-fetch the accepted requests and causing
inconsistent state between status-go and client.

### CODE REVIEW

**Review by 0x-r4bbit — APPROVED** [review]
LGTM!
Would be cool if you could add some comment on why this change was done?

**Comment by cammellos** [comment]
> LGTM! Would be cool if you could add some comment on why this change was done?

sure, you mean in the PR description or you'd like me to do it in the code?

**Comment by 0x-r4bbit** [comment]
Ah, just a comment here is enough. I see what the PR is doing, but was just wondering why. I put such reasoning typically in the commit message, just to ensure people don't run into open questions.

But a comment here is enough.

**Comment by cammellos** [comment]
@0x-r4bbit good point! updated git commit & pr description

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
