### PR TITLE
fix: mitigate race conditions on community

### LINKED ISSUE #14432: Community updates are lost/erased sometimes (re-evaluation overrides it?)
# Bug Report

## Description

When Iuri adds a permission, if he then adds more permissions, there is a chance that the newest permissions will be removed/lost.

My guess of what is happening is that the member re-evaluation  starts when the first permission is created. Then, when it ends, it saves the community and publishes it. However, that re-evaluation is made on a separate thread, so it does it's own copy of the description. so at the end, if the re-evaluation takes a lot of time, there is a strong chance that it will save and publish an out of date description. In other words, if community changes were made while the re-evaluation was in progress, they will be lost.

I think the most straightforward way to fix this would be to cancel and restart the member reevaluation if `saveAndPublish` is ever called (there is a new version/clock).
Another option would be to make the reevaluation smarter and it got the community description again at the end and just applies the member permissions it calculated to it. However, this solution is more error prone, because if another permission was added that changes the way the members should be, it could cause a temporary weird state.

## Steps to reproduce

0. Have a big community with lots of channels, members, permissions and tokens
  or add some sleeps in the reevaluate method to fake a long time to evaluate
1. Add a community permission
2. Do some other updates, like adding another permission or just editing the name

Wait until the reevaluation is done. See that the changes made at step 2 were lost/overriden.

#### Expected behavior

No change is lost

#### Actual behavior

Changes are lost

### Additional Information

- Status desktop version: 2.28.0

### PR DESCRIPTION
**Pull request by osmaczko**
mitigates: status-im/status-desktop#14432

Use manager-level community locks to mitigate race conditions on communities processed by separate goroutines.

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Does this mean that while the member re-evaluation is in progress, no community update will ever work?

**Comment by osmaczko** [comment]
> Does this mean that while the member re-evaluation is in progress, no community update will ever work?

They will eventually work, albeit with a delay. This requires improvement, but it is the only timely solution I can think of right now. It will affect only the control nodes.

**Comment by jrainville** [comment]
> > Does this mean that while the member re-evaluation is in progress, no community update will ever work?
> 
> They will eventually work, albeit with a delay. This requires improvement, but it is the only timely solution I can think of right now. It will affect only the control nodes.

Ok yeah that's what I thought. If it's the only solution that doesn't require a big change, than so be it.

Just to be sure, what will it look like for the Owner in that case. Let's say the member check is in progress, if the owner updates a channel name, will it just not appear until the member check finishes? Will it freeze?

Is it no possible in Go to cancel a routine?

**Comment by osmaczko** [comment]
> Just to be sure, what will it look like for the Owner in that case. Let's say the member check is in progress, if the owner updates a channel name, will it just not appear until the member check finishes? Will it freeze?

It really depends if the API is called async or not. It seems `editChat` and `editCommunity` are not called async. In this case it will freeze, as in the attached video (I simulated the long conflicting operation to take 15secs):

https://github.com/status-im/status-go/assets/33099791/7ad44762-a235-4121-82c4-d79f330e82fa

Tbh, I think the freeze is better than edit without immediate results.

> Is it no possible in Go to cancel a routine?

We could use a cancellation point and check it explicitly in each `ReevaluateMembers`'s loop iteration, but that requires more work and extra logic to re-run the reevaluation afterwards. That's not so straightforward to do. I think we can try it afterwards if freezing turns out to be too annoying.

**Comment by jrainville** [comment]
> > Is it no possible in Go to cancel a routine?
> 
> We could use a cancellation point and check it explicitly in each ReevaluateMembers's loop iteration, but that requires more work and extra logic to re-run the reevaluation afterwards. That's not so straightforward to do. I think we can try it afterwards if freezing turns out to be too annoying.

@iurimatias how do you feel about the above as a temporary fix?

**Comment by iurimatias** [comment]
This freeze is for the admin right? I think it's fine in that case, better than the alternative

**Comment by jrainville** [comment]
> This freeze is for the admin right? I think it's fine in that case, better than the alternative

Yes, only for the control node actually.

**Review by jrainville — APPROVED** [review]
I think we can close the current issue and reopen one to create a better solution for 2.29

**Review by qfrank — APPROVED** [review]

**Pull request merged**
