### PR TITLE
Send notification when your contact invites you to group chat

### LINKED ISSUE #12330: No PN when your contact invites you to group chat
# Bug Report

## Problem 
As a user, I want to be notified if my contact invites me to group chat. 
Currently there is no push notification about invite to group chat - it just appears on home screen

#### Expected behavior
PN

#### Actual behavior
no PN

### Reproduction

1) as User A: add User B to contacts
2) as User A: put app to background
3) as User B: invite User A to group chat

### Additional Information

- Status version: 1.15 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by briansztamfater**
Sends local notification (Android) when a contact invites you to a group chat

Fixes https://github.com/status-im/status-react/issues/12330

### CODE REVIEW

**Review by bitgamma — APPROVED** [review]

**Review by Samyoul — COMMENTED** [review]
Looks good @briansztamfater is it possible to add a test or two to ensure this functionality isn't broken in the future?

**Comment by briansztamfater** [comment]
> Looks good @briansztamfater is it possible to add a test or two to ensure this functionality isn't broken in the future?

Yes for sure, will do!

**Comment by briansztamfater** [comment]
@Samyoul Done! Spent more time than expected but needed to figure out how to write tests in Go. Seems like a good way of learning the language btw :)

**Review by Samyoul — APPROVED** [review]
That looks great, thank you for the tests

**Pull request merged**
