### PR TITLE
Make chat muting only works on one chat and not to completely block PNs from a user

### PR DESCRIPTION
**Pull request by ibrkhalil**
Closes [Issue 1 and 2](https://github.com/status-im/status-mobile/pull/15128)
When User A sends a PN by messaging/mentioning User B in a community channel/group chat the PN doesn't work.
Because the way muting was working before it was done globally, Meaning if you muted a user he'll be muted in all chats, It acted as if you blocked him.
This PR decouples muting a user from the blocking behavior.

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by borismelnik — APPROVED** [review]
👍

**Comment by jakubgs** [comment]
Please don't just auto-generate branch names. This is unsightly.
```
send-notification-to-unmuted-chat-even-if-its-muted-somewhere-else
```
Also, the PR title could be fixed too.

**Comment by jakubgs** [comment]
I've pushed a new image to `notify.prod` fleet with:
```
 > make docker-image DOCKER_IMAGE_CUSTOM_TAG=deploy-notify-prod
 > docker push statusteam/status-go:deploy-notify-prod
```
Will take ~5 minutes to propagate. Lets see what happens.

**Comment by jakubgs** [comment]
For your info, you can view the fleet logs here: https://kibana.infra.status.im/goto/9232b300-1023-11ee-aaa4-85391103106b

**Review by Samyoul — APPROVED** [review]

**Pull request merged**
