### PR TITLE
fix(wallet)_: properly use amount in erc1155 transfers

### PR DESCRIPTION
**Pull request by dlipicar**
Fixes https://github.com/status-im/status-desktop/issues/16664

- ERC721 and ERC1155 are using a different mechanism than the other processors when executing the routes. ~For some reason the tx gets sent to the chain at the `BuildTransaction` stage, instead of only building the transactions for the client to sign and confirm~ This is wrong, the parameters used imply the Tx doesn't get sent to the chain, it's only generated.
- Moreover, for the particular case of ERC1155 transfers, this "extra" send mechanism didn't properly use the set Amount, which resulted in sends having Amount 0.
- This PR removes this secondary tx creation mechanism (with the abigen wrapper), reuses the data packing mechanism used for estimating gas fees, which also fixes the mentioned bug.

https://github.com/user-attachments/assets/e129b31a-4ce2-43d2-a190-9c29653bb730

### CODE REVIEW

**Review by saledjenic — COMMENTED** [review]
@dlipicar some erc721 contracts do not have `safeTransferFrom` implemented, in those cases we need to proceed with `transferFrom`, removing `sendOrBuildV2` we avoid that check.

I've tested this PR and it seems that's the only change we need to support erc721 and erc1155 (later when we add entering a custom amount on the client side we don't need any backend changes):
https://github.com/status-im/status-go/pull/6018

**Comment by friofry** [comment]
Hi @pavloburykh 

This fix changes the behaviour of `BuildTransactionV2` which is only used in (`buildTxForPath` ->`BuildTransactionsFromRoute` -> `BuildTransactionsFromRoute`)

I've checked that desktop does indeed use the `wallet_buildTransactionsFromRoute` API call. 
But mobile doesn't use this endpoint (only `wallet_buildTransaction` or `wallet_buildRawTransaction`)

So mobile is not affected by this PR (nor by https://github.com/status-im/status-go/pull/6018).

**Comment by pavloburykh** [comment]
> So mobile is not affected by this PR

@friofry thanks a lot for reviewing.

**Review by saledjenic — APPROVED** [review]

**Comment by saledjenic** [comment]
@dlipicar before merging this PR, could you merge first this one https://github.com/status-im/status-go/pull/6020
there are 2 changes:
- one that removes stickers service (not mandatory for the release, but doesn't hurt for sure, cause nothing is affected cause no processor is using it)
- second commit, if err check, that one would be nice to have in the release

**Pull request merged**
