### PR TITLE
Ran make vendor

### PR DESCRIPTION
**Pull request by Samyoul**
I've pulled from develop, ran `make vendor` and the `git checkout -b chore/make-vendor`, this file pops up, commit change, push.

Screenshot 2022-04-29 at 21 08 52

The vendor check fails... but why?

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status_go.html))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Comment by Samyoul** [comment]
CI `make vendor` log contains:

```
[2022-04-29T20:07:27.413Z] go: downloading github.com/marten-seemann/qtls-go1-16 v0.1.4
[2022-04-29T20:07:27.413Z] go: downloading github.com/marten-seemann/qtls-go1-17 v0.1.0
[2022-04-29T20:07:27.413Z] go: downloading github.com/marten-seemann/qtls-go1-18 v0.1.0-beta.1
```

**Comment by Samyoul** [comment]
Look at https://github.com/marten-seemann/qtls-go1-18/tree/v0.1.0-beta.1

Screenshot 2022-04-30 at 21 30 18

So `qtls-go1-18 v0.1.0-beta.1` does contain [generate_cert.go](https://github.com/marten-seemann/qtls-go1-18/blob/v0.1.0-beta.1/generate_cert.go) ... why does the CI fail this file?

**Comment by Samyoul** [comment]
After upgrading to go `1.18.2` this stopped, sooooo ... 🤷

**Pull request closed without merging**
