### PR TITLE
fix: start go-waku on Start() instead of New()

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Review by vitvly — APPROVED** [review]

**Comment by qoqobolo** [comment]
Hi, @richard-ramos! Can you update the go version here, please?
Thanks 🙏

**Comment by richard-ramos** [comment]
> Hi, @richard-ramos! Can you update the go version here, please? Thanks

done!

**Comment by qoqobolo** [comment]
@richard-ramos the error on login and crash are still here :(

Logs: [wrongpassword1704.log](https://github.com/status-im/status-go/files/11251134/wrongpassword1704.log)

Screenshot 2023-04-17 at 16 18 22

**Comment by richard-ramos** [comment]
Ah! but this time the err happens in a different place, compared to the initial report (https://github.com/status-im/status-mobile/issues/15653#issuecomment-1508388387)
```
04-17 16:10:48.916 24602     0 E Go      : goroutine 4165 [running, locked to thread]:
04-17 16:10:48.916 24602     0 E Go      : github.com/status-im/status-go/wakuv2.(*Waku).Stop(0x400267c6c0)
04-17 16:10:48.916 24602     0 E Go      : 	github.com/status-im/status-go/wakuv2/waku.go:1217 +0x48
```

And it happens **after** go-waku is stopped according to the code. I'll take a stab at fixing it! thank you, @qoqobolo!

**Comment by qoqobolo** [comment]
@richard-ramos caught the error again.
This time only after ~15 attempts (takes longer to reproduce this) and I was also unable to reproduce crash.
Logs are here [wrongpassword1804.log](https://github.com/status-im/status-go/files/11260624/wrongpassword1804.log)

**Comment by richard-ramos** [comment]
I couldnt identify a status-go error in the logs.  :thinking: 
@cammellos, do you see anything interesting in these logs?

**Comment by cammellos** [comment]
@qoqobolo @richard-ramos I think the logs are not capturing the whole thing, it might be just before those in the stream unfortunately

**Comment by qoqobolo** [comment]
@cammellos @richard-ramos let me know if I can provide any other useful information for investigation.
Or maybe we could merge the current fix (if I understand correctly that the original bug with `cleaning up waku-2` has been fixed and now we have smth different)?
wdyt?

**Comment by richard-ramos** [comment]
@qoqobolo IMO it sounds good. I'll open a separate issue to track the login error in case in the future we run into it and capture more information!

**Review by qoqobolo — APPROVED** [review]

**Comment by qoqobolo** [comment]
Thanks @richard-ramos!

**Pull request merged**
