### PR TITLE
add multi-account LoadAccount, ImportMnemonic, and Reset functions

### PR DESCRIPTION
**Pull request by gravityblast**
Expose multi account  `LoadAccount` , `ImportMnemonic`, and `Reset` methods.

### CODE REVIEW

**Comment by gravityblast** [comment]
@flexsurfer I added here the Load and Reset functions.
You need to call reset in case you load an account and then the user cancel the action instead of derive and store a new account.

**Comment by flexsurfer** [comment]
@gravityblast could you elaborate on why we need LoadAccount ? how can it be used?

**Comment by flexsurfer** [comment]
and what about generate ? if user generates 5 accounts, goes back and generate 5 more ? do we need to reset when he goes back ?

**Comment by gravityblast** [comment]
@flexsurfer yes I'll write everything in a readme file so that it can always be in the repo and I'll post it here

**Comment by gravityblast** [comment]
@flexsurfer 
> and what about generate ? if user generates 5 accounts, goes back and generate 5 more ? do we need to reset when he goes back ?

All the multi-account methods are used to generate derive etc, but only StoreDerived and StoreAccount are actually saving keys to the filesystem.
You can call generate as many time as you want. but if you restart the application the keys are gone, they were just in memory until you store them.
After storing them, you don't need to multi-account functions anymore, until you want to load one to derive more child keys.

**Comment by gravityblast** [comment]
you don't need to reset, but you could do it. you can just use the new 5  ids, but there will be 10 keys in memory.

**Comment by gravityblast** [comment]
@flexsurfer , I added a README file, can you check it and tell me if it makes sense please?

**Review by adambabik — APPROVED** [review]

**Pull request merged**
