### PR TITLE
fix: handle nil descriptions in communities for chat_getChats

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Review by borismelnik — APPROVED** [review]
👍

**Review by 0x-r4bbit — APPROVED** [review]
Nice and clean.

Just wondering: At this point we should always have a community description with a chat, since we're generating a `general` chat by default, no?

In which scenarios would we still run into `nil` descriptions?

**Comment by richard-ramos** [comment]
> @PascalPrecht: In which scenarios would we still run into `nil` descriptions?

If you import a community with a private key, and the mailserver you're connected to does not have the community description available, or you're not connected to a mailserver at all, a community will be created, but its description will be nil. `func New(config Config) (*Community, error)` in `protocol/communities/community.go` does not assign a default value to the description

cc: @osmaczko since he was dealing with nil descriptions in another PR too

**Comment by richard-ramos** [comment]
> At this point we should always have a community description with a chat, since we're generating a `general` chat by default, no?

Yes, but this is in case you are creating the community. If you're importing an existing community using its private key, there's no guarantee that the general chat will exist (it might have been deleted)

**Comment by 0x-r4bbit** [comment]
Thanks for clarifying!

**Comment by anastasiyaig** [comment]
https://github.com/status-im/status-desktop/pull/5918 is in testing now for this @churik

**Comment by elina2015** [comment]
Tested in https://ethstatus.testrail.net/index.php?/runs/view/9347&group_by=tests:status_id&group_order=asc

**Pull request merged**
