### PR TITLE
Storing emoji values for Custom Emoji Thumbnails for Community Channels

### PR DESCRIPTION
**Pull request by Parveshdhull**
This PR stores emoji values which are required for creating custom emoji thumbnails

## status-react PR:
https://github.com/status-im/status-react/pull/12594

### CODE REVIEW

**Comment by richard-ramos** [comment]
It seems that the protobuf library was updated in this PR. Would it be possible to do so in a separate PR?
Also, the build failing might be fixed by executing `make vendor` to update the dependencies inside the `vendor/` folder

**Comment by Parveshdhull** [comment]
> It seems that the protobuf library was updated in this PR. Would it be possible to do so in a separate PR?
> Also, the build failing might be fixed by executing `make vendor` to update the dependencies inside the `vendor/` folder

Thanks, @richard-ramos, `make vendor` fixed the build issue. Also, I made separate PR for updating the protobuf library👍

**Review by Samyoul — COMMENTED** [review]
Hey @Parveshdhull thank you for your work on this PR. Can I ask what is the desired process flow you want to implement with these changes?

**Comment by Parveshdhull** [comment]
> Hey @Parveshdhull thank you for your work on this PR. Can I ask what is the desired process flow you want to implement with these changes?

Hi @Samyoul,
I want to store emoji values for generating emoji thumbnails for community channels.

Currently, channels only storing color values and thumbnail is being created with the help of the first alphabet of the channel name. Now It will store an extra field(emoji) and thumbnail will be created with the help of both(background color and emoji).

Issue: https://github.com/status-im/status-react/issues/12375
Status-React PR: https://github.com/status-im/status-react/pull/12594
Thanks

PS: I will update this PR too after running `make setup`  👍 https://github.com/status-im/status-go/pull/2368

**Review by cammellos — APPROVED** [review]

**Pull request merged**
