### PR TITLE
Bump version to 0.23.0-beta.8

### PR DESCRIPTION
**Pull request by flexsurfer**
Bump version to 0.23.0-beta.8

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Review by pedropombeiro — APPROVED** [review]

**Comment by jakubgs** [comment]
Let me check that android build failure. I remember seeing this before.
```
+ make statusgo-android
Building status-go for Android...
gomobile: open build/bin/statusgo.aar: no such file or directory
Makefile:114: recipe for target 'statusgo-android' failed
make: *** [statusgo-android] Error 1
```

**Comment by jakubgs** [comment]
Interesting, so we call `make statusgo-android` which calls:
https://github.com/status-im/status-go/blob/cbe50f557c4ce76e75d7170e64323ca1c8814bb9/Makefile#L116
But there is no such folder as `build/bin`:
```bash
admin@linux-04.do-ams3.ci.misc:~ % cd /home/jenkins/workspace/status-go_prs_android_PR-1405
admin@linux-04.do-ams3.ci.misc:status-go_prs_android_PR-1405 % cd src/github.com/status-im/status-go
admin@linux-04.do-ams3.ci.misc:status-go % ls -l build/bin
ls: cannot access 'build/bin': No such file or directory
admin@linux-04.do-ams3.ci.misc:status-go % ls -l build
ls: cannot access 'build': No such file or directory
admin@linux-04.do-ams3.ci.misc:status-go % ls -l build
```

**Comment by jakubgs** [comment]
It appears that the `Makefile` assumes that `build/bin` will exist, even though it's not part of the repo, and is created automatically by targets like `statusgo`.

Either we add an `mkdir` somehwere, or we add a `build/bin/.gitkeep` file.

**Comment by jakubgs** [comment]
I merged #1406, you can try rebasing to see if it will pass this time, but it seems pointless for a version bump so just merge as is if you want.

**Comment by jakubgs** [comment]
Started a release build:
https://ci.status.im/job/status-go/job/parallel/367/

**Pull request merged**
