### PR TITLE
Nuke jail package

### PR DESCRIPTION
**Pull request by divan**
Jail stands for JS Jailed execution environment. We used it historically to run some console JS code inside isolated interpreter.  We used otto VM interpreter, which is not concurrently safe, and generally this package has always been a hack.

Now, it's not used by status-react anymore, so we can safely delete it.
Which is cool.

Note, `otto` package (github.com/robertkrimen/otto) is still in the vendor list, because it's imported in a few more places in the go-ethereum code. We need to fix `dep` pruning to fix this (and shave yak).

+15 −7,512 :)

### CODE REVIEW

**Review by adambabik — COMMENTED** [review]
Can we remove `github.com/robertkrimen/otto` from `vendor/`?

**Comment by divan** [comment]
> Can we remove github.com/robertkrimen/otto from vendor/?

Not yet. I mentioned it in PR description:

> Note, otto package (github.com/robertkrimen/otto) is still in the vendor list, because it's imported in a few more places in the go-ethereum code. We need to fix dep pruning to fix this (and shave yak).

**Comment by divan** [comment]
That's strange, after investigating CI checks and running `make dep-ensure` again, it doesn't want `otto` anymore, and seems like it can be safely deleted.

**Review by dshulyak — APPROVED** [review]

**Comment by dshulyak** [comment]
> That's strange, after investigating CI checks and running make dep-ensure again, it doesn't want otto anymore, and seems like it can be safely deleted.

as i understand if we don't import code that imports otto then this dependency won't be collected by `dep` tool, even if we don't prune unused modules. but for example, if later we will try to import those modules - then we will get a compilation error and we will have to re-run `dep ensure`

**Review by adambabik — APPROVED** [review]

**Comment by divan** [comment]
@dshulyak right, but when I ran `make dep-ensure` for the first time, it left out otto. I checked manually, and otto was imported somewhere from go-ethereum (console and some more packages), thus I decided that it's still used. Anyway, it's good now.

**Pull request merged**
