### PR TITLE
Upgrade to geth 1.8.11

### LINKED ISSUE #1033: upgrade to go-ethereum 1.8.11
# Problem

Since `go-ethereum` 1.8.11 [has been released](https://github.com/ethereum/go-ethereum/releases/tag/v1.8.11) in the last days, we should update it in our dependencies.

# Implementation

Investigate changes in the new version of `go-ethereum` and check that all our patches can be applied without problems.

# Acceptance Criteria

All patches can be applied and all tests run succesfully.

### PR DESCRIPTION
**Pull request by pedropombeiro**
> Geth v1.8.11 (Streamline) is our biweekly maintenance release, focusing mainly on performance. Overall this release is ~28% lighter on disk IO and ~23% faster on block processing

Important changes:
- [x] Replaced deprecated `common.Hex` with `hexutil.Encode`.
- [x] Removed upstreamed `0010-geth-17-fix-npe-in-filter-system.patch`.
- [x] Removed upstreamed `0020-discv5-metrics.patch`.
- [x] Removed upstreamed `0026-ethdb-error-deadlock.patch`.
- [x] Updated goleveldb to same version used by geth 1.8.11.
- [x] Updated `PublicTransactionPoolAPI.GasPrice` return type to match type in internal geth interface.

Closes #1033

### CODE REVIEW

**Comment by pedropombeiro** [comment]
Just noticed that `0026-ethdb-error-deadlock.patch` may not be needed or might be simplified given the changes made upstream, looking into this.

**Comment by pedropombeiro** [comment]
Confirmed that the upstream changes do the same thing as `0026-ethdb-error-deadlock.patch`

**Review by adriacidre — APPROVED** [review]
Cool stuff

**Review by adambabik — APPROVED** [review]
Great work!

**Pull request merged**
