### PR TITLE
chore_: drop wakuv2 fleets, use waku fleets

### PR DESCRIPTION
**Pull request by yakimant**
See https://github.com/status-im/infra-nim-waku/issues/91 for details

Mostly done automatically. Some parts manually.

### CODE REVIEW

**Comment by yakimant** [comment]
@richard-ramos, @cammellos, please have a look. Am I doing anything stupid?
Also, like I need to regenerate this:
https://github.com/status-im/status-go/blob/38183ab33534a27a76dea1a80b9248ba4c384bcb/static/bindata.go#L271-L309

**Comment by richard-ramos** [comment]
Yes, to regenerate that file:
```
cd static
go generate
```

**Comment by yakimant** [comment]
Hm, lint is failing:
```
[2024-03-19T14:48:28.423Z] params/cluster.go:5: File is not `goimports`-ed with -local github.com/ethereum/go-ethereum,github.com/status-im/status-go,github.com/waku-org/go-waku (goimports)
[2024-03-19T14:48:28.423Z] 	FleetUndefined    = ""
[2024-03-19T14:48:28.423Z] 	FleetProd         = "eth.prod"
[2024-03-19T14:48:28.423Z] 	FleetStaging      = "eth.staging"
[2024-03-19T14:48:28.423Z] 	FleetTest         = "eth.test"
[2024-03-19T14:48:28.423Z] 	FleetWakuSandbox  = "waku.sandbox"
[2024-03-19T14:48:28.423Z] 	FleetWakuTest     = "waku.test"
[2024-03-19T14:48:28.423Z] 	FleetStatusTest   = "status.test"
[2024-03-19T14:48:28.423Z] 	FleetStatusProd   = "status.prod"
[2024-03-19T14:48:28.423Z] 	FleetShardsTest   = "shards.test"
[2024-03-19T14:48:28.423Z] make: *** [Makefile:357: lint] Error 1
```

@richard-ramos, can you please help?

**Comment by yakimant** [comment]
Amazing lint error, it appeared - I should just remov one formatting space:
```
-       FleetUndefined    = ""
-       FleetProd         = "eth.prod"
-       FleetStaging      = "eth.staging"
-       FleetTest         = "eth.test"
-       FleetWakuSandbox  = "waku.sandbox"
-       FleetWakuTest     = "waku.test"
-       FleetStatusTest   = "status.test"
-       FleetStatusProd   = "status.prod"
-       FleetShardsTest   = "shards.test"
+       FleetUndefined   = ""
+       FleetProd        = "eth.prod"
+       FleetStaging     = "eth.staging"
+       FleetTest        = "eth.test"
+       FleetWakuSandbox = "waku.sandbox"
+       FleetWakuTest    = "waku.test"
+       FleetStatusTest  = "status.test"
+       FleetStatusProd  = "status.prod"
+       FleetShardsTest  = "shards.test"
```

`golangci-lint run --fix` helped to discover

**Review by igor-sirotin — APPROVED** [review]
looks good to me, but better wait for @richard-ramos super-eye review 🙂

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
