### PR TITLE
[WIP] add mailserver-tools command

### PR DESCRIPTION
**Pull request by adambabik**
`mailserver-tools` has a command `count` which returns a number of envelopes for a given topic.

We want to have a capability of verifying how new private chats topic splitting works.

### CODE REVIEW

**Comment by adambabik** [comment]
The idea how to collect envelope counts per topic is to run this tool every e.g. an hour and store the result in Prometheus, for example. However, as it will be a short lived session, we need Prometheus Push Gateway to do that. @jakubgs can we run https://github.com/prometheus/pushgateway along our Prometheus instances?

**Review by mandrigin — APPROVED** [review]

**Comment by jakubgs** [comment]
>can we run https://github.com/prometheus/pushgateway along our Prometheus instances?

@adambabik I guess we could do that, but why can't we use the normal pull way of getting all our metrics into Prometheus? Is it because you didn't make this tool as a service that could host a `/metrics` endpoint?

If that's the case than that's hardly an issue. It could be as simple as a `cron` script that generate a `/var/www/mailsever-envelopes/metrics` text file in Prometheus format that would be hosted by Nginx. Or do you have some other reason for not wanting to do that?

**Comment by adambabik** [comment]
@jakubgs yeah, I didn't want to run it as a service all the time because there is no reason to do that.

I can work with generating metrics into a file if that's easier to consumer by Prometheus.

**Comment by jakubgs** [comment]
As long as the tool returns a usable number, I can just wrap it in a bash script that will format it for Prometheus. No issue.

**Comment by jakubgs** [comment]
What is the status of this? Is this on hold until we figure out the decision on the protocol breaking changes?

**Comment by adambabik** [comment]
@jakubgs yes, when the implementation for partitioned topics is confirmed, this will be updated.

**Comment by jakubgs** [comment]
I don't think this is stale.

**Comment by jakubgs** [comment]
@adambabik is this still relevant?

**Comment by adambabik** [comment]
Nope, it's already changed.

**Pull request closed without merging**
