### PR TITLE
Beta/refactor logging #221

### PR DESCRIPTION
**Pull request by MarinX**

### CODE REVIEW

**Comment by tiabc** [comment]
A few questions:
1. Can we avoid using global variables and `init` package function? I'm strictly against that.
2. Can we make our log package even more thin leaving only functions which are absolutely necessary? For example, I'd like to wrap `go-ethereum` logger and leave its configuration (including log level) inside it. Absolutely thin logger adding only our prefix. What do you think?

**Comment by MarinX** [comment]
1. Yes, that would be great for me also. I used the guide from common.logger package and this is why.
2. Thin yes, but we will need to add space to implement log-rotate, separate log file and silent the go-ethereum logs.

**Comment by MarinX** [comment]
I refactor the log package to be thin as possible without breaking any other internal packages.
- This package uses 1 global instance for logging.
- No configuration
- Prefix geth=StatusIM

**Comment by MarinX** [comment]
Also, I merged develop into this branch

**Comment by MarinX** [comment]
Hi @rgeraldes , 
Fixed and changed by the feedback you provided.

**Comment by tiabc** [comment]
@MarinX, please, open this pull request against `develop`, `bug-whisper-on-geth1.6.1` is not used any more. Also, move this branch to `status-go` according to https://hackmd.io/s/rJ8VauV8b

**Comment by MarinX** [comment]
Creating new PR, closing this one.

**Pull request closed without merging**
