### PR TITLE
chore: bump protobuf dependency

### LINKED ISSUE #3501: Memory leak in Waku v2 implementation
# Problem
The [SpiffWorkflow fleets](https://github.com/status-im/infra-spiff-workflow) are currently using a `status-go` node speaking Waku v2 to send notifications about ongoing processes. It's using the dedicated [`cmd/spiff-workflow`](https://github.com/status-im/status-go/tree/develop/cmd/spiff-workflow) command in a Docker container. We have discovered a memory growth issue that can affect other containers on the hosts. Here's a pattern for 20 days:

image

There's a clear growth trend that gets interrupted by our daily container restarts introduced as a hack fix:
https://github.com/status-im/infra-spiff-workflow/blob/master/ansible/roles/spiff-workflow/tasks/hacks.yml

### PR DESCRIPTION
**Pull request by richard-ramos**
In https://github.com/status-im/status-go/issues/3501 we found out that unmarshalling WakuMessages protobuffers consume a lot of memory. In this PR, the protobuf dependency is updated to their latest commit since it includes a couple of changes that reduce the number of allocations and seems like a good start to figure out if we have a memory leak or if it's something that was already fixed.

This PR builds on top of https://github.com/status-im/status-go/pull/3497 and may fix https://github.com/status-im/status-go/issues/3501

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
Thank you.

**Comment by richard-ramos** [comment]
Linter is complaining. Looks like upgrading the protobuf version is not as straightfwd as I thought

**Comment by richard-ramos** [comment]
Let's see if the latest commit works!

**Review by jrainville — APPROVED** [review]
This looks like it was mind numbing work lol.
Good job

**Comment by richard-ramos** [comment]
meh... getting this PR to work it's too complicated. I'll update the dependency only in go-waku

**Pull request closed without merging**
