### PR TITLE
Added mixed case address to the `Account` struct

### PR DESCRIPTION
**Pull request by saledjenic**
This PR adds mixed case address to the response for `GetAccounts` and `GetAccountByAddress `

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Comment by cammellos** [comment]
@saledjenic you might have to rebase to latest develop, since it fails with linting error because of 1.18

**Comment by saledjenic** [comment]
> @saledjenic you might have to rebase to latest develop, since it fails with linting error because of 1.18

done, thanks

**Review by alaibe — APPROVED** [review]

**Comment by saledjenic** [comment]
@cammellos @richard-ramos I guess that the test issues are not caused by changes done in this PR, but I've tried to fix them, you can check in my second commit what changes in regards of tests I did, but again tests failed. I am not sure how to fix tests issues at this moment, please help.

**Comment by 0x-r4bbit** [comment]
@saledjenic I'm running into the same test issue in #2668 
For some reason, both `Chat` objects in the response of `JoinCommunity` have a `Name` of `general`, while only the first one should have that.

It's unclear to me why/how that happens.

**Pull request merged**
