### PR TITLE
Use the same boot & static nodes for Rinkeby as in Mainnet.

### PR DESCRIPTION
**Pull request by mandrigin**
ETHIndia and other conference events requires users to be on Rinkeby, hence the users needs to be
able to communicate between Rinkeby/Mainnet.

We used to keep Rinkeby separate, but this commit changes it.

### CODE REVIEW

**Review by adambabik — APPROVED** [review]
LGTM but I would also remove `- stage: Test e2e on public network` from Travis CI. This was a reason we were keeping a separate Rinkeby Cluster.

**Comment by mandrigin** [comment]
@adambabik but with multi-fleet support, can we fix it more elegantly?

**Comment by adambabik** [comment]
Yes we can but it's a separate issue. This test in Travis does not work anyway because Rinkeby can't be synced. I would (1) remove it, (2) create another issue to bring e2e tests on a public network back (maybe as a separate Jenkins job instead of running it in Travis).

**Comment by mandrigin** [comment]
@adambabik frankly, I would remove Travis whatsoever. Our Jenkins runners are much more powerful and there are far more of them.

**Comment by adambabik** [comment]
That's fine as well.

**Comment by mandrigin** [comment]
@adambabik did that (removed the step of public e2e)

**Pull request merged**
