### PR TITLE
chore_: bump go-waku

### PR DESCRIPTION
**Pull request by kaichaosun**
Bump go-waku for store hash query.

Important changes:
- [x] make `isFilterSubAlive` empty before filter manager completes.

### CODE REVIEW

**Review by chaitanyaprem — APPROVED** [review]
We should let everyone know that Filter won't work once we merge this PR.
Maybe @cammellos can confirm if this is ok.

**Comment by cammellos** [comment]
@kaichaosun @chaitanyaprem filter is currently not really working for us, so in theory won't break anything, but what is the plan exactly for filter and lightpush then? cc @vitvly

**Comment by vitvly** [comment]
There's another issue: https://github.com/status-im/status-go/issues/5262 (sometimes filter subscribes are not executed due to node not being up yet).

**Comment by chaitanyaprem** [comment]
> @kaichaosun @chaitanyaprem filter is currently not really working for us, so in theory won't break anything, but what is the plan exactly for filter and lightpush then? cc @vitvly

I am currently dogfooding new filter changes as per https://github.com/status-im/status-go/pull/4665/. 

As @vitvly mentioned above once #5262 is addressed, we need to do further dogfooding post which filter should become functional again :)

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
