### PR TITLE
chore: `make generate` with nix-shell

### PR DESCRIPTION
**Pull request by igor-sirotin**
Just run a `make generate` from nix shell to regenerate all files. No source file changes here.
All devs should use [nix-shell](https://nixos.org/download#nix-install-macos) locally to generate files. Or even better: [move generation to CI](https://github.com/status-im/status-go/issues/4191) 🙂

### CODE REVIEW

**Review by cammellos — APPROVED** [review]

**Review by MishkaRogachev — APPROVED** [review]
Thanks!

**Comment by jakubgs** [comment]
Yes, we really need to remove those, add them to `gitignore` and just generate them via Nix during CI builds.

**Comment by igor-sirotin** [comment]
> Yes, we really need to remove those, add them to `gitignore` and just generate them via Nix during CI builds.

@jakubgs afaik, this is currently blocked by CI, is this correct? That we're changing the builds somehow and after that it will be easy to move the generation to CI.

**Comment by jakubgs** [comment]
It's not blocked, it's just "nice-to-have" so it's low on priorities list compared to the shitload of other things that we have to do.

We will get to it.

**Pull request merged**
