### PR TITLE
fix(dapps)_: fix bugs and expose wallet_GetWalletConnectActiveSessions API

### PR DESCRIPTION
**Pull request by stefandunca**
### Updates [#15189](https://github.com/status-im/status-desktop/issues/15189)

Required by https://github.com/status-im/status-desktop/pull/15322

Changes

- `HEAD` fix(dapps)_: fix session identity
  - The pairing topic was used instead the topic for the session identity which caused session management issues.
-  `HEAD~1` fix(dapps)_: fix JSON marshaling for `walletconnect.DBSession`
- `HEAD~2` feat(dapps)_: expose `wallet_GetWalletConnectActiveSessions` API

### CODE REVIEW

**Review by kounkou — APPROVED** [review]
Just need to improve coverage I guess... Good luck

**Review by alwx — APPROVED** [review]

**Comment by stefandunca** [comment]
image

@igor-sirotin all the added lines are green in my test coverage could you please help me understand why the 20% coverage?

**Comment by igor-sirotin** [comment]
> @igor-sirotin all the added lines are green in my test coverage

Well this is not correct 🙂 

This is the only line that's covered:
image

These are not covered:
image

This remained "not affecting the test coverage":
image

The problem here is that it doesn't make sense to write tests for `services/wallet/api.go`.
I'm aware of this problem and will take care of it soon.

Meanwhile we can force-merge it @cammellos

**Comment by stefandunca** [comment]
> Well this is not correct 🙂

Indeed, I missed that I have to be logged in the coverage extension to have the extra thick green/red bar.

> The problem here is that it doesn't make sense to write tests for `services/wallet/api.go`. I'm aware of this problem and will take care of it soon.

After logging in I figure out and wrote a test for it. Please remove it in your PR when fixing it.

**Pull request merged**
