### PR TITLE
Save transfer for every account that is being watched

### LINKED ISSUE #1584: ETHDownloader stores only one transfer per transaction, even if it transfer is related to multiple watched accounts
@dshulyak actually I think I found an issue, seems like when I send a transaction from one account to the other, I only receive a transfer for one of the account (the :wallet true one) and not the other. It is fine for token transfers but not for eth

_Originally posted by @yenda in https://github.com/status-im/status-go/pull/1569#issuecomment-524564547_

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/status-im/status-go/issues/1584

### CODE REVIEW

**Comment by yenda** [comment]
I still don't see the transaction but I think it is because I need https://github.com/status-im/status-go/pull/1569 as well for that to work?

**Comment by dshulyak** [comment]
@yenda are you transacting between existing and new address? or between two addresses that were added before login?

**Review by yenda — APPROVED** [review]
@dshulyak fixes my issue, can be merged from a functional pov

**Comment by jakubgs** [comment]
```
+ go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags  -- github.com/status-im/status-go/mobile]: exit status 2: # runtime/cgo
gcc_android.c:6:10: fatal error: android/log.h: No such file or directory
 #include <android/log.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

Makefile:93: recipe for target 'statusgo-android' failed
make: *** [statusgo-android] Error 1
```
Seems like something is missing, but what? Maybe Android SDK?
```
 $ ansible ci-slave-linux -a 'find /usr/lib/android-sdk -name log.h'

linux-03.do-ams3.ci.misc | CHANGED | rc=0 >>


linux-05.do-ams3.ci.misc | CHANGED | rc=0 >>
/usr/lib/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/log.h
/usr/lib/android-sdk/ndk-bundle/sources/third_party/shaderc/third_party/spirv-tools/source/opt/log.h
/usr/lib/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/utils/google-benchmark/src/log.h
/usr/lib/android-sdk/ndk-bundle/sysroot/usr/include/android/log.h

linux-01.do-ams3.ci.misc | CHANGED | rc=0 >>
/usr/lib/android-sdk/ndk-bundle/sysroot/usr/include/android/log.h
/usr/lib/android-sdk/ndk-bundle/sources/third_party/shaderc/third_party/spirv-tools/source/opt/log.h
/usr/lib/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/utils/google-benchmark/src/log.h
/usr/lib/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/log.h

linux-04.do-ams3.ci.misc | CHANGED | rc=0 >>
/usr/lib/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/utils/google-benchmark/src/log.h
/usr/lib/android-sdk/ndk-bundle/sources/third_party/shaderc/third_party/spirv-tools/source/opt/log.h
/usr/lib/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/log.h
/usr/lib/android-sdk/ndk-bundle/sysroot/usr/include/android/log.h

linux-02.do-ams3.ci.misc | CHANGED | rc=0 >>
/usr/lib/android-sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/utils/google-benchmark/src/log.h
/usr/lib/android-sdk/ndk-bundle/sources/third_party/shaderc/third_party/spirv-tools/source/opt/log.h
/usr/lib/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/android/log.h
/usr/lib/android-sdk/ndk-bundle/sysroot/usr/include/android/log.h
```
Interestingly enough the `android/log.h` files are missing from `linux-03`, but all builds failed in this PR failed on `linux-02`, so that makes no fucking sense.

**Comment by yenda** [comment]
@jakubgs but this is not related to the PR right? Could someone merge this PR so that I can merge the status-react PR that depends on it?

**Comment by jakubgs** [comment]
This seems to be a `gomobile` issue - https://github.com/golang/go/issues/33859 - submitted yesterday.

**Comment by jakubgs** [comment]
>but this is not related to the PR right? Could someone merge this PR so that I can merge the status-react PR that depends on it?

No, it's not related to the PR, I see no issue with merging it.

**Comment by yenda** [comment]
@adambabik can you merge this?

**Pull request merged**
