### PR TITLE
Update go-ethereum to v1.9.5-status.9

### LINKED ISSUE #1896: MultiAccountStoreDerived should return an error when account already stored
# Problem

When we're trying to store existing account with `MultiAccountStoreAccount` it returns an error, `MultiAccountStoreDerived` should work the same and returns an error, currently, it rewrites account with the new password

### PR DESCRIPTION
**Pull request by adambabik**
Closes #1896

### CODE REVIEW

**Comment by adambabik** [comment]
@flexsurfer let us know if this works so that I can merge please.

**Review by flexsurfer — APPROVED** [review]

**Review by gravityblast — APPROVED** [review]

**Comment by flexsurfer** [comment]
@gravityblast still no error

**Comment by flexsurfer** [comment]
@adambabik thanks, tested , it works, can be merged

**Comment by flexsurfer** [comment]
could you pls bump version so i can use it ?

**Pull request merged**
