### PR TITLE
Bump version to 0.19.0-beta.6

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by dshulyak** [comment]
@adambabik I am not sure if we need this bump in develop. release/0.19 missing one commit from develop. so we don't need to merge this one, right?

**Comment by adambabik** [comment]
@dshulyak I guess the situation is that there was a PR merged into the develop branch and you would like to release it as `0.19.0-beta.6`. Then switch to `release/0.19`, do `git merge develop --ff-only`, bump `VERSION` like here and push to `relesae/0.19`. Go to Jenkins and trigger parallel job checking "Release" and using `relesae/0.19` branch. Also, merge back the bump commit back to `develop` so that they are even.

**Comment by dshulyak** [comment]
@adambabik not exactly. there were two PRs merged into develop. one is not compatible with current status-react. so i basically cherry-picked hotfix that is compatible with current status-react on top of release/0.19 and created a new release (0.19.0-beta.6).

**Comment by dshulyak** [comment]
I already created release on top of the release/0.19 branch. I am just asking if I need to bump version in develop, for consistency. Looks like that i don't, but just to be sure...

**Comment by adambabik** [comment]
@dshulyak ah I see. Ok, https://github.com/status-im/status-go/tree/release/0.19 looks great. But if our `develop` has a backward incompatible change, we should bump `VERSION` in `develop` to `0.20.0-beta.0` so that if someone will make a release from `develop`, it will be a next version indicating this fact.

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/status-im/status-go">status-im/status-go</a></strong></div><div>The Status module that consumes go-ethereum. Contribute to status-im/status-go development by creating an account on GitHub.</div></blockquote>

**Comment by adambabik** [comment]
I pushed it to develop https://github.com/status-im/status-go/commit/6e88828d76d3020ed84de2732547327ed4a4d8d4.

**Pull request closed without merging**
