### PR TITLE
fix: statusd

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]

**Comment by jakubgs** [comment]
These tests are totally fucked aren't they?

**Comment by jakubgs** [comment]
I tested it on a `notify.prod` host and it appears to work:
```
admin@node-01.gc-us-central1-a.notify.prod:/docker/status-go % d
CONTAINER ID   NAMES            IMAGE                                  CREATED         STATUS
c7835aa677df   status-go-node   statusteam/status-go:v0.132.0-d98887   5 minutes ago   Up About a minute (healthy)
44be15fca7f7   gorush           appleboy/gorush:1.16.0-linux-amd64     5 weeks ago     Up 7 days (healthy)
```
But I'm getting LOTS of errors like this:
```
ERROR[02-24|09:14:51.923] failed to extract content topic from message topic=/railgun/v2/0/1/fees/json err="invalid content topic format"
ERROR[02-24|09:14:51.974] failed to extract content topic from message topic=/railgun/v2/0/80001/fees/json err="invalid content topic format"
ERROR[02-24|09:14:51.982] failed to extract content topic from message topic=/railgun/v2/0/5/fees/json err="invalid content topic format"
ERROR[02-24|09:14:51.987] failed to extract content topic from message topic=/railgun/v2/0/56/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.059] failed to extract content topic from message topic=/railgun/v2/0/421613/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.177] failed to extract content topic from message topic=/railgun/v2/0/137/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.841] failed to extract content topic from message topic=/railgun/v2/0/5/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.844] failed to extract content topic from message topic=/railgun/v2/0/421613/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.865] failed to extract content topic from message topic=/railgun/v2/0/56/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.896] failed to extract content topic from message topic=/railgun/v2/0/1/fees/json err="invalid content topic format"
ERROR[02-24|09:14:52.960] failed to extract content topic from message topic=/railgun/v2/0/137/fees/json err="invalid content topic format"
ERROR[02-24|09:14:53.079] failed to extract content topic from message topic=/railgun/v2/0/42161/fees/json err="invalid content topic format"
```
But that's unrelated.

**Comment by jakubgs** [comment]
Actually, it is still crashing:
```
2023-02-24T09:17:28.637Z#011ERROR#011protocol/messenger_auto_message.go:52#011[auto message] failed to send message#011{"error": "Chat not found", "errorVerbose": "Chat not found\ngithub.com/status-im/status-go/protocol.(*Messenger).sendChatMessage\n\t/go/src/github.com/status-im/status-go/protocol/messenger.go:1991\ngithub.com/status-im/status-go/protocol.(*Messenger).SendChatMessage\n\t/go/src/github.com/status-im/status-go/protocol/messenger.go:1927\ngithub.com/status-im/status-go/protocol.(*Messenger).startAutoMessageLoop.func1\n\t/go/src/github.com/status-im/status-go/protocol/messenger_auto_message.go:50\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
github.com/status-im/status-go/protocol.(*Messenger).startAutoMessageLoop.func1
#011/go/src/github.com/status-im/status-go/protocol/messenger_auto_message.go:52
2023-02-24T09:17:28.637Z#011DEBUG#011protocol/messenger_backup.go:65#011backing up data
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1b540e5]
goroutine 362 [running]:
github.com/status-im/status-go/protocol.(*Messenger).backupProfile(0xc001637680, {0x50ce06?, 0xc00516cd01?}, 0x18682b692bd)
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:314 +0xe5
github.com/status-im/status-go/protocol.(*Messenger).BackupData(0xc001637680, {0x2aaa300, 0xc003aa7a40})
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:88 +0xe5
github.com/status-im/status-go/protocol.(*Messenger).startBackupLoop.func1()
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:69 +0x225
created by github.com/status-im/status-go/protocol.(*Messenger).startBackupLoop
#011/go/src/github.com/status-im/status-go/protocol/messenger_backup.go:36 +0x8a
```
But that's also something different.

**Comment by richard-ramos** [comment]
Found another issue:
```
goroutine 296 [running]:
github.com/status-im/status-go/wakuv2/common.(*ReceivedMessage).Hash(...)
	/home/richard/status/status-go/wakuv2/common/message.go:171
github.com/status-im/status-go/wakuv2.(*Waku).OnNewEnvelopes(0xc0000d4e00, 0xc00265dec0?, 0xc000130000?)
	/home/richard/status/status-go/wakuv2/waku.go:1240 +0x80
github.com/status-im/status-go/wakuv2.(*Waku).runRelayMsgLoop(0xc0000d4e00)
	/home/richard/status/status-go/wakuv2/waku.go:698 +0x1fd
created by github.com/status-im/status-go/wakuv2.New
	/home/richard/status/status-go/wakuv2/waku.go:379 +0x1c6d

```

**Comment by richard-ramos** [comment]
nvm, i had introduced it in last commit. It's fixed now

**Review by jakubgs — APPROVED** [review]

**Review by alaibe — APPROVED** [review]

**Comment by jakubgs** [comment]
Built a Docker image: `statusteam/status-go:v0.132.2-4fd4be`
https://ci.infra.status.im/job/status-go/job/manual/2933/

**Comment by jakubgs** [comment]
Thanks for the fixes man.

**Pull request merged**
