### PR TITLE
add missing ENTRYPOINT for status-go image

### PR DESCRIPTION
**Pull request by jakubgs**
Small fix for our status-go image. Adding an `ENTRYPOINT` of `/usr/local/bin/statusd` and some labels for clarity.

### CODE REVIEW

**Review by gravityblast — APPROVED** [review]
LGTM

**Review by divan — APPROVED** [review]

**Comment by adriacidre** [comment]
Restarted this build and opened [an issue](https://github.com/status-im/status-go/issues/1085) for `TestShhExtSuite/TestRequestMessagesSuccess` which it's been randomly breaking builds the last week.

**Comment by divan** [comment]
merging, as test failures are unrelated to it, it's a flaky tests issue

**Comment by adambabik** [comment]
What problem does it solve? Has it been properly tested? I run:
```
$ docker run --rm --memory=50m --memory-swap=50m -it  statusteam/status-go -networkid=1 -discovery=true -standalone=false -shh -topic.search=whisper=10,15 -maxpeers 50 -topic.register=whisper -log=DEBUG -datadir=./test-dir-client -ipc -http -metrics
```
and in logs it prints:
```
INFO [07-11|09:22:43] Status backend initialized
INFO [07-11|09:22:43] LES protocol is disabled                 package=status-go/node
INFO [07-11|09:22:43] SHH protocol is disabled                 package=status-go/node
INFO [07-11|09:22:43] Status service api is disabled           package=status-go/node
```
However, I passed `-shh` option to `CMD`.

This is a correct behaviour with shell entrypoint but I am not sure this is what we want. A solution for this can be exec entrypoint form: `ENTRYPOINT ["/usr/local/bin/statusd"]`. In such a case, my example will work fine. Check out [docs](https://docs.docker.com/engine/reference/builder/#understand-how-cmd-and-entrypoint-interact) for more examples.

**Comment by divan** [comment]
@adambabik I haven't tried it myself, assuming that ENTRYPOINT syntax is straightforward. :/

**Comment by jakubgs** [comment]
I think adding a `CMD ["--help"]` is a good idea. I'll make another PR.

**Comment by jakubgs** [comment]
https://github.com/status-im/status-go/pull/1090

**Pull request merged**
