### PR TITLE
fix(windows-build): Remove free space check for archives

### PR DESCRIPTION
**Pull request by borismelnik**
When I used `syscall.Statfs` for getting the free space on user machine, I introduced the bug for windows. This PR change standard usage of `Statfs` to `gopsutil` implementation

Important changes:
- [x] Something worth noting for reviewers.

Closes #

### CODE REVIEW

**Review by alaibe — APPROVED** [review]

**Comment by cammellos** [comment]
@siddarthkay can you validate the behaviour works fine in relation of the changes we made to make it work on x86_64 emulators?

**Comment by borismelnik** [comment]
@cammellos I never add the new modules to the project and I see the tests was failed. Could you pls helps me, what I should call or add when Im trying to add new module?

**Comment by siddarthkay** [comment]
@cammellos : will review
@borismelnik : do you need help with `make vendor` ?

**Comment by borismelnik** [comment]
> @cammellos : will review
> @borismelnik : do you need help with `make vendor` ?

Yes!

**Comment by siddarthkay** [comment]
it seems this change is incompatible with `gomobile` for iOS
```
Building status-go for iOS...
export GO111MODULE=off; \
gomobile init; \
gomobile bind -v \
-target=ios -ldflags="-s -w" \
-tags 'nowatchdog gowaku_no_rln' \
-ldflags=' -X github.com/status-im/status-go/params.Version=0.171.35 -X 
github.com/status-im/status-go/params.GitCommit=07e05bd48 -X 
github.com/status-im/status-go/params.IpfsGatewayURL=https://ipfs.status.im/' \
-o build/bin/Statusgo.xcframework \
github.com/status-im/status-go/mobile
/nix/store/5aqs07ndvkpk4qj3d3xxc841ysb0hqdd-gomobile-unstable-2022-05-18/bin/gomobile: go install 
golang.org/x/mobile/cmd/gobind@latest failed: exit status 1
```

**Comment by siddarthkay** [comment]
one thing that may help you @borismelnik : you may modify `protocol/communities/manager.go` to only use changes you made by either doing build time checks or compile time checks for only Windows Architecture.
example of build time check -> https://github.com/status-im/tcp-shaker/commit/571aa46f35a5bb72b8bc8306fad2f87bb75def12
example of compile time check -> https://github.com/status-im/status-go/commit/a6df2be92ea15a90a4fb7589060fda04c92dfe6e#diff-fa2036d1728b003fa50e8da7210000d2701d86a28737d94b9466691f783ed16bR26

**Comment by borismelnik** [comment]
> one thing that may help you @borismelnik : you may modify `protocol/communities/manager.go` to only use changes you made by either doing runtime checks or compile time checks for only Windows Architecture.
> example of run time check -> [status-im/tcp-shaker@571aa46](https://github.com/status-im/tcp-shaker/commit/571aa46f35a5bb72b8bc8306fad2f87bb75def12)
> example of compile time check -> [a6df2be#diff-fa2036d1728b003fa50e8da7210000d2701d86a28737d94b9466691f783ed16bR26](https://github.com/status-im/status-go/commit/a6df2be92ea15a90a4fb7589060fda04c92dfe6e#diff-fa2036d1728b003fa50e8da7210000d2701d86a28737d94b9466691f783ed16bR26)

as I understand that we not supporting history archives on mobile?

**Comment by anastasiyaig** [comment]
guys any luck with that? perhaps we can do it separately somehow and revert the changes that initially caused this bug? I need my Windows build back :D @siddarthkay @borismelnik

**Comment by siddarthkay** [comment]
@anastasiyaig : I can take a look later today

**Comment by borismelnik** [comment]
@anastasiyaig @siddarthkay I make decision to revert my changes just to unblock windows build and will add cross-platform implementation in next PR.

**Review by siddarthkay — APPROVED** [review]

**Pull request merged**
