### PR TITLE
chore: deprecate InviteUsersToCommunity

### PR DESCRIPTION
**Pull request by osmaczko**
Add deprecation info to InviteUsersToCommunity

### CODE REVIEW

**Comment by osmaczko** [comment]
@Samyoul do you use `InviteUsersToCommunity` on mobile any longer? Maybe we could remove it altogether.

**Review by 0x-r4bbit — APPROVED** [review]
Also +1 for removing API if mobile doesn't use it (anymore)

**Comment by Samyoul** [comment]
@osmaczko Thank you, looking at the `status-mobile` code we only seem to have an adaptor function for this API method:

```clojure
(rf/defn invite-users
  {:events [::invite-people-confirmation-pressed]}
  [cofx user-pk contacts]
  (let [community-id (fetch-community-id-input cofx)
        pks          (if (seq user-pk)
                       (conj contacts user-pk)
                       contacts)]
    (when (seq pks)
      {:json-rpc/call [{:method      "wakuext_inviteUsersToCommunity"
                        :params      [{:communityId community-id
                                       :users       pks}]
                        :js-response true
                        :on-success  #(re-frame/dispatch [::people-invited %])
                        :on-error    #(do
                                        (log/error "failed to invite-user community" %)
                                        (re-frame/dispatch [::failed-to-invite-people %]))}]})))
```

https://github.com/status-im/status-mobile/blob/109061a112795e32d59052e138e4b4aced5e74d2/src/status_im/communities/core.cljs#L329-L345

The event `invite-people-confirmation-pressed` is only triggered once, but only in the old UI https://github.com/status-im/status-mobile/blob/develop/src/status_im/ui/screens/communities/invite.cljs#L87

However for dealing with deprecated functions we sure mark them `Deprecated` and ultimately removed them once they are no longer being used. We have a kind of tiered deprecation in `status-go`:

- `A`functionality we no longer use and will never use again, have no internal or external dependency.
  - ✅ Safe to remove
- `B` functionality that has become redundant due to other functionality
  - ✅ Safe to remove
- `C` functionality that is partially used and could / should be replace with a better replacement
- `D` functionality we've previously implemented but want to develop further or keep around
- `E` functionality we've introduced but been asked to remove, but subsequently asked to reimplement, then asked to remove again 🙂 
  - Or functionality that is fully formed and we suspect may be asked to be reintroduced 
  - See @igor-sirotin's PR here https://github.com/status-im/status-go/pull/3809 for an example of this case.

I think in this particular case with this PR's deprecation this is some mix of `A` and `B`, so we can open a PR on `status-mobile` and remove it safely.

**Comment by osmaczko** [comment]
@Samyoul thank you very much for detailed description. I will create a separate PR with the removal of `InviteUsersToCommunity` which has been deprecated for less than a week :sweat_smile:

**Pull request merged**
