### PR TITLE
Return compressed key with emojis

### PR DESCRIPTION
**Pull request by ibrkhalil**
Adds the compressed-key on the emoji reaction strct for status-mobile to use

### CODE REVIEW

**Review by cammellos — COMMENTED** [review]
Could you please add a test for this?

**Comment by ibrkhalil** [comment]
> Could you please add a test for this?

Done

**Review by ilmotta — APPROVED** [review]

**Review by cammellos — APPROVED** [review]

**Comment by cammellos** [comment]
@ibrkhalil can this be merged? have you tested it on mobile?

**Comment by ibrkhalil** [comment]
> @ibrkhalil can this be merged? have you tested it on mobile?

Yes, I did
I was awaiting QA approval, But I don't think this is something that should just work.
Will merge

**Pull request merged**
