### PR TITLE
ci: make dest variable an env OUTPUT var

### PR DESCRIPTION
**Pull request by jakubgs**
This should fix issues with re-running builds while skipping some initial stages.

Like here:
image

https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2198/20/

### CODE REVIEW

**Review by Samyoul — APPROVED** [review]

**Comment by jakubgs** [comment]
I'm going to try the re-run with missed stages. To do that I will force a failure.

**Comment by jakubgs** [comment]
```
java.lang.IllegalArgumentException: One or more variables have some issues with their values: ARTIFACT
```
I think it doens't like calls to a library in `environment` block:
```
environment {
    ARTIFACT       = "${env.WORKSPACE}/status-go-desktop-${lib.suffix()}.zip"
    ...
}
```
The call to `lib.suffix()` might not work here.

**Comment by jakubgs** [comment]
Well, this turned into a bit of a refactor, but that's good because I wanted to make `status-go` use `status-jenkins-lib` anyway:

IT WERKS™

image

https://ci.status.im/job/status-go/job/prs/job/linux/job/PR-2224/19/

**Comment by jakubgs** [comment]
One change that i'm not sure about is this: https://github.com/status-im/status-jenkins-lib/commit/2d8fa6d5

I'm not sure if relative checking of `VERSION` file is a good idea... but any other ideas seem messy.

**Comment by jakubgs** [comment]
Don't merge this yet. I have to publish the `status-jenkins-lib` changes into `master` and tag them.

**Comment by jakubgs** [comment]
I also ran a manual build like we do for releases and it worked fine: https://ci.status.im/job/status-go/job/manual/501/

I've changed quite a bit so maybe you should review this again @Samyoul.

**Review by Samyoul — APPROVED** [review]
Looks good. Thank you

**Pull request merged**
