### PR TITLE
Fix syncing of contact request local state

### PR DESCRIPTION
**Pull request by rasom**
needed for https://github.com/status-im/status-mobile/issues/15042 

The problem was that `localState` was updated on `remoteState` change and that caused inconsistent `localState` on synchronised devices.

### CODE REVIEW

**Comment by cammellos** [comment]
@rasom thank you, great work! Could you add a test please? this part is really fiddly and without them is hard to refactor the code.
Thanks

**Comment by rasom** [comment]
@cammellos sure

**Review by ilmotta — APPROVED** [review]

**Review by qfrank — APPROVED** [review]

**Comment by qfrank** [comment]
TestProcessSyncContactRequestState failed 🤔

**Comment by rasom** [comment]
@qfrank yep, should be fixed now

**Comment by rasom** [comment]
@cammellos I added one tiny case which covers specifically the path which caused the bug

**Pull request merged**
