### PR TITLE
[pairing] Do not mark contact as added on unblocking

### PR DESCRIPTION
**Pull request by rasom**
status: ready

needed for https://github.com/status-im/status-react/issues/12673

### CODE REVIEW

**Comment by Samyoul** [comment]
I have a feeling that this PR and https://github.com/status-im/status-go/pull/2372 will have some conflicts.

**Comment by rasom** [comment]
@Samyoul well, shit happens

**Review by Samyoul — APPROVED** [review]
This looks good. In itself I see nothing breaking about this PR.

**Comment by rasom** [comment]
@Samyoul it is even simpler now

**Comment by Samyoul** [comment]
👨‍🍳 This is perfection.

**Pull request merged**
