### PR TITLE
feat: add `pprof` flag to spiff-workflow

### PR DESCRIPTION
**Pull request by richard-ramos**

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [x] Have you tested changes with mobile?
- [x] Have you tested changes with desktop?

**Review by jakubgs — APPROVED** [review]
Thanks.

**Comment by jakubgs** [comment]
I have pushed an image based off of this branch as `deploy-mod-dev`:
```
 > d push statusteam/spiffworkflow-wakunode:deploy-mod-dev
The push refers to repository [docker.io/statusteam/spiffworkflow-wakunode]
4401ed82532c: Pushed 
6faa8f804e3a: Pushed 
133f23fe2ef7: Pushed 
dc4c98bc5b66: Layer already exists 
0059e4bdafac: Layer already exists 
f1417ff83b31: Layer already exists 
deploy-mod-dev: digest: sha256:b4b08a8f6b4aa9dd41a5942253490a77da4d770eb090ca0c1f33b81fa02bcbbb size: 1573
```

**Comment by jakubgs** [comment]
I have configured the pprof flags on the `mod-dev` host:

- https://github.com/status-im/infra-spiff-workflow/commit/a793d9cc - spiff-workflow: add support for pprof flag
- https://github.com/status-im/infra-spiff-workflow/commit/f229401d - spiff: enable wakunode pprof on mod-dev

```
admin@node-01.sm-eu-zur1.spiff.mod-dev:~ % grep pprof /docker/spiff-workflow/docker-compose.yml 
      -pprof=true
      -pprof-port=52525
```
It is worth noting that this node doesn't have normal metrics either.

**Pull request merged**
