### PR TITLE
Fix LES blocking on sync

### LINKED ISSUE #102: Find solution to blocking `eth` calls (during sync)
**Problem**
- `eth` is not responsive up until sync is done
- tested in `geth --light --testnet console`, no `eth` calls is possible if LES headers sync is in progress

**Notes:**
- this issue is claimed to be solved by https://github.com/ethereum/go-ethereum/pull/3519 (but it isn't)
- issue introduced in https://github.com/ethereum/go-ethereum/commit/c57c54ce96628aeb6345776310123a80593f0143

**Resolution:**
- create bug fix request by describing the issue
- briefly review if solution can be found, if so then file PR to that bug fix request

### PR DESCRIPTION
**Pull request by farazdagi**
- fixes #102 
- we need to check with chain data reset (to see that blocking doesn't occur indeed)
- please note that https://github.com/ethereum/go-ethereum/pull/3660 hasn't been merged yet (I've tested the code, but due to whole complexity of the issue, I am not 100% sure there are no issues left)
- if ^^ PR will be merged w/o any more changes (after https://github.com/ethereum/go-ethereum/pull/3660/commits/fe38042772b96c5132d272d4534a75f179e4e6f7), then it is safe to proceed w/ merging

### CODE REVIEW

**Comment by rasom** [comment]
I've just tested `status-react` using this branch, and it looks like we still have a problem. 

So, currently, when we are calling `web3.eth` while app is syncing it locks request:

```
02-11 12:27:55.469 19869 19965 D StatusModule: ["commands","send","validator"]
02-11 12:27:55.469 19869 20538 D StatusModule: startCallJail
02-11 12:30:12.509 19869 20538 D StatusModule: endCallJail

~2 mins
```

The only difference is that we can get response before node is fully synced.

**Comment by farazdagi** [comment]
- Zsolt has added number of new commits, will see what they add to the stock.
- There's a certain delay when I try to dump `eth` on console, not 2 minutes of course
- I will probably need to look into our jail code too, to make sure we don't have contention there

**Comment by farazdagi** [comment]
It was quite a ride, hopefully we will now be able to wrap this up.

Number of notes:
- while blocking during sync was resolved on `go-ethereum` side, delay that @rasom has reported the last time (~2mins) is still there
- I have produced our own fix, and let Zsolt know about it https://github.com/ethereum/go-ethereum/pull/3660#issuecomment-280182354
- I've spent **lots** of time testing, so this PR contains test (https://github.com/status-im/status-go/pull/107/files#diff-7a361c6d3aa516317ac8022c7ccef360R745) where I make sure I try to `eth_getBalance()`, `eth_getTransactionCount()`, `eth_sendTransaction()` (for **both** ETH sending and contract creation). Everything works w/o any blocking/delays, beyond reasonable latency

Please let me know if you spot anything. And if you do, ideally, I'd like to have a JS to reproduce the issue (I've spent considerable amount of time testing under different circumstances, but might miss something).

Finally, regarding all this non-blocking during sync. Please note that you get result on current state of database i.e. you will get balance, or nonce, or tx count or anything as it is seen in the currently synced block. Which can be misleading (and quickly changing as sync is in progress). So, if you sync from the beginning - your obtained information becomes outdated quickly. There's no "live" querying, all requests go to DB state, which gets synced, thus you need to sync to the latest block to get the latest state of the database.

So, if you get "nonce is too low" error when trying sending transaction **while non-synced** - it is expected. Even if you do not get error (can happen, as nonce validation is really primitive in `go-ethereum`, ping me for details if interested), your tx will not be added to blockchain - fully synced peers will reject it.

Overall, this means that while we do not have a blocking behavior (at least shouldn't have it anymore), it is important to understand the limitations. If our use case: user has already almost synced db, then goes offline, then online, and while syncing wants to have access to app - then it will probably work relatively smoothly.

**Comment by jarradh** [comment]
How is this done if it still contains the 2 minute delay?

**Comment by farazdagi** [comment]
We circumvented the problem by updating all other packages, except for the LES (and we will keep it this way, up until the issue with LES blocking is properly resolved on `go-ethereum` side).

In the meantime, the following branches are available:
- https://github.com/status-im/status-go/commits/geth/1.5.6-stable-with-non-blocking-les
- https://github.com/status-im/status-go/commits/geth/1.5.7-stable-with-non-blocking-les
- https://github.com/status-im/status-go/commits/geth/1.5.8-stable-with-non-blocking-les
- https://github.com/status-im/status-go/commits/geth/1.5.9-stable-with-non-blocking-les

**Pull request closed without merging**
