### PR TITLE
Comment out flaky tests

### PR DESCRIPTION
**Pull request by rasom**
A new portion of commented out flaky tests. "Success metric" is again 5 consecutive green builds.

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by rasom** [comment]
https://github.com/status-im/status-go/issues/4695 @osmaczko @cammellos 
https://github.com/status-im/status-go/issues/4740 @osmaczko 
https://github.com/status-im/status-go/issues/4752 @vitvly
https://github.com/status-im/status-go/issues/4751 @MishkaRogachev 
https://github.com/status-im/status-go/issues/4749 @saledjenic
https://github.com/status-im/status-go/issues/4697  @cammellos @osmaczko  @MishkaRogachev
https://github.com/status-im/status-go/issues/4750 @osmaczko @0x-r4bbit 

^ the list is based on git-blame so it might be not a perfect match, sorry for that

**Review by siddarthkay — APPROVED** [review]

**Comment by MishkaRogachev** [comment]
I'm not very sure about `MessengerContactRequestSuite`, I haven't observed on CI that it crashes there for a long time. I'll try to replicate the problem locally

**Comment by jrainville** [comment]
@rasom thanks for tracking all the flaky tests.

However, I don't think commenting them out is a good way forward. There is a strong chance that we might introduce regressions by accident with those tests commented.

A better way would be to add a flag to those tests and make them retry or something. I'm not sure if that's something that's supported in Go.

Anyway, my team and I discussed it and we think it would be preferable to revert this PR to avoid those regressions. 

What do you think?

**Comment by rasom** [comment]
@jrainville I think there are basically 3 options
1. Commenting out flaky tests
2. Uncommenting them when they are not flaky (e.g. solution you proposed)
3. Giving everyone right to force push or, option which would be equally bad, remove successful tests run from requirements on merging 

The rest of it is unacceptable. I spent days rerunning flaky tests in order to get my PRs merged. 

The only way to go here is to uncomment them when they are "reasonably not flaky". The metric I proposed once is to run it successfully 1000 times locally before merging. Propose your option. But then when it is proven that it is flaky anyway - requirements for that test should be tighten even further. Or you can add automatic reruns of those specific tests. Or something else. But not to uncomment it until it's known it is flaky and it forces devs to ru-run test for nothing. If there is an option to keep it a local thing but not include it to the build - again, up to you. And so forth...

**I'm 100% against revert/uncommenting before it is fixed.**

**Comment by rasom** [comment]
> I'm not very sure about `MessengerContactRequestSuite`, I haven't observed on CI that it crashes there for a long time. I'll try to replicate the problem locally

@MishkaRogachev I reported it two weeks ago (that's likely the first time I've encountered it), since that I've seen it 2-3 times in my PRs. So that depends on what you mean as "a long time" here.

**Comment by osmaczko** [comment]
I understand the frustration, but we should [keep these tests at least compilable](https://github.com/status-im/status-go/pull/4759/commits/a39d19718b7ad359f049f51b4d7b5a3ca71e97b4) and not just comment them out.

We are missing a process to identify flaky tests. Some tests may become flaky with a change in a potentially unrelated part; we must have a way to monitor it and address it asap. Disabling tests should be a last resort.

Once again, I will point to: https://github.com/status-im/status-go/issues/4264. We should monitor test flakiness on a daily basis. The results of nightly tests are useless due to: https://github.com/status-im/status-go/issues/4586 and https://github.com/status-im/status-go/issues/4585. @jrainville, @cammellos, could you please take these issues into account when planning the priorities for the next sprint? I am pretty sure we'll spend way more time on possible regressions that flaky tests otherwise would catch than on fixing these two issues.

**Comment by dlipicar** [comment]
My 2 argentinean peso cents:
1) Keeping them compilable bothers no one and helps a lot.
2) Having to automatically retry tests many times for them to pass makes test runs much longer, which makes people mad.
3) Having to manually retry tests a bunch of times to get PRs merged because some completely unrelated test is flaky makes everybody mad.
4) 2 is tolerable, 3 really isn't.

IMO the flow should be:
1) Detect a flaky test (Bonus track: Have nightly builds run every test N times to find flaky ones faster?)
2) Decide who's responsible for fixing it, create a high-priority Issue so we can re-introduce it ASAP
3) a) If it has a high chance of succeeding, use some automatic retry mechanism. Make sure it doesn't make test runs much longer and that it's basically certain it'll eventually pass. That way we can at least still catch some changes that actually break the test.
b) If we cannot be certain it will pass within a reasonable time, disable it not to slow down other devs' progress.
4) Eventually remove retries/re-introduce the test when it's stable.

No idea what's happening in these tests, but this situation seems to reoccur every now and then. Is there a pattern we can detect and try to avoid in the future?
- Timeouts -> How long things take depends on system load. Adjust timeout periods accordingly? Mock the system timer wherever possible?
- Access to remote resources -> We normally want to test that our code changes work and not whether some resource is accesible. Mock remote resource for PR test runs and have separate "remote resource availability tests" or "integration tests" which are only executed on nightly runs?
- Random crashes -> I guess there's not much we can do here...

**Pull request merged**
