### PR TITLE
Rebase on geth 1.7.2

### PR DESCRIPTION
**Pull request by adambabik**
Corresponding status-im/go-ethereum branch: https://github.com/status-im/go-ethereum/tree/status/1.7.2-stable

### CODE REVIEW

**Comment by JekaMas** [comment]
I`ve got failed test:
```--- FAIL: TestConfigWriteRead (0.00s)
        Error Trace:    config_test.go:454
	            	config_test.go:457
```

**Comment by adambabik** [comment]
@tiabc the problem with cluster geth 1.7.x nodes and synchronization was resolved? I tried to sync from scratch (removed data directory) and it's slow with a lot of issues like:
```
WARN [10-16|17:01:47] Rolled back headers                      count=96   header=1699135->1699135 fast=0->0 block=0->0
WARN [10-16|17:01:47] Synchronisation failed, dropping peer    peer=e006f0b2dc98e757 err="retrieved hash chain is invalid"
WARN [10-16|17:01:47] message loop                             peer=e006f0b2dc98e757 err=EOF
```

@JekaMas what command did you run? I had this error but it was fixed in `ad1c265`.

**Comment by JekaMas** [comment]
I`ve rechecked it: on 'ad1c265' test failes, but on '6e1b8fc' all is ok.

**Comment by tiabc** [comment]
@adambabik which network? If Ropsten, I've just re-deployed our dev cluster and it may be still syncing, for example.
I've also faced these errors, by the way, not sure where they come from, I wanted to ask you to investigate that :)

**Comment by tiabc** [comment]
Can you confirm that all failing on CI tests passes locally? Also, please, merge `develop`, there're a lot of changes.

**Comment by themue** [comment]
`./e2e/transactions/...` locally leads to a timeout together with *no suitable peers*. So will look how my peer fix helps here.

**Comment by themue** [comment]
Still timeout of `statusd` test.

**Comment by adambabik** [comment]
I checked syncing from scratch and run all unit and e2e tests locally, they all passed. Also, I rebased against the current develop. IMO it's ready to be merged.

**Pull request merged**
