### PR TITLE
Chore/keep flaky tests compilable

### PR DESCRIPTION
**Pull request by osmaczko**
fix: keep flaky tests compilable and easy to find

### CODE REVIEW

**Review by igor-sirotin — APPROVED** [review]
I still have a strong opinion that we shouldn't postpone fixing the flaky tests. 

By disabling them we will only introduce even more regressions. We either spend X time units now to fix the flaky tests, or later we spend same X and +Y on top to fix the introduced regressions. 

It's very dangerous and will be very harmful.
We shouldn't underestimate the unavoidable consequences.

**Comment by osmaczko** [comment]
> I still have a strong opinion that we shouldn't postpone fixing the flaky tests.
> 
> By disabling them we will only introduce even more regressions. We either spend X time units now to fix the flaky tests, or we spend X later and +Y to fix the introduced regressions.
> 
> It's very dangerous and will be very harmful. We shouldn't underestimate the unavoidable consequences.

I have the same opinion, I just improved the way how they are disabled.

**Review by jrainville — APPROVED** [review]
That's a good first step. At least tests will be compiled and remain compatible. Doesn't fix possible regressions, but it's nice

**Comment by MishkaRogachev** [comment]
just suggestion: maybe we can try [skip](https://pkg.go.dev/testing#:~:text=documentation%20about%20fuzzing.-,Skipping,func%20TestTimeConsuming(t%20*testing. ) from the test package

**Pull request merged**
