### PR TITLE
Fix lint on unused method

### PR DESCRIPTION
**Pull request by adriacidre**
Make lint prompts an error on transactor_test.go

```
make lint
lint
geth/transactions/transactor_test.go:85:28:warning: func (*TxQueueTestSuite).completeFunc is unused (U1000) (megacheck)
make: *** [lint] Error 1
```

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]
oops, a leftover :) thanks for fixing!

**Comment by mandrigin** [comment]
@adriacidre I think you can merge it after the CI is green, it is a very simple change anyway.

**Comment by dshulyak** [comment]
btw just noticed that it fails locally, but my ci passed and this change is definitely in tree 

https://travis-ci.org/status-im/status-go/builds/364584371

<blockquote><div><strong><a href="https://travis-ci.org/status-im/status-go/builds/364584371">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div></blockquote>

**Review by themue — APPROVED** [review]

**Comment by adriacidre** [comment]
@themue yep, it's really strange, maybe moving `make lint` and `vendor check` to the same step broke something, i'll try to investigate and open another PR.

**Comment by themue** [comment]
@adriacidre Will just give it a try here too.

**Comment by adriacidre** [comment]
> @themue yep, it's really strange, maybe moving make lint and vendor check to the same step broke something, i'll try to investigate and open another PR.

sorry, I meant @dshulyak

**Comment by themue** [comment]
@adriacidre N.p., just tested and it locally fails here too.

**Pull request merged**
