### PR TITLE
[#11468] Hide/show option for accounts in the wallet

### PR DESCRIPTION
**Pull request by flexsurfer**
Hide/show option for accounts in the wallet

### CODE REVIEW

**Review by Samyoul — APPROVED** [review]
👍

**Comment by flexsurfer** [comment]
@Samyoul could you pls help with test, have no idea why they fail

**Comment by Samyoul** [comment]
Hey @flexsurfer I've had a look at the error logs and the main error that keeps coming up is 

```
Received unexpected error:
[2021-08-11T06:07:11.096Z]         	            	no such table: accounts in line 0: ALTER TABLE accounts ADD COLUMN hidden BOOL NOT NULL DEFAULT FALSE;
```

Which says to me that the migration is targeting the wrong DB. I will have a look for you and share the fix

**Comment by Samyoul** [comment]
So the fix is to move the migration file from

```
renamed:    protocol/migrations/sqlite/1628580203_add_hidden_account.up.sql -> appdatabase/migrations/sql/1628580203_add_hidden_account.up.sql
```

Then run `make generate`

On my local machine the tests pass after that.

```
=== RUN   TestSQLitePersistenceSuite
--- PASS: TestSQLitePersistenceSuite (0.50s)
=== RUN   TestSQLitePersistenceSuite/TestExists
    --- PASS: TestSQLitePersistenceSuite/TestExists (0.13s)
=== RUN   TestSQLitePersistenceSuite/TestSaveAndRetrieve
    --- PASS: TestSQLitePersistenceSuite/TestSaveAndRetrieve (0.12s)
=== RUN   TestSQLitePersistenceSuite/TestSaveAndRetrieveIdentity
    --- PASS: TestSQLitePersistenceSuite/TestSaveAndRetrieveIdentity (0.12s)
=== RUN   TestSQLitePersistenceSuite/TestSaveDifferentIdenities
    --- PASS: TestSQLitePersistenceSuite/TestSaveDifferentIdenities (0.13s)
PASS

Process finished with exit code 0
```

**Pull request merged**
