### PR TITLE
Better logs and more robust download handling for community archives

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
There's descriptions in each commit but in a nutshell:

- Adding better logs to history archive handling for better debugging
- Better handling of multiple magnetlinks that are being processed at roughly the same time (proper interruption of download and data import with resumability)
- Tracking of which archives were successfully imported (not just downloaded)

### CODE REVIEW

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://status.im/docs/))?
- [ ] Have you tested changes with mobile?
- [ ] Have you tested changes with desktop?

**Review by richard-ramos — APPROVED** [review]
Looks good!
Not a show stopper, but could you remove the migrations files / bindata that are not really affected by this change?

**Comment by 0x-r4bbit** [comment]
@richard-ramos thank you for the review: done

**Comment by 0x-r4bbit** [comment]
I'm refactoring this to make use of `sync.WaitGroup`s so we properly wait until the ongoing magnetlink process has been cancelled before we spin up the next.

This has uncovered some interesting deadlock cases with the mutex used in message processing.
Please do not merge this yet until I've updated this.

**Comment by 0x-r4bbit** [comment]
@richard-ramos would you mind giving this another look?
This is now refactored as per discussion to ensure current download/import task is cancelled before we start a new one

**Review by richard-ramos — APPROVED** [review]
:100:

**Pull request merged**
