### PR TITLE
fix_: update enr for staging fleet node whose peerID is changed

### PR DESCRIPTION
**Pull request by chaitanyaprem**
The staging fleet node `boot-01.do-ams3.status.staging` had its peerID changed about 2 months ago. 

But the ENR specified in cluster config still points to the older peerID which is no longer valid. Hence it leads to connection failures since it is one of the bootnodes. 

This PR updates the enr to the correct one as per https://fleets.status.im/

### CODE REVIEW

**Review by kaichaosun — APPROVED** [review]

**Review by igor-sirotin — APPROVED** [review]

**Comment by chaitanyaprem** [comment]
Note that i am not merging this until enrtree is also updated for staging which would also need to be changed in the code. 
I will wait for @siddarthkay to update the enrtree and then change it and merge.

**Comment by siddarthkay** [comment]
I've updated DNS entries for status.staging with : 

```
[nix-shell:~/code/status-im/infra-utils]$ ssh -L 8500:127.0.0.1:8500 -N 
  -f siddarth@node-01.do-ams3.waku.sandbox
[nix-shell:~/code/status-im/infra-utils]$ export PRIVATE_KEY=$(pass services/dns-discovery/prod/staging/private-key)
[nix-shell:~/code/status-im/infra-utils]$ export CF_TOKEN=$(pass cloud/Cloudflare/token)
[nix-shell:~/code/status-im/infra-utils]$ consul/dnsdisc.py -e status -s staging 
  -d store.staging.status.nodes.status.im -n nim-waku-enr 
  -C /Users/siddarthkumar/code/status-im/infra-utils/nim-dnsdisc/build/tree_creator -i nim-waku-store-enr
[INFO] Service found: store-01.do-ams3.status.staging:nim-waku-store-enr
[INFO] Service found: store-02.do-ams3.status.staging:nim-waku-store-enr
[INFO] Service found: store-01.gc-us-central1-a.status.staging:nim-waku-store-enr
[INFO] Service found: store-02.gc-us-central1-a.status.staging:nim-waku-store-enr
[INFO] Service found: store-01.ac-cn-hongkong-c.status.staging:nim-waku-store-enr
[INFO] Service found: store-02.ac-cn-hongkong-c.status.staging:nim-waku-store-enr
[INFO] Deleting record: 2nm67iglh6ppy4aynir3imkorm.store.staging.status.nodes.status.im
[INFO] Deleting record: 7pitefne2vhtt3wkpetgpoubna.store.staging.status.nodes.status.im
[INFO] Deleting record: store.staging.status.nodes.status.im
[INFO] Deleting record: v6wvb5dykwjfkfnkhyiancrnjm.store.staging.status.nodes.status.im
[INFO] Creating record: dcvgwycmzityxcbu24pch6ytzq.store.staging.status.nodes.status.im
[INFO] Creating record: h6nounnpdh2wlul75347zkmfie.store.staging.status.nodes.status.im
[INFO] Creating record: isp4dshdwiexmzchsnenyibj2m.store.staging.status.nodes.status.im
[INFO] Creating record: store.staging.status.nodes.status.im
[INFO] URL: 
enrtree://AI4W5N5IFEUIHF5LESUAOSMV6TKWF2MB6GU2YK7PU4TYUGUNOCEPW@store.staging.status.nodes.status.im

```

**Review by plopezlpz — APPROVED** [review]

**Review by jakubgs — APPROVED** [review]
Looks correct to me:
```
jakubgs@boot-01.do-ams3.status.staging:~ % /docker/nim-waku-boot/api.sh /debug/v1/info | grep enrUri 
  "enrUri": "enr:-QEQuEBuiQgFlJNcv255042zwyl4pOBOivakX8N30Dr9vaaEU2q8-7N4GVY4Hk87iEKELjlIXTpE9Wj6EQq1lrBuc7ayAYJpZIJ2NIJpcISPxvrpim11bHRpYWRkcnO4YAAtNihib290LTAxLmRvLWFtczMuc3RhdHVzLnN0YWdpbmcuc3RhdHVzLmltBnZfAC82KGJvb3QtMDEuZG8tYW1zMy5zdGF0dXMuc3RhZ2luZy5zdGF0dXMuaW0GAbveA4Jyc40AEAUAAQAgAEAAgAEAiXNlY3AyNTZrMaEDq-yGgpuoUG6NKkbIDRmrMiT-bEVzFlpWLEK_rF3yKUaDdGNwgnZfg3VkcIIjKIV3YWt1Mg0"
```

**Comment by siddarthkay** [comment]
@chaitanyaprem mentioned that for boot.staging nodes the ENRTree referenced old peerIds.
So I regenerated them with : 

```
[nix-shell:~/code/status-im/infra-utils]$ consul/dnsdisc.py -e status -s staging -d boot.staging.status.nodes.status.im -n nim-waku-enr -C /Users/siddarthkumar/code/status-im/infra-utils/nim-dnsdisc/build/tree_creator -i nim-waku-boot-enr
[INFO] Service found: boot-01.do-ams3.status.staging:nim-waku-boot-enr
[INFO] Service found: boot-01.gc-us-central1-a.status.staging:nim-waku-boot-enr
[INFO] Service found: boot-01.ac-cn-hongkong-c.status.staging:nim-waku-boot-enr
[INFO] Deleting record: boot.staging.status.nodes.status.im
[INFO] Deleting record: odkcy7sc2ij6dvgfd3rojse2c4.boot.staging.status.nodes.status.im
[INFO] Deleting record: wrgrhlrn5c5njfit6tora7finu.boot.staging.status.nodes.status.im
[INFO] Creating record: boot.staging.status.nodes.status.im
[INFO] Creating record: m4p6qp7ufjzmj6clg5g3tqau3i.boot.staging.status.nodes.status.im
[INFO] Creating record: sga7hjagwtl3tzoolr6pjwaz3u.boot.staging.status.nodes.status.im
[INFO] URL: enrtree://AI4W5N5IFEUIHF5LESUAOSMV6TKWF2MB6GU2YK7PU4TYUGUNOCEPW@boot.staging.status.nodes.status.im
```

**Comment by chaitanyaprem** [comment]
enrtree remains the same and resolves to new peerID now. 

`    waku_test.go:215: node discovered is: 16Uiu2HAmQE7FXQc6iZHdBzYfw3qCSDa9dLc1wsBJKoP4aZvztq2d , its enr: enr:-QEQuEBuiQgFlJNcv255042zwyl4pOBOivakX8N30Dr9vaaEU2q8-7N4GVY4Hk87iEKELjlIXTpE9Wj6EQq1lrBuc7ayAYJpZIJ2NIJpcISPxvrpim11bHRpYWRkcnO4YAAtNihib290LTAxLmRvLWFtczMuc3RhdHVzLnN0YWdpbmcuc3RhdHVzLmltBnZfAC82KGJvb3QtMDEuZG8tYW1zMy5zdGF0dXMuc3RhZ2luZy5zdGF0dXMuaW0GAbveA4Jyc40AEAUAAQAgAEAAgAEAiXNlY3AyNTZrMaEDq-yGgpuoUG6NKkbIDRmrMiT-bEVzFlpWLEK_rF3yKUaDdGNwgnZfg3VkcIIjKIV3YWt1Mg0
`

**Pull request merged**
